In [1]:
import pandas as pd

twitter_path = r"C:\Users\danie\supportmind-ai\rawsupportminddata\Customer Support on Twitter\twcs\twcs.csv"

df_twitter = pd.read_csv(twitter_path)

print("Shape:", df_twitter.shape)
print("\nColumns:")
print(df_twitter.columns.tolist())

Shape: (2811774, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [2]:
print(df_twitter.info())

<class 'pandas.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                str
 2   inbound                  bool
 3   created_at               str
 4   text                     str
 5   response_tweet_id        str
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 557.8 MB
None

In [3]:
print("\nMissing values:")
print(df_twitter.isnull().sum().sort_values(ascending=False))

print("\nMissing value percentage:")
print(
    (df_twitter.isnull().mean() * 100)
    .sort_values(ascending=False)
    .round(2)
)

Missing values:
response_tweet_id          1040629
in_response_to_tweet_id     794335
tweet_id                         0
inbound                          0
author_id                        0
text                             0
created_at                       0
dtype: int64

Missing value percentage:
response_tweet_id          37.01
in_response_to_tweet_id    28.25
tweet_id                    0.00
inbound                     0.00
author_id                   0.00
text                        0.00
created_at                  0.00
dtype: float64

In [4]:
print("\nUnique values:")
for column in df_twitter.columns:
    print(f"{column}: {df_twitter[column].nunique():,}")

Unique values:
tweet_id: 2,811,774
author_id: 702,777
inbound: 2
created_at: 2,061,666
text: 2,782,618
response_tweet_id: 1,771,145
in_response_to_tweet_id: 1,774,822

In [5]:
print(df_twitter["inbound"].value_counts())

print("\nPercentages:")
print(
    (df_twitter["inbound"].value_counts(normalize=True) * 100)
    .round(2)
)

inbound
True     1537843
False    1273931
Name: count, dtype: int64

Percentages:
inbound
True     54.69
False    45.31
Name: proportion, dtype: float64

In [6]:
for value in [True, False]:
    print("=" * 80)
    print(f"INBOUND = {value}")
    print("=" * 80)

    samples = df_twitter.loc[
        df_twitter["inbound"] == value,
        ["tweet_id", "author_id", "text"]
    ].head(10)

    for _, row in samples.iterrows():
        print(f"\nTweet ID: {row['tweet_id']}")
        print(f"Author: {row['author_id']}")
        print(f"Text: {row['text']}")

================================================================================
INBOUND = True
================================================================================

Tweet ID: 2
Author: 115712
Text: @sprintcare and how do you propose we do that

Tweet ID: 3
Author: 115712
Text: @sprintcare I have sent several private messages and no one is responding as usual

Tweet ID: 5
Author: 115712
Text: @sprintcare I did.

Tweet ID: 8
Author: 115712
Text: @sprintcare is the worst customer service

Tweet ID: 12
Author: 115713
Text: @sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯

Tweet ID: 16
Author: 115713
Text: @sprintcare Since I signed up with you....Since day 1

Tweet ID: 18
Author: 115713
Text: @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Tweet ID: 20
Author: 115715
Text: @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Tweet ID: 22
Author: 115716
Text: @Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?

Tweet ID: 26
Author: 115716
Text: @Ask_Spectrum I received this from your corporate office would you like a copy?
================================================================================
INBOUND = False
================================================================================

Tweet ID: 1
Author: sprintcare
Text: @115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.

Tweet ID: 4
Author: sprintcare
Text: @115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.

Tweet ID: 6
Author: sprintcare
Text: @115712 Can you please send us a private message, so that I can gain further details about your account?

Tweet ID: 11
Author: sprintcare
Text: @115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC

Tweet ID: 15
Author: sprintcare
Text: @115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA

Tweet ID: 17
Author: sprintcare
Text: @115713 H there! We'd definitely like to work with you on this, how long have you been experiencing this issue? -AA

Tweet ID: 19
Author: sprintcare
Text: @115715 Please send me a private message so that I can send you the link to access your account. -FR

Tweet ID: 21
Author: Ask_Spectrum
Text: @115716 What information is incorrect? ^JK

Tweet ID: 25
Author: Ask_Spectrum
Text: @115716 Our department is part of the corporate office.  If you're particular area has gone to this format, we were unawa... https://t.co/P7XCmTzPQj

Tweet ID: 27
Author: Ask_Spectrum
Text: @115716 No thank you. ^JK

In [7]:
print("response_tweet_id examples:")
print(
    df_twitter["response_tweet_id"]
    .dropna()
    .head(20)
    .tolist()
)

print("\nin_response_to_tweet_id examples:")
print(
    df_twitter["in_response_to_tweet_id"]
    .dropna()
    .head(20)
    .tolist()
)

response_tweet_id examples:
['2', '1', '3', '4', '5,7', '9,6,10', '11,13,14', '12', '15', '16', '17', '19', '22,23', '25', '26', '27', '21', '24', '28', '30']

in_response_to_tweet_id examples:
[3.0, 1.0, 4.0, 5.0, 6.0, 8.0, 12.0, 15.0, 16.0, 17.0, 18.0, 20.0, 24.0, 21.0, 22.0, 25.0, 26.0, 21.0, 28.0, 29.0]

In [8]:
print("Tweets with a response:")
print(df_twitter["response_tweet_id"].notna().value_counts())

print("\nTweets that are responses:")
print(df_twitter["in_response_to_tweet_id"].notna().value_counts())

Tweets with a response:
response_tweet_id
True     1771145
False    1040629
Name: count, dtype: int64

Tweets that are responses:
in_response_to_tweet_id
True     2017439
False     794335
Name: count, dtype: int64

In [9]:
print(
    df_twitter[
        [
            "tweet_id",
            "inbound",
            "response_tweet_id",
            "in_response_to_tweet_id"
        ]
    ].head(30).to_string(index=False)
)

 tweet_id  inbound response_tweet_id  in_response_to_tweet_id
        1    False                 2                      3.0
        2     True               NaN                      1.0
        3     True                 1                      4.0
        4    False                 3                      5.0
        5     True                 4                      6.0
        6    False               5,7                      8.0
        8     True            9,6,10                      NaN
       11    False               NaN                     12.0
       12     True          11,13,14                     15.0
       15    False                12                     16.0
       16     True                15                     17.0
       17    False                16                     18.0
       18     True                17                      NaN
       19    False               NaN                     20.0
       20     True                19                      NaN
       21    False             22,23                     24.0
       22     True                25                     21.0
       25    False                26                     22.0
       26     True                27                     25.0
       27    False               NaN                     26.0
       23     True               NaN                     21.0
       24     True                21                     28.0
       28    False                24                     29.0
       29     True                28                      NaN
       30    False               NaN                     31.0
       31     True                30                      NaN
       32    False               NaN                     33.0
       33     True                32                      NaN
       34    False                35                     36.0
       35     True                37                     34.0

In [10]:
response_counts = (
    df_twitter["response_tweet_id"]
    .dropna()
    .astype(str)
    .str.split(",")
    .str.len()
)

print("Tweets with response IDs:", len(response_counts))
print("\nResponse count distribution:")
print(response_counts.value_counts().sort_index().head(20))

print("\nStatistics:")
print(response_counts.describe())

Tweets with response IDs: 1771145

Response count distribution:
response_tweet_id
1     1548719
2      172743
3       31306
4        8873
5        3204
6        1557
7         897
8         564
9         460
10        290
11        255
12        194
13        160
14        166
15        107
16        111
17         81
18         92
19         81
20         53
Name: count, dtype: int64

Statistics:
count    1.771145e+06
mean     1.234273e+00
std      4.141607e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.755000e+03
Name: response_tweet_id, dtype: float64

In [11]:
print("Maximum responses linked to one tweet:",
      response_counts.max())

print("\nTweets with multiple response IDs:",
      (response_counts > 1).sum())

print("Percentage with multiple responses:",
      round((response_counts > 1).mean() * 100, 2))

Maximum responses linked to one tweet: 1755

Tweets with multiple response IDs: 222426
Percentage with multiple responses: 12.56

In [12]:
response_count_by_role = df_twitter.copy()

response_count_by_role["response_count"] = (
    response_count_by_role["response_tweet_id"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: len([v for v in x.split(",") if v.strip()])
        if x.strip()
        else 0
    )
)

print("Response count by inbound role:")
print(
    response_count_by_role
    .groupby("inbound")["response_count"]
    .describe()
)

print("\nMultiple-response tweets by inbound role:")
print(
    response_count_by_role
    .groupby("inbound")["response_count"]
    .apply(lambda x: (x > 1).sum())
)

print("\nPercentage with multiple responses by inbound role:")
print(
    response_count_by_role
    .groupby("inbound")["response_count"]
    .apply(lambda x: round((x > 1).mean() * 100, 2))
)

Response count by inbound role:
             count      mean       std  min  25%  50%  75%     max
inbound
False    1273931.0  0.494765  4.499396  0.0  0.0  0.0  1.0  1755.0
True     1537843.0  1.011664  1.874320  0.0  1.0  1.0  1.0  1090.0

Multiple-response tweets by inbound role:
inbound
False     60471
True     161955
Name: response_count, dtype: int64

Percentage with multiple responses by inbound role:
inbound
False     4.75
True     10.53
Name: response_count, dtype: float64

In [13]:
# Tweets that explicitly point to another tweet
has_parent = df_twitter["in_response_to_tweet_id"].notna()

print("Tweets with a parent tweet:")
print(has_parent.sum())

print(
    "Percentage with parent:",
    round(has_parent.mean() * 100, 2)
)

print("\nParent tweet ID uniqueness:")
print(
    df_twitter.loc[has_parent, "in_response_to_tweet_id"]
    .astype(int)
    .nunique()
)

print("\nTweets without parent:")
print((~has_parent).sum())

Tweets with a parent tweet:
2017439
Percentage with parent: 71.75

Parent tweet ID uniqueness:
1774822

Tweets without parent:
794335

In [14]:
# Tweets that are not replies are potential conversation roots
roots = df_twitter[
    df_twitter["in_response_to_tweet_id"].isna()
].copy()

print("Potential conversation roots:", len(roots))

print("\nRoot tweets by inbound role:")
print(
    roots["inbound"]
    .value_counts()
    .rename(index={
        True: "Customer",
        False: "Company"
    })
)

print("\nRoot tweet role percentages:")
print(
    (roots["inbound"].value_counts(normalize=True) * 100)
    .round(2)
    .rename(index={
        True: "Customer",
        False: "Company"
    })
)

Potential conversation roots: 794335

Root tweets by inbound role:
inbound
Customer    787346
Company       6989
Name: count, dtype: int64

Root tweet role percentages:
inbound
Customer    99.12
Company      0.88
Name: proportion, dtype: float64

In [15]:
# Build a parent lookup: tweet_id -> parent tweet ID
parent_map = (
    df_twitter
    .dropna(subset=["in_response_to_tweet_id"])
    .set_index("tweet_id")["in_response_to_tweet_id"]
    .to_dict()
)

def get_depth(tweet_id, parent_map, max_depth=100):
    depth = 0
    current = tweet_id
    visited = set()

    while current in parent_map:
        if current in visited:
            break

        visited.add(current)

        parent = parent_map[current]

        if parent is None:
            break

        current = int(parent)
        depth += 1

        if depth >= max_depth:
            break

    return depth


# Analyze a manageable diagnostic subset first.
# This does NOT reduce the dataset for modelling.
sample_ids = df_twitter["tweet_id"].head(10000)

depths = sample_ids.apply(
    lambda x: get_depth(x, parent_map)
)

print("Tweets analysed:", len(depths))

print("\nDepth distribution:")
print(depths.value_counts().sort_index())

print("\nDepth statistics:")
print(depths.describe())

Tweets analysed: 10000

Depth distribution:
tweet_id
0      2731
1      2870
2      1394
3      1030
4       544
       ...
96        1
97        1
98        1
99        1
100      30
Name: count, Length: 101, dtype: int64

Depth statistics:
count    10000.000000
mean         2.916800
std          8.197548
min          0.000000
25%          0.000000
50%          1.000000
75%          3.000000
max        100.000000
Name: tweet_id, dtype: float64

In [16]:
print("Depth distribution (0–20):")
print(
    depths.value_counts()
    .sort_index()
    .loc[lambda x: x.index <= 20]
)

print("\nTweets at diagnostic depth cap (100):")
print((depths == 100).sum())

print(
    "\nPercentage at depth cap:",
    round((depths == 100).mean() * 100, 2)
)

Depth distribution (0–20):
tweet_id
0     2731
1     2870
2     1394
3     1030
4      544
5      408
6      251
7      190
8      109
9       92
10      50
11      42
12      31
13      21
14      18
15      19
16      19
17      15
18      13
19      10
20       7
Name: count, dtype: int64

Tweets at diagnostic depth cap (100):
30

Percentage at depth cap: 0.3

In [17]:
text_stats_by_role = (
    df_twitter
    .assign(
        char_count=df_twitter["text"].str.len(),
        word_count=df_twitter["text"].str.split().str.len()
    )
    .groupby("inbound")[["char_count", "word_count"]]
    .describe()
)

print(text_stats_by_role)

        char_count                                                         \
             count        mean        std  min   25%    50%    75%    max
inbound
False    1273931.0  118.662300  45.402433  6.0  91.0  120.0  139.0  343.0
True     1537843.0  109.936148  57.164487  1.0  67.0  109.0  140.0  513.0

        word_count
             count       mean        std  min   25%   50%   75%    max
inbound
False    1273931.0  20.340073   8.123852  1.0  15.0  20.0  24.0   66.0
True     1537843.0  18.728028  10.644689  1.0  11.0  18.0  25.0  137.0

In [18]:
print("Customer tweets:")
print(
    df_twitter.loc[df_twitter["inbound"] == True, "text"]
    .str.len()
    .describe()
)

print("\nCompany tweets:")
print(
    df_twitter.loc[df_twitter["inbound"] == False, "text"]
    .str.len()
    .describe()
)

Customer tweets:
count    1.537843e+06
mean     1.099361e+02
std      5.716449e+01
min      1.000000e+00
25%      6.700000e+01
50%      1.090000e+02
75%      1.400000e+02
max      5.130000e+02
Name: text, dtype: float64

Company tweets:
count    1.273931e+06
mean     1.186623e+02
std      4.540243e+01
min      6.000000e+00
25%      9.100000e+01
50%      1.200000e+02
75%      1.390000e+02
max      3.430000e+02
Name: text, dtype: float64

In [19]:
from collections import Counter
import re

customer_text = (
    df_twitter.loc[df_twitter["inbound"] == True, "text"]
    .astype(str)
    .str.lower()
)

# Remove Twitter handles
customer_text_clean = customer_text.apply(
    lambda x: re.sub(r"@\w+", "", x)
)

# Extract 2-word and 3-word phrases
bigrams = Counter()
trigrams = Counter()

for text in customer_text_clean:
    words = re.findall(r"\b[a-zA-Z']+\b", text)

    bigrams.update(
        zip(words, words[1:])
    )

    trigrams.update(
        zip(words, words[1:], words[2:])
    )

print("Top customer bigrams:")
for phrase, count in bigrams.most_common(30):
    print(" ".join(phrase), "→", count)

print("\nTop customer trigrams:")
for phrase, count in trigrams.most_common(30):
    print(" ".join(phrase), "→", count)

Top customer bigrams:
t co → 220575
https t → 220493
i have → 78377
on the → 51549
in the → 46668
thank you → 46395
it s → 45003
i m → 44916
for the → 41911
to be → 37375
and i → 36148
to get → 34642
this is → 34468
i am → 34032
i can → 33651
for a → 31251
to the → 31205
on my → 30987
when i → 30905
of the → 30688
can you → 30300
i was → 29967
customer service → 28459
can t → 26676
my phone → 26559
it was → 26257
trying to → 26053
can i → 25553
don t → 25504
have to → 25058

Top customer trigrams:
https t co → 220493
how do i → 12065
i have to → 10695
i can t → 10517
i don t → 10034
thank you for → 9645
i need to → 9592
i have a → 9431
i want to → 7761
thanks for the → 7730
is there a → 7090
how can i → 6685
can you help → 6479
i i i → 5664
on the phone → 5632
be able to → 5495
i have been → 4991
can you please → 4957
this is the → 4884
it s not → 4883
can i get → 4628
this https t → 4564
i ve been → 4478
i m not → 4423
every time i → 4413
to get a → 4392
there is no → 4292
and it s → 4183
i try to → 4068
your customer service → 4059

In [20]:
customer_text_no_urls = (
    df_twitter.loc[df_twitter["inbound"] == True, "text"]
    .astype(str)
    .str.lower()
    .str.replace(r"https?://\S+|www\.\S+", " ", regex=True)
    .str.replace(r"@\w+", " ", regex=True)
)

print("Original customer tweets:", len(customer_text))
print("After URL/mention removal:", len(customer_text_no_urls))

print("\nTop customer bigrams after URL/mention removal:")

bigrams_clean = Counter()

for text in customer_text_no_urls:
    words = re.findall(r"\b[a-zA-Z']+\b", text)
    bigrams_clean.update(zip(words, words[1:]))

for phrase, count in bigrams_clean.most_common(40):
    print(" ".join(phrase), "→", count)

Original customer tweets: 1537843
After URL/mention removal: 1537843

Top customer bigrams after URL/mention removal:
i have → 78377
on the → 51557
in the → 46671
thank you → 46395
it s → 45003
i m → 44916
for the → 41911
to be → 37375
and i → 36150
to get → 34642
this is → 34468
i am → 34032
i can → 33651
for a → 31252
to the → 31210
on my → 30988
when i → 30905
of the → 30688
can you → 30300
i was → 29967
customer service → 28459
can t → 26676
my phone → 26559
it was → 26257
trying to → 26053
can i → 25553
don t → 25504
have to → 25058
is the → 25012
do i → 24802
have a → 24062
i need → 24054
you guys → 23553
need to → 23499
thanks for → 22400
i ve → 22334
i get → 21532
but i → 21453
want to → 21043
my account → 20947

In [21]:
import spacy

print("spaCy version:", spacy.__version__)

try:
    nlp = spacy.load("en_core_web_sm")
    print("English model: available")
except Exception as e:
    print("English model: not available")
    print(type(e).__name__, "-", e)

spaCy version: 3.8.14
English model: available

In [22]:
customer_sample = (
    df_twitter.loc[df_twitter["inbound"] == True, "text"]
    .astype(str)
    .head(10000)
    .tolist()
)

docs = list(
    nlp.pipe(
        customer_sample,
        batch_size=256
    )
)

print("Tweets analysed:", len(docs))

print("\nAverage tokens per tweet:")
print(
    round(
        sum(len(doc) for doc in docs) / len(docs),
        2
    )
)

print("\nAverage alphabetic tokens per tweet:")
print(
    round(
        sum(
            sum(token.is_alpha for token in doc)
            for doc in docs
        ) / len(docs),
        2
    )
)

print("\nTotal entities detected:")
print(
    sum(len(doc.ents) for doc in docs)
)

Tweets analysed: 10000

Average tokens per tweet:
20.33

Average alphabetic tokens per tweet:
15.19

Total entities detected:
12608

In [23]:
from collections import Counter

entity_counts = Counter()

for doc in docs:
    for ent in doc.ents:
        entity_counts[ent.label_] += 1

print("Entity type distribution:")
for label, count in entity_counts.most_common():
    print(f"{label:15} → {count}")

Entity type distribution:
ORG             → 3468
CARDINAL        → 1948
DATE            → 1945
PERSON          → 1917
GPE             → 1069
TIME            → 641
MONEY           → 615
ORDINAL         → 249
PRODUCT         → 187
NORP            → 179
EVENT           → 76
LOC             → 64
FAC             → 62
PERCENT         → 56
WORK_OF_ART     → 56
QUANTITY        → 45
LAW             → 16
LANGUAGE        → 15

In [24]:
entity_examples = {}

for doc in docs:
    for ent in doc.ents:
        entity_examples.setdefault(ent.label_, [])

        if len(entity_examples[ent.label_]) < 10:
            entity_examples[ent.label_].append(
                (ent.text, doc.text)
            )

for label in entity_counts.most_common():
    entity_type = label[0]

    print(f"\n{'=' * 60}")
    print(f"{entity_type} examples")
    print(f"{'=' * 60}")

    for entity_text, source_text in entity_examples.get(
        entity_type,
        []
    ):
        print(f"Entity: {entity_text}")
        print(f"Tweet:  {source_text}")
        print()

============================================================
ORG examples
============================================================
Entity: @sprintcare
Tweet:  @sprintcare is the worst customer service

Entity: @115714
Tweet:  @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Entity: @115714
Tweet:  @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Entity: OCS Account Takeover
Tweet:  @Ask_Spectrum The correct way to do it is via an OCS Account Takeover and email Consent Form it does not need to be done in a local office

Entity: INCORRECT
Tweet:  @Ask_Spectrum That is INCORRECT information I have the form in front of me that is faxed over-maybe you need to maintain up to date information

Entity: @115722 MD
Tweet:  @115722 MD. And this was sent to the wrong address https://t.co/dMQ1WZXJOk

Entity: https://t.co/dMQ1WZXJOk
Tweet:  @115722 MD. And this was sent to the wrong address https://t.co/dMQ1WZXJOk

Entity: CS
Tweet:  @115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give me an acct #!

Entity: ISP
Tweet:  @115722 is the worst ISP I’ve ever had

Entity: Diet
Tweet:  @ChipotleTweets no Diet Coke and a literal bone this Boorito was extra spooky! https://t.co/C4oCCtdUct


============================================================
CARDINAL examples
============================================================
Entity: 5
Tweet:  @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Entity: one
Tweet:  @Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?

Entity: @VerizonSupport
Tweet:  somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service

Entity: #
Tweet:  When you're the only one in costume #boorito @ChipotleTweets

Entity: at least 5p
Tweet:  @marksandspencer ou must charge at least 5p a bag (including VAT) for carrier bags that are all of the following:

unused - it’s new and hasn’t already been used for sold goods to be taken away or delivered
plastic and 70 microns thick or less
it has handles, an opening and isn’t sealed

Entity: 70
Tweet:  @marksandspencer ou must charge at least 5p a bag (including VAT) for carrier bags that are all of the following:

unused - it’s new and hasn’t already been used for sold goods to be taken away or delivered
plastic and 70 microns thick or less
it has handles, an opening and isn’t sealed

Entity: 4
Tweet:  @marksandspencer aren’t require charge 4 a bag:
paper bags
shops in airports, or on board trains, aeroplanes or ships
bags which only contain certain items, such as unwrapped food, raw meat and fish where there is a food safety risk, prescription medicines, uncovered blades, seeds, bulbs &amp; 🌷s

Entity: 2
Tweet:  @MicrosoftHelps I need assistance recovering 2 hotmail accounts. I have  filled the recovery forms but am told am not providing enough info

Entity: 500
Tweet:  @ATVIAssist @115754 umm someone is streaming WWII with 500+ viewers https://t.co/AhBT7AZZSz

Entity: 11
Tweet:  @115758 @ATVIAssist Are yous going to update COD Zombies on IOS for IOS 11.


============================================================
DATE examples
============================================================
Entity: day 1
Tweet:  @sprintcare Since I signed up with you....Since day 1

Entity: the 4 years
Tweet:  @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Entity: 60 days
Tweet:  @115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give me an acct #!

Entity: today
Tweet:  @ChipotleTweets messed up today and didn’t give me my $3 burrito although I was dressed up 😭

Entity: a week
Tweet:  hey @ChipotleTweets wanna come to Mammoth. I'll at least eat there once a week i promise

Entity: Halloween
Tweet:  Happy Halloween! Since I'm too old to trick or treat I now look forward to $3 booritos at @ChipotleTweets 👻 I got mine earlier, did you?

Entity: Saturday
Tweet:  So frustrated with @ChipotleTweets 😡 Ordered dinner on Saturday using their app. Order was wrong AND they charged my credit card twice

Entity: Halloween
Tweet:  Btw @ChipotleTweets giving out $3 burritos if you dress up for Halloween 🎃 Call your Chipotle to make sure, they’re doing it @ select ones

Entity: Every year
Tweet:  Every year, my trick-or-treating routine is walking to Chipotle, spending 3 dollars and walking back home. @ChipotleTweets

Entity: Halloween
Tweet:  Considering walking to @ChipotleTweets in my llama onesie alone happy Halloween 😭


============================================================
PERSON examples
============================================================
Entity: LTE
Tweet:  @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Entity: Spectrum
Tweet:  @Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?

Entity: 😩😩😩😩
Tweet:  somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service

Entity: @115722 Nobody
Tweet:  @115722 Nobody can find my account or number. I walked out of a store with this. I've explained that they can find my acct via my devices serial #..

Entity: @VerizonSupport Cuts
Tweet:  @VerizonSupport Cuts out every 20 minutes this is ridiculous

Entity: @115722
Tweet:  @115722 is the worst ISP I’ve ever had

Entity: Veggie Burrito
Tweet:  @ChipotleTweets @28
I don't fit in my Veggie Burrito costume #Halloween https://t.co/7tJDVpzLWn

Entity: Boorito
Tweet:  @ChipotleTweets no Diet Coke and a literal bone this Boorito was extra spooky! https://t.co/C4oCCtdUct

Entity: https://t.co/C4oCCtdUct
Tweet:  @ChipotleTweets no Diet Coke and a literal bone this Boorito was extra spooky! https://t.co/C4oCCtdUct

Entity: fanforlife
Tweet:  @ChipotleTweets Thank you @ChipotleTweets for resolving my issue so quickly!! Y’all are the best ☺️ #fanforlife


============================================================
GPE examples
============================================================
Entity: VERIZON
Tweet:  .@VerizonSupport @115725 @115726                                                 &gt;All of VERIZON IS DOWN&lt;
When can we expect a fix ?

Entity: Becky
Tweet:  @ChipotleTweets @ChipotleTweets Becky is very nice

Entity: Mammoth
Tweet:  hey @ChipotleTweets wanna come to Mammoth. I'll at least eat there once a week i promise

Entity: D.C.
Tweet:  @ChipotleTweets Thanks Becky! Just feeling sorry for myself because my fiancé is driving from D.C. To Mississippi tonight

Entity: Mississippi
Tweet:  @ChipotleTweets Thanks Becky! Just feeling sorry for myself because my fiancé is driving from D.C. To Mississippi tonight

Entity: @ATVIAssist
Tweet:  @ATVIAssist can you still pre oder ww2 on the playstation store

Entity: xp^
Tweet:  @ATVIAssist For double xp^

Entity: Carentan
Tweet:  @115754 @115765 @ATVIAssist @115766

Will non season pass holders get the bobus man Carentan at any point? Or not at all?

Entity: my5
Tweet:  @XboxSupport This is what's on my screen? Not sure if it's Xbox side or my5 side that's broken? Last time it was my5 as had to call head office about it! https://t.co/jnMIVOlNbS

Entity: Xboxes
Tweet:  @1520 @XboxSupport  the 5 app on Xboxes not working error code 200, done a power cycle and still the same? Please fix app


============================================================
TIME examples
============================================================
Entity: every 20 minutes
Tweet:  @VerizonSupport Cuts out every 20 minutes this is ridiculous

Entity: tonight
Tweet:  @ChipotleTweets I had excellent service tonight too! Plenty of people on the line, went very fast, everyone was kind!

Entity: tonight
Tweet:  @ChipotleTweets Thanks Becky! Just feeling sorry for myself because my fiancé is driving from D.C. To Mississippi tonight

Entity: a few hours
Tweet:  @AskPlayStation It was when I would go to download it. I just waited a few hours till after I bought it and it downloaded now.

Entity: 1 hour
Tweet:  @115769 whats going on with your app. its totally stuck here for 1 hour and prior to updating froze and didnt work since updating. https://t.co/UpoCzPNqFb

Entity: this afternoon
Tweet:  @115790 @XboxSupport redeemed a code for fifa points this afternoon and still haven't got it. Why is this?

Entity: a few hours
Tweet:  @115794 @115796 Nothing, partner was on a train to Preston had to get a Taxi rest of way as was told no trains into Preston for a few hours

Entity: 2pm tomorrow
Tweet:  @AskLyft I have to be at work at 2pm tomorrow. My new phone is being overnighted but it may not be there until then. I have no other ride.

Entity: minutes
Tweet:  @115846 @115821 Remember my head phones and they brought them within minutes

Entity: a last minute
Tweet:  My package from @115821 with my Halloween costume was “delivered” Friday but I don’t have I so searching everywhere for a last minute idea.


============================================================
MONEY examples
============================================================
Entity: 171
Tweet:  My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik

Entity: Halloween
Tweet:  @ChipotleTweets @28
I don't fit in my Veggie Burrito costume #Halloween https://t.co/7tJDVpzLWn

Entity: 3
Tweet:  @ChipotleTweets messed up today and didn’t give me my $3 burrito although I was dressed up 😭

Entity: 3
Tweet:  Happy Halloween! Since I'm too old to trick or treat I now look forward to $3 booritos at @ChipotleTweets 👻 I got mine earlier, did you?

Entity: 3
Tweet:  Btw @ChipotleTweets giving out $3 burritos if you dress up for Halloween 🎃 Call your Chipotle to make sure, they’re doing it @ select ones

Entity: 3 dollars
Tweet:  Every year, my trick-or-treating routine is walking to Chipotle, spending 3 dollars and walking back home. @ChipotleTweets

Entity: 3
Tweet:  $3 burritos and I’m nowhere near a @ChipotleTweets 🤦🏾‍♂️

Entity: 680$
Tweet:  @XboxSupport @115786 Kinda need to make sure I have 680$ cdn in my bank, so would be nice to know.. I dun just have cash laying around ya know #RealLifeStruggles

Entity: 3 for £
Tweet:  @Morrisons 3 for £6, unless one is reduced (hidden label on the side!) then it’s 3 for £6.14. Don’t care about the 14p but feel ripped off! https://t.co/jG0fTncMDr

Entity: 6
Tweet:  @Morrisons 3 for £6, unless one is reduced (hidden label on the side!) then it’s 3 for £6.14. Don’t care about the 14p but feel ripped off! https://t.co/jG0fTncMDr


============================================================
ORDINAL examples
============================================================
Entity: 2xp
Tweet:  @ATVIAssist So, when I go get the game on friday my 2xp code will be on the receipt?

Entity: first
Tweet:  @115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

Entity: 2nd
Tweet:  .@AmazonHelp Item has not been delivered but tracking says it was handed to me over an hour ago... 2nd time this has happened. Sort it out https://t.co/42W82GcARk

Entity: 3rd
Tweet:  @AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?

Entity: 18th
Tweet:  @AppleSupport I’ve got a screenshot saying my #iPhoneX is reserved for the 3rd then an email saying it’s the 18th... what happened?

Entity: first
Tweet:  @Delta I'm flying JFK-MEX-MID tomorrow and you say I'm booked in, but it looks like it's just the first leg. Can you check, please?

Entity: first
Tweet:  Hi @British_Airways! My flight from MAN--LHR--BWI for Nov. 3 was canceled. I was excited to try your Club 787 product. Only available flight is now to IAD which is a hassle, but rebooked anyway--my only option! Any availability in first class on BA293 for the troubles please?

Entity: first
Tweet:  @VirginTrains For at least the third time this year, I will miss the meeting I especially took the train for in the first place. So often late. No refund because it "doesn't qualify". Next season = car.

Entity: 22:45
Tweet:  @GWRHelp boarding the 22:45 from pad to swindon. Where in reading do I have to go for the bus?dont usually find staff to help!!!

Entity: first
Tweet:  @ChipotleTweets Woohoo! I'm gonna be first in line. 😄


============================================================
PRODUCT examples
============================================================
Entity: https://t.co/0G98RtNxPK
Tweet:  @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Entity: Coke
Tweet:  @ChipotleTweets no Diet Coke and a literal bone this Boorito was extra spooky! https://t.co/C4oCCtdUct

Entity: PlayStation
Tweet:  @AskPlayStation I bought Lego Star Wars in the PlayStation store but it won't let me download it because the data is corrupted..

Entity: @1520
Tweet:  @1520 @XboxSupport  the 5 app on Xboxes not working error code 200, done a power cycle and still the same? Please fix app

Entity: @115812
Tweet:  @115812 I cant Connect my Interactive Broker ( Canada) with yahoo finance App in ios 11, Any suggestions.. ??

Entity: Scorpio
Tweet:  @115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away

Entity: BWI
Tweet:  @British_Airways I assume that being Sapphire does not matter? I'll have to find a way from IAD to BWI upon landing... Because that's where my car is parked.

Entity: TiVo
Tweet:  @comcastcares Phoenix Suns are on auto record. NBA Team Channel 752 trying to record tonight. I only want regular broadcast games recorded like TiVo does.

Entity: App
Tweet:  @VirginTrains Thanks, see it now. Real shame about how poor the new App is though.

Entity: @115937 @AskeBay the
Tweet:  EVERYTIME i sell something on @115937 @AskeBay the bid comes back as fraudulent and i have to repost.  7 days wasted.  I’m done.  Ugh.


============================================================
NORP examples
============================================================
Entity: @115830
Tweet:  In response to your @115830 packing video, this packaging was for a 2ft washing line pole @115837 https://t.co/X21SQHgC0K

Entity: https://t.co/NV0yucs0lB
Tweet:  @AppleSupport  https://t.co/NV0yucs0lB

Entity: @116016
Tweet:  Hey @116016 we're gonna need to talk about all these pending charges that keep going through my account 5 days after the transaction was made.... I'm getting real irritated.

Entity: Japanese
Tweet:  This is the Japanese vampire book I blurbed. Different, touching, and perfectly constructed. https://t.co/lZAfyKtMpe

Entity: telefon
Tweet:  @AppleSupport epıl bana yardımcı olur musun telefon internet konusunda çok yakıyo napcaz ?

Entity: German
Tweet:  @AmazonHelp I'm learning German, so I don't really mind between German/English. If I have to choose, I say German.

Entity: German
Tweet:  @AmazonHelp I'm learning German, so I don't really mind between German/English. If I have to choose, I say German.

Entity: German
Tweet:  @AmazonHelp I'm learning German, so I don't really mind between German/English. If I have to choose, I say German.

Entity: German
Tweet:  @116316 Hi. How can I restrict results to German language books, while searching titles on amazon.de?

Entity: Dutch
Tweet:  Dear @115888 how do i get my discovery playlist to stop suggesting Dutch music to me, it's been a year


============================================================
EVENT examples
============================================================
Entity: WWII
Tweet:  @ATVIAssist @115754 umm someone is streaming WWII with 500+ viewers https://t.co/AhBT7AZZSz

Entity: New #ButtermilkCrispyTenders https://t.co/4sy9hatKTi
Tweet:  My grandma's laying #Poolside thanks to @McDonalds delicious New #ButtermilkCrispyTenders https://t.co/4sy9hatKTi

Entity: Hurricane Irma
Tweet:  @115900 My house was destroyed by Hurricane Irma, I've called you THREE times to place temporary hold, and you STILL send me a bill

Entity: WWII
Tweet:  @116226 @ATVIAssist Can I use my 3 of a kind on WWII? 🤔😂 plz

Entity: @AppleSupport watchOs4
Tweet:  @AppleSupport watchOs4 made my watch pointless Browsing music on my phone via the watch was 80% reason for buying it now it’s useless.

Entity: @AppleSupport See
Tweet:  @AppleSupport See how it says searching at the top instead of giving me signal?.....I’ve been dealing with that for 2 weeks and sprint did everything https://t.co/iB0NsSeL1G

Entity: 😜 @ChipotleTweets
Tweet:  Come through to chipotle and get your $3 bowl today 😜 @ChipotleTweets https://t.co/aOAeKJ2rZp

Entity: @115830
Tweet:  just noticed I paid £4.95 delivery on Amazon simply because I did not select the FREE delivery option, after I spent enough to qualify... what a RIP OFF, why is it not free automatically when qualifying @115830

Entity: @AppleSupport
Tweet:  Listen I’m having issues with my phone so like can you @ me so we can talk @AppleSupport

Entity: WWII
Tweet:  @115765 @ATVIAssist @115766 having issues with my game WWII, from missing attachments for guns, blank lobby screens. Are any of the disc defected. Bought mine from tesco £36 https://t.co/dRjAlXTgCx


============================================================
LOC examples
============================================================
Entity: the Echo Show
Tweet:  @AmazonHelp Nothing there helped me with the Echo Show

Entity: hai yaar @Uber_Support
Tweet:  kya khassi support hai yaar @Uber_Support. i am an uber rider not driver. they are telling me to take docs to nearby uber office for verification and all i was asked was to update my cellphone number 👺👺

Entity: Four Seasons
Tweet:  How did I not get a ride out of this surge!? I’m at the Four Seasons resort and there is only one car around me and it’s farther away. Thanks @115873. #scrubered. https://t.co/qdicFjZlXB

Entity: Southwest
Tweet:  @SouthwestAir I'd have to fly your airline again to do that, so no. Not after you screwed me over last time. Never flying Southwest again. #neverflywn

Entity: Delta
Tweet:  @Delta I went to the service center &amp; spoke to a sup. Wouldn’t refund my $75 OR deliver bags. She couldn’t show me in writing nor was I told I was ‘voluntarily’ separating from my bag. 🙄 Said it would cost Delta to deliver my bag. Apparently 60+ flights a year means nothing.

Entity: Whitechapel
Tweet:  @sainsburys It’s a multi pack so I don’t have the barcode I’m afraid, it was Whitechapel in London

Entity: NYC
Tweet:  Hey @AmericanAir! Rocky here on flight AA2254. We were supposed to depart at 6:07PM but it is now 6:54PM and the crew just informed us that our captain is missing. Oh and not to mention we also had a maintenance issue. Hope to make it to NYC safe and sound. #disappointed

Entity: the north east
Tweet:  @VerizonSupport Same reports on @116655 from other FiOS users around the north east.  Is this something Verizon is investigating or could join in on?  Been over 4 hours of outage for some. https://t.co/2Ecdop6zl1

Entity: Verizon
Tweet:  @VerizonSupport Same reports on @116655 from other FiOS users around the north east.  Is this something Verizon is investigating or could join in on?  Been over 4 hours of outage for some. https://t.co/2Ecdop6zl1

Entity: Verizon
Tweet:  @VerizonSupport @115725 ... when your “gigabit” internet is so slow that the Verizon speed test fails repeatedly... https://t.co/qsg0ov6rXp


============================================================
FAC examples

In [25]:
import transformers

print("Transformers version:", transformers.__version__)

c:\Users\danie\anaconda3\envs\supportmind\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Transformers version: 5.13.0

In [26]:
from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

sentiment_sample = (
    df_twitter.loc[
        df_twitter["inbound"] == True,
        "text"
    ]
    .astype(str)
    .head(1000)
    .tolist()
)

sentiment_results = sentiment_pipeline(
    sentiment_sample,
    batch_size=32,
    truncation=True
)

print("Tweets analysed:", len(sentiment_results))

from collections import Counter

sentiment_counts = Counter(
    result["label"]
    for result in sentiment_results
)

print("\nSentiment distribution:")
for label, count in sentiment_counts.items():
    print(
        f"{label}: {count} "
        f"({count / len(sentiment_results) * 100:.2f}%)"
    )

print("\nConfidence statistics:")

import numpy as np

scores = np.array(
    [result["score"] for result in sentiment_results]
)

print("Mean:", round(scores.mean(), 4))
print("Median:", round(np.median(scores), 4))
print("Minimum:", round(scores.min(), 4))

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 1862.38it/s]

Tweets analysed: 1000

Sentiment distribution:
POSITIVE: 207 (20.70%)
NEGATIVE: 793 (79.30%)

Confidence statistics:
Mean: 0.9723
Median: 0.9973
Minimum: 0.5014

In [27]:
sentiment_analysis = df_twitter.loc[
    df_twitter["inbound"] == True,
    ["tweet_id", "text", "response_tweet_id"]
].head(1000).copy()

sentiment_analysis["sentiment"] = [
    result["label"]
    for result in sentiment_results
]

sentiment_analysis["sentiment_score"] = [
    result["score"]
    for result in sentiment_results
]

sentiment_analysis["response_count"] = (
    sentiment_analysis["response_tweet_id"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: len(
            [item for item in x.split(",") if item.strip()]
        ) if x.strip() else 0
    )
)

print(
    sentiment_analysis
    .groupby("sentiment")["response_count"]
    .describe()
)

           count      mean       std  min  25%  50%  75%   max
sentiment
NEGATIVE   793.0  1.185372  3.087068  0.0  1.0  1.0  1.0  84.0
POSITIVE   207.0  1.483092  4.587706  0.0  1.0  1.0  1.0  52.0

In [28]:
print("Average response count by sentiment:")
print(
    sentiment_analysis
    .groupby("sentiment")["response_count"]
    .mean()
)

print("\nTweets with at least one response:")
print(
    sentiment_analysis
    .assign(
        has_response=
        sentiment_analysis["response_count"] > 0
    )
    .groupby("sentiment")["has_response"]
    .mean()
    .mul(100)
    .round(2)
)

Average response count by sentiment:
sentiment
NEGATIVE    1.185372
POSITIVE    1.483092
Name: response_count, dtype: float64

Tweets with at least one response:
sentiment
NEGATIVE    87.89
POSITIVE    83.57
Name: has_response, dtype: float64

In [29]:
customer_response_counts = (
    df_twitter.loc[
        df_twitter["inbound"] == True,
        "response_tweet_id"
    ]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: len(
            [item for item in x.split(",") if item.strip()]
        ) if x.strip() else 0
    )
)

print("Customer tweets:", len(customer_response_counts))

print("\nResponse buckets:")

response_buckets = pd.cut(
    customer_response_counts,
    bins=[-1, 0, 1, 2, 3, 5, 10, 20, 50, 100, float("inf")],
    labels=[
        "0",
        "1",
        "2",
        "3",
        "4-5",
        "6-10",
        "11-20",
        "21-50",
        "51-100",
        "101+"
    ]
)

print(
    response_buckets
    .value_counts()
    .sort_index()
)

print("\nPercentages:")
print(
    (
        response_buckets
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
        .round(2)
    )
)

Customer tweets: 1537843

Response buckets:
response_tweet_id
0          234014
1         1141874
2          128090
3           22424
4-5          8090
6-10         2132
11-20         680
21-50         375
51-100         98
101+           66
Name: count, dtype: int64

Percentages:
response_tweet_id
0         15.22
1         74.25
2          8.33
3          1.46
4-5        0.53
6-10       0.14
11-20      0.04
21-50      0.02
51-100     0.01
101+       0.00
Name: proportion, dtype: float64

In [30]:
from collections import Counter

term_counts = Counter()

for doc in docs:
    for token in doc:
        if (
            token.is_alpha
            and not token.is_stop
            and len(token.lemma_) >= 3
        ):
            term_counts[token.lemma_.lower()] += 1

print("Top meaningful customer terms:")

for term, count in term_counts.most_common(100):
    print(f"{term:25} → {count}")

Top meaningful customer terms:
thank                     → 864
service                   → 596
get                       → 589
time                      → 539
help                      → 533
customer                  → 455
work                      → 451
order                     → 445
day                       → 432
try                       → 420
need                      → 397
phone                     → 367
amp                       → 356
say                       → 348
flight                    → 339
account                   → 318
want                      → 317
like                      → 313
know                      → 298
app                       → 296
send                      → 292
update                    → 291
email                     → 288
issue                     → 281
pay                       → 275
today                     → 268
tell                      → 267
new                       → 257
fix                       → 240
check                     → 229
guy                       → 227
wait                      → 223
amazon                    → 223
good                      → 220
hour                      → 217
internet                  → 216
charge                    → 214
change                    → 212
come                      → 212
problem                   → 207
receive                   → 205
halloween                 → 194
driver                    → 191
number                    → 190
bad                       → 189
delivery                  → 185
hey                       → 182
look                      → 177
call                      → 177
month                     → 176
find                      → 176
ask                       → 172
way                       → 169
happen                    → 169
buy                       → 167
yes                       → 163
refund                    → 163
people                    → 161
use                       → 161
give                      → 159
reply                     → 159
deliver                   → 158
week                      → 156
game                      → 153
think                     → 152
store                     → 149
let                       → 148
iphone                    → 148
cancel                    → 147
long                      → 142
will                      → 140
card                      → 140
contact                   → 139
great                     → 134
not                       → 134
have                      → 133
year                      → 132
take                      → 132
thing                     → 130
package                   → 130
leave                     → 129
money                     → 128
late                      → 128
minute                    → 127
stop                      → 127
train                     → 126
message                   → 125
home                      → 119
right                     → 119
play                      → 117
prime                     → 116
support                   → 113
code                      → 112
watch                     → 112
wrong                     → 111
ios                       → 111
book                      → 111
able                      → 111
free                      → 110
return                    → 110

In [31]:
import pandas as pd
import numpy as np

# Load Twitter dataset
twitter_path = r"C:\Users\danie\supportmind-ai\rawsupportminddata\Customer Support on Twitter\twcs\twcs.csv"

df = pd.read_csv(
    twitter_path,
    dtype={
        "tweet_id": "int64",
        "author_id": "string",
        "inbound": "boolean",
        "response_tweet_id": "string",
        "in_response_to_tweet_id": "string",
    }
)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (2811774, 7)

Columns:
['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [32]:
# Tweets with no parent are conversation roots
root_mask = df["in_response_to_tweet_id"].isna()

roots = df.loc[
    root_mask,
    [
        "tweet_id",
        "author_id",
        "inbound",
        "created_at",
        "text",
        "response_tweet_id",
    ]
].copy()

print("Root conversations:", len(roots))

print("\nRoot inbound distribution:")
print(roots["inbound"].value_counts(dropna=False))

print("\nCustomer roots:")
print((roots["inbound"] == True).sum())

print("Company roots:")
print((roots["inbound"] == False).sum())

Root conversations: 794335

Root inbound distribution:
inbound
True     787346
False      6989
Name: count, dtype: Int64

Customer roots:
787346
Company roots:
6989

In [33]:
customer_roots = roots[
    roots["inbound"] == True
].copy()

print("Customer-started conversations:", len(customer_roots))

customer_roots.head()

Customer-started conversations: 787346

,tweet_id,author_id,inbound,created_at,text,response_tweet_id
6,8,115712,True,Tue Oct 31 21:45:10 +0000 2017,@sprintcare is the worst customer service,"9,6,10"
12,18,115713,True,Tue Oct 31 19:56:01 +0000 2017,@115714 y’all lie about your “great” connectio...,17
14,20,115715,True,Tue Oct 31 22:03:34 +0000 2017,"@115714 whenever I contact customer support, t...",19
23,29,115716,True,Tue Oct 31 22:01:35 +0000 2017,actually that's a broken link you sent me and ...,28
25,31,115717,True,Tue Oct 31 22:06:54 +0000 2017,"Yo @Ask_Spectrum, your customer service reps a...",30

In [34]:
from collections import defaultdict

children = defaultdict(list)

for row in df[
    ["tweet_id", "in_response_to_tweet_id"]
].itertuples(index=False):

    tweet_id = row.tweet_id
    parent_id = row.in_response_to_tweet_id

    if pd.notna(parent_id):
        children[int(parent_id)].append(int(tweet_id))

print("Tweets with child relationships:", len(children))

Tweets with child relationships: 1774822

In [35]:
# Number of direct child replies for each tweet
root_direct_children = customer_roots["tweet_id"].map(
    lambda tweet_id: len(children.get(int(tweet_id), []))
)

print("Customer root direct-response statistics:")
print(root_direct_children.describe())

print("\nDirect responses per customer root:")
print(root_direct_children.value_counts().sort_index().head(20))

print("\nCustomer roots with:")
print("0 direct responses :", (root_direct_children == 0).sum())
print("1 direct response  :", (root_direct_children == 1).sum())
print("2+ direct responses:", (root_direct_children >= 2).sum())

Customer root direct-response statistics:
count    787346.000000
mean          1.111699
std           0.811679
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         297.000000
Name: tweet_id, dtype: float64

Direct responses per customer root:
tweet_id
1     722105
2      53858
3       7928
4       2225
5        528
6        204
7         84
8         65
9         62
10        29
11        31
12        31
13        19
14        23
15         8
16        12
17         6
18        10
19         7
20         4
Name: count, dtype: int64

Customer roots with:
0 direct responses : 0
1 direct response  : 722105
2+ direct responses: 65241

In [36]:
# Inspect a few customer-started conversations
sample_root_ids = customer_roots["tweet_id"].head(10).tolist()

for root_id in sample_root_ids:
    root_row = df.loc[df["tweet_id"] == root_id].iloc[0]

    print("\n" + "=" * 100)
    print("ROOT")
    print("Tweet ID :", root_id)
    print("Inbound  :", root_row["inbound"])
    print("Text     :", root_row["text"])

    child_ids = children.get(int(root_id), [])

    print("\nDirect replies:", len(child_ids))

    for child_id in child_ids[:10]:
        child_row = df.loc[df["tweet_id"] == child_id].iloc[0]

        print(
            f"  → {child_id} | "
            f"inbound={child_row['inbound']} | "
            f"{child_row['text']}"
        )

====================================================================================================
ROOT
Tweet ID : 8
Inbound  : True
Text     : @sprintcare is the worst customer service

Direct replies: 3
  → 6 | inbound=False | @115712 Can you please send us a private message, so that I can gain further details about your account?
  → 9 | inbound=False | @115712 I would love the chance to review the account and provide assistance.
  → 10 | inbound=False | @115712 Hello! We never like our customers to feel like they are not valued.

====================================================================================================
ROOT
Tweet ID : 18
Inbound  : True
Text     : @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Direct replies: 1
  → 17 | inbound=False | @115713 H there! We'd definitely like to work with you on this, how long have you been experiencing this issue? -AA

====================================================================================================
ROOT
Tweet ID : 20
Inbound  : True
Text     : @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Direct replies: 1
  → 19 | inbound=False | @115715 Please send me a private message so that I can send you the link to access your account. -FR

====================================================================================================
ROOT
Tweet ID : 29
Inbound  : True
Text     : actually that's a broken link you sent me and incorrect information https://t.co/V4yfrHR8VI

Direct replies: 1
  → 28 | inbound=False | @115716 The information pertaining to the account assumption is correct.  This does need to be done at a local outlet wit... https://t.co/P7XCmTzPQj

====================================================================================================
ROOT
Tweet ID : 31
Inbound  : True
Text     : Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service going!

Direct replies: 1
  → 30 | inbound=False | @115717 Hello, My apologies for any frustrations or inconvenience. I’d be happy to look into this for you? ^MG

====================================================================================================
ROOT
Tweet ID : 33
Inbound  : True
Text     : My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik

Direct replies: 1
  → 32 | inbound=False | @115718 I apologize for the inconvenience. I will be glad to assist you. Can you DM me your Name and acct # or phone #? -JB

====================================================================================================
ROOT
Tweet ID : 36
Inbound  : True
Text     : somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service

Direct replies: 1
  → 34 | inbound=False | @115719 Help has arrived! We are sorry to see that you are having trouble. How can we help?
^HSB

====================================================================================================
ROOT
Tweet ID : 39
Inbound  : True
Text     : @VerizonSupport My friend is without internet we need to play videogames together please our skills diminish every moment without internetz

Direct replies: 1
  → 38 | inbound=False | @115720 Have your friend message us.
^ACM

====================================================================================================
ROOT
Tweet ID : 49
Inbound  : True
Text     : @115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give me an acct #!

Direct replies: 1
  → 48 | inbound=True | @115721 Are you referring to wireless or residential service?
^JAY

====================================================================================================
ROOT
Tweet ID : 59
Inbound  : True
Text     : @115722 is the worst ISP I’ve ever had

Direct replies: 1
  → 58 | inbound=False | @115723 What did we do to make you feel this way and how can we fix things between us? ^KMG

In [37]:
def inspect_conversation(root_id, max_nodes=20):
    """
    Display the conversation chain starting from a customer root.
    """

    print("\n" + "=" * 110)
    print("CONVERSATION ROOT:", root_id)

    root_row = df.loc[df["tweet_id"] == root_id].iloc[0]

    print(
        f"[ROOT] tweet_id={root_id} | "
        f"inbound={root_row['inbound']} | "
        f"{root_row['text']}"
    )

    queue = [(int(root_id), 0)]
    visited = set()

    nodes_shown = 0

    while queue and nodes_shown < max_nodes:

        tweet_id, depth = queue.pop(0)

        if tweet_id in visited:
            continue

        visited.add(tweet_id)

        row = df.loc[df["tweet_id"] == tweet_id].iloc[0]

        print(
            f"[depth={depth}] "
            f"tweet_id={tweet_id} | "
            f"inbound={row['inbound']} | "
            f"{row['text']}"
        )

        nodes_shown += 1

        child_ids = children.get(tweet_id, [])

        for child_id in child_ids:
            queue.append((int(child_id), depth + 1))


# Inspect several customer-started conversations
for root_id in customer_roots["tweet_id"].head(10):
    inspect_conversation(int(root_id), max_nodes=20)

==============================================================================================================
CONVERSATION ROOT: 8
[ROOT] tweet_id=8 | inbound=True | @sprintcare is the worst customer service
[depth=0] tweet_id=8 | inbound=True | @sprintcare is the worst customer service
[depth=1] tweet_id=6 | inbound=False | @115712 Can you please send us a private message, so that I can gain further details about your account?
[depth=1] tweet_id=9 | inbound=False | @115712 I would love the chance to review the account and provide assistance.
[depth=1] tweet_id=10 | inbound=False | @115712 Hello! We never like our customers to feel like they are not valued.
[depth=2] tweet_id=5 | inbound=True | @sprintcare I did.
[depth=2] tweet_id=7 | inbound=True | @sprintcare the only way I can get a response is to tweet apparently
[depth=3] tweet_id=4 | inbound=False | @115712 Please send us a Private Message so that we can further assist you. Just click ‘Message’ at the top of your profile.
[depth=4] tweet_id=3 | inbound=True | @sprintcare I have sent several private messages and no one is responding as usual
[depth=5] tweet_id=1 | inbound=False | @115712 I understand. I would like to assist you. We would need to get you into a private secured link to further assist.
[depth=6] tweet_id=2 | inbound=True | @sprintcare and how do you propose we do that

==============================================================================================================
CONVERSATION ROOT: 18
[ROOT] tweet_id=18 | inbound=True | @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.
[depth=0] tweet_id=18 | inbound=True | @115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.
[depth=1] tweet_id=17 | inbound=False | @115713 H there! We'd definitely like to work with you on this, how long have you been experiencing this issue? -AA
[depth=2] tweet_id=16 | inbound=True | @sprintcare Since I signed up with you....Since day 1
[depth=3] tweet_id=15 | inbound=False | @115713 We understand your concerns and we'd like for you to please send us a Direct Message, so that we can further assist you. -AA
[depth=4] tweet_id=12 | inbound=True | @sprintcare You gonna magically change your connectivity for me and my whole family ? 🤥 💯
[depth=5] tweet_id=11 | inbound=False | @115713 This is saddening to hear. Please shoot us a DM, so that we can look into this for you. -KC
[depth=5] tweet_id=13 | inbound=False | @115713 I would really like to work with you to have this resolved. Kindly send us a DM. I'm here for you! -ResolutionSup SR
[depth=5] tweet_id=14 | inbound=False | @115713 Hi, my name is Shantel, I'm a resolution supervisor here with Sprint. Your issues was brought to my attention.  1/2 -ResolutionSup SR

==============================================================================================================
CONVERSATION ROOT: 20
[ROOT] tweet_id=20 | inbound=True | @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK
[depth=0] tweet_id=20 | inbound=True | @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK
[depth=1] tweet_id=19 | inbound=False | @115715 Please send me a private message so that I can send you the link to access your account. -FR

==============================================================================================================
CONVERSATION ROOT: 29
[ROOT] tweet_id=29 | inbound=True | actually that's a broken link you sent me and incorrect information https://t.co/V4yfrHR8VI
[depth=0] tweet_id=29 | inbound=True | actually that's a broken link you sent me and incorrect information https://t.co/V4yfrHR8VI
[depth=1] tweet_id=28 | inbound=False | @115716 The information pertaining to the account assumption is correct.  This does need to be done at a local outlet wit... https://t.co/P7XCmTzPQj
[depth=2] tweet_id=24 | inbound=True | @Ask_Spectrum That is INCORRECT information I have the form in front of me that is faxed over-maybe you need to maintain up to date information
[depth=3] tweet_id=21 | inbound=False | @115716 What information is incorrect? ^JK
[depth=4] tweet_id=22 | inbound=True | @Ask_Spectrum Would you like me to email you a copy of one since Spectrum is not updating your training?
[depth=4] tweet_id=23 | inbound=True | @Ask_Spectrum The correct way to do it is via an OCS Account Takeover and email Consent Form it does not need to be done in a local office
[depth=5] tweet_id=25 | inbound=False | @115716 Our department is part of the corporate office.  If you're particular area has gone to this format, we were unawa... https://t.co/P7XCmTzPQj
[depth=6] tweet_id=26 | inbound=True | @Ask_Spectrum I received this from your corporate office would you like a copy?
[depth=7] tweet_id=27 | inbound=False | @115716 No thank you. ^JK

==============================================================================================================
CONVERSATION ROOT: 31
[ROOT] tweet_id=31 | inbound=True | Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service going!
[depth=0] tweet_id=31 | inbound=True | Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service going!
[depth=1] tweet_id=30 | inbound=False | @115717 Hello, My apologies for any frustrations or inconvenience. I’d be happy to look into this for you? ^MG

==============================================================================================================
CONVERSATION ROOT: 33
[ROOT] tweet_id=33 | inbound=True | My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik
[depth=0] tweet_id=33 | inbound=True | My picture on @Ask_Spectrum pretty much every day. Why should I pay $171 per month? https://t.co/U6ptkQa5Ik
[depth=1] tweet_id=32 | inbound=False | @115718 I apologize for the inconvenience. I will be glad to assist you. Can you DM me your Name and acct # or phone #? -JB

==============================================================================================================
CONVERSATION ROOT: 36
[ROOT] tweet_id=36 | inbound=True | somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service
[depth=0] tweet_id=36 | inbound=True | somebody from @VerizonSupport please help meeeeee 😩😩😩😩 I'm having the worst luck with your customer service
[depth=1] tweet_id=34 | inbound=False | @115719 Help has arrived! We are sorry to see that you are having trouble. How can we help?
^HSB
[depth=2] tweet_id=35 | inbound=True | @VerizonSupport I finally got someone that helped me, thanks!
[depth=3] tweet_id=37 | inbound=False | @115719 Awesome! If you ever need us we are just a tweet away.
^HSB

==============================================================================================================
CONVERSATION ROOT: 39
[ROOT] tweet_id=39 | inbound=True | @VerizonSupport My friend is without internet we need to play videogames together please our skills diminish every moment without internetz
[depth=0] tweet_id=39 | inbound=True | @VerizonSupport My friend is without internet we need to play videogames together please our skills diminish every moment without internetz
[depth=1] tweet_id=38 | inbound=False | @115720 Have your friend message us.
^ACM

==============================================================================================================
CONVERSATION ROOT: 49
[ROOT] tweet_id=49 | inbound=True | @115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give me an acct #!
[depth=0] tweet_id=49 | inbound=True | @115722 tried to pay a bill for 60 days. No service, rude CS, and several transfers. Look up my equipment # and give me an acct #!
[depth=1] tweet_id=48 | inbound=True | @115721 Are you referring to wireless or residential service?
^JAY
[depth=2] tweet_id=47 | inbound=True | @115722 Nobody can find my account or number. I walked out of a store with this. I've explained that they can find my acct via my devices serial #..
[depth=3] tweet_id=46 | inbound=True | @115721 Hello Duke, Do you have a copy of your bill? What state are your services located in?
^NHP
[depth=4] tweet_id=42 | inbound=True | @115722 MD. And this was sent to the wrong address https://t.co/dMQ1WZXJOk
[depth=5] tweet_id=40 | inbound=False | @115721 Please follow and DM us so that we can look into this order.
^HSB
[depth=6] tweet_id=41 | inbound=True | @VerizonSupport What else can I provide? They refuse to help me because they cannot validate the account...
[depth=7] tweet_id=43 | inbound=False | @115721 We would not be able to verify anything without authenticating your account.
^JAY
[depth=8] tweet_id=44 | inbound=True | @VerizonSupport How? I have my phone number and email, that's it. How did I get equipment and service? I'm literally trying to pay and nobody can find me?
[depth=9] tweet_id=45 | inbound=False | @115721 We can use the order number to locate the account but will need to do so in our secure one on one chat. Please follow and DM us.
^HSB

==============================================================================================================
CONVERSATION ROOT: 59
[ROOT] tweet_id=59 | inbound=True | @115722 is the worst ISP I’ve ever had
[depth=0] tweet_id=59 | inbound=True | @115722 is the worst ISP I’ve ever had
[depth=1] tweet_id=58 | inbound=False | @115723 What did we do to make you feel this way and how can we fix things between us? ^KMG
[depth=2] tweet_id=57 | inbound=True | @VerizonSupport Cuts out every 20 minutes this is ridiculous
[depth=3] tweet_id=56 | inbound=False | @115723 Are all your services cutting out?
^ACM
[depth=4] tweet_id=55 | inbound=True | @VerizonSupport Yep
[depth=5] tweet_id=54 | inbound=False | @115723 Do you have our Fios service?  When services go out, does the internet light on the router change color? ^BCW
[depth=6] tweet_id=53 | inbound=True | @VerizonSupport Just randomly boots me offline there it goes again
[depth=7] tweet_id=52 | inbound=False | @115723 Did the lights change on the router when this happened?
^JAY
[depth=8] tweet_id=51 | inbound=True | @VerizonSupport Don’t know, router is downstairs. But it’s just the WiFi Nothing connected to Ethernet
[depth=9] tweet_id=50 | inbound=False | @115723 Is the light on top red?
^JAY

In [38]:
def get_conversation_stats(root_id, max_depth=100):
    """
    Traverse the conversation graph and collect structural statistics.
    """

    queue = [(int(root_id), 0)]
    visited = set()

    total_nodes = 0
    customer_nodes = 0
    company_nodes = 0
    max_depth_found = 0

    while queue:

        tweet_id, depth = queue.pop(0)

        if tweet_id in visited:
            continue

        visited.add(tweet_id)

        row = df.loc[df["tweet_id"] == tweet_id].iloc[0]

        total_nodes += 1
        max_depth_found = max(max_depth_found, depth)

        if bool(row["inbound"]):
            customer_nodes += 1
        else:
            company_nodes += 1

        if depth >= max_depth:
            continue

        for child_id in children.get(tweet_id, []):
            queue.append((int(child_id), depth + 1))

    return {
        "root_id": int(root_id),
        "total_nodes": total_nodes,
        "customer_nodes": customer_nodes,
        "company_nodes": company_nodes,
        "max_depth": max_depth_found,
    }

In [39]:
sample_roots = customer_roots["tweet_id"].head(10000)

conversation_stats = [
    get_conversation_stats(root_id)
    for root_id in sample_roots
]

conversation_stats_df = pd.DataFrame(conversation_stats)

conversation_stats_df.head()

   root_id  total_nodes  customer_nodes  company_nodes  max_depth
0        8           10               5              5          6
1       18            8               3              5          5
2       20            2               1              1          1
3       29            9               5              4          7
4       31            2               1              1          1

In [40]:
print("Conversation statistics:")
print(
    conversation_stats_df[
        [
            "total_nodes",
            "customer_nodes",
            "company_nodes",
            "max_depth",
        ]
    ].describe()
)

Conversation statistics:
        total_nodes  customer_nodes  company_nodes     max_depth
count  10000.000000    10000.000000   10000.000000  10000.000000
mean       4.748900        2.606800       2.142100      2.578700
std       15.137594        9.306699       6.111779      2.900043
min        2.000000        1.000000       1.000000      1.000000
25%        2.000000        1.000000       1.000000      1.000000
50%        3.000000        1.000000       1.000000      1.000000
75%        5.000000        2.000000       2.000000      3.000000
max      974.000000      569.000000     405.000000    100.000000

In [41]:
print("\nCustomer messages per conversation:")
print(
    conversation_stats_df["customer_nodes"]
    .value_counts()
    .sort_index()
    .head(20)
)

print("\nConversation depth:")
print(
    conversation_stats_df["max_depth"]
    .value_counts()
    .sort_index()
    .head(30)
)

Customer messages per conversation:
customer_nodes
1     5128
2     2415
3     1016
4      519
5      291
6      170
7      126
8       61
9       53
10      38
11      29
12      24
13      17
14      15
15       9
16       8
17       8
18       5
19       3
20       4
Name: count, dtype: int64

Conversation depth:
max_depth
1     5118
2     1226
3     1702
4      485
5      570
6      203
7      234
8      109
9      104
10      44
11      61
12      31
13      18
14      15
15      16
16       6
17      12
18       7
19       7
20       4
21       1
22       4
23       4
24       2
25       1
26       2
27       2
28       1
29       2
30       2
Name: count, dtype: int64

In [42]:
# Conversation complexity target
#
# Simple interaction:
#   maximum conversation depth <= 1
#
# Multi-turn interaction:
#   conversation reaches depth >= 2
#
# The root customer message is depth 0.
# A company reply is depth 1.
# A subsequent message is depth 2.

conversation_stats_df["multi_turn"] = (
    conversation_stats_df["max_depth"] >= 2
)

print("Target distribution:")
print(
    conversation_stats_df["multi_turn"]
    .value_counts()
    .sort_index()
)

print("\nTarget percentages:")
print(
    conversation_stats_df["multi_turn"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\nTarget labels:")
print("0 = Simple interaction")
print("1 = Multi-turn interaction")

Target distribution:
multi_turn
False    5118
True     4882
Name: count, dtype: int64

Target percentages:
multi_turn
False    51.18
True     48.82
Name: proportion, dtype: float64

Target labels:
0 = Simple interaction
1 = Multi-turn interaction

In [43]:
simple_examples = conversation_stats_df[
    conversation_stats_df["multi_turn"] == False
].sort_values(
    ["max_depth", "total_nodes"]
).head(5)

multi_examples = conversation_stats_df[
    conversation_stats_df["multi_turn"] == True
].sort_values(
    ["max_depth", "total_nodes"]
).head(5)

print("SIMPLE INTERACTION EXAMPLES")
print(
    simple_examples[
        [
            "root_id",
            "total_nodes",
            "customer_nodes",
            "company_nodes",
            "max_depth",
            "multi_turn",
        ]
    ].to_string(index=False)
)

print("\n" + "=" * 100)

print("MULTI-TURN INTERACTION EXAMPLES")
print(
    multi_examples[
        [
            "root_id",
            "total_nodes",
            "customer_nodes",
            "company_nodes",
            "max_depth",
            "multi_turn",
        ]
    ].to_string(index=False)
)

SIMPLE INTERACTION EXAMPLES
 root_id  total_nodes  customer_nodes  company_nodes  max_depth  multi_turn
      20            2               1              1          1       False
      31            2               1              1          1       False
      33            2               1              1          1       False
      39            2               1              1          1       False
      61            2               1              1          1       False

====================================================================================================
MULTI-TURN INTERACTION EXAMPLES
 root_id  total_nodes  customer_nodes  company_nodes  max_depth  multi_turn
     180            3               2              1          2        True
     237            3               2              1          2        True
     293            3               2              1          2        True
     323            3               2              1          2        True
     608            3               2              1          2        True

In [44]:
simple_root = int(simple_examples.iloc[0]["root_id"])
multi_root = int(multi_examples.iloc[0]["root_id"])

print("\n" + "=" * 100)
print("SIMPLE EXAMPLE")
inspect_conversation(simple_root, max_nodes=15)

print("\n" + "=" * 100)
print("MULTI-TURN EXAMPLE")
inspect_conversation(multi_root, max_nodes=15)

====================================================================================================
SIMPLE EXAMPLE

==============================================================================================================
CONVERSATION ROOT: 20

[ROOT] tweet_id=20 | inbound=True | @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK
[depth=0] tweet_id=20 | inbound=True | @115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK
[depth=1] tweet_id=19 | inbound=False | @115715 Please send me a private message so that I can send you the link to access your account. -FR

====================================================================================================
MULTI-TURN EXAMPLE

==============================================================================================================
CONVERSATION ROOT: 180
[ROOT] tweet_id=180 | inbound=True | @AskPlayStation So, what's the november ps plus free game?
[depth=0] tweet_id=180 | inbound=True | @AskPlayStation So, what's the november ps plus free game?
[depth=1] tweet_id=178 | inbound=False | @115743 There is no info to share at the moment. Feel free to keep an eye on the PS Blog for news and updates: https://t.co/aLtfBAztyC
[depth=2] tweet_id=179 | inbound=True | @AskPlayStation @115743 Can I get help already??

In [45]:
# Build conversation complexity statistics
# for all customer-started conversations.

from collections import deque

def get_root_conversation_stats(root_id):
    """
    Traverse one customer-rooted conversation tree
    and calculate its structural statistics.
    """

    root_id = int(root_id)

    queue = deque([(root_id, 0)])
    visited = set()

    total_nodes = 0
    customer_nodes = 0
    company_nodes = 0
    max_depth = 0

    while queue:

        tweet_id, depth = queue.popleft()

        if tweet_id in visited:
            continue

        visited.add(tweet_id)

        row = df.loc[df["tweet_id"] == tweet_id].iloc[0]

        total_nodes += 1
        max_depth = max(max_depth, depth)

        if bool(row["inbound"]):
            customer_nodes += 1
        else:
            company_nodes += 1

        for child_id in children.get(tweet_id, []):
            queue.append((int(child_id), depth + 1))

    return (
        root_id,
        total_nodes,
        customer_nodes,
        company_nodes,
        max_depth,
    )

In [46]:
tweet_lookup = df.set_index("tweet_id")[
    ["inbound", "text"]
]

print("Tweet lookup rows:", len(tweet_lookup))
print("Unique tweet IDs:", tweet_lookup.index.is_unique)

Tweet lookup rows: 2811774
Unique tweet IDs: True

In [47]:
def get_root_conversation_stats(root_id):
    """
    Traverse one customer-rooted conversation tree
    using the indexed tweet lookup.
    """

    root_id = int(root_id)

    queue = deque([(root_id, 0)])
    visited = set()

    total_nodes = 0
    customer_nodes = 0
    company_nodes = 0
    max_depth = 0

    while queue:

        tweet_id, depth = queue.popleft()

        if tweet_id in visited:
            continue

        visited.add(tweet_id)

        row = tweet_lookup.loc[tweet_id]

        total_nodes += 1
        max_depth = max(max_depth, depth)

        if bool(row["inbound"]):
            customer_nodes += 1
        else:
            company_nodes += 1

        for child_id in children.get(tweet_id, []):
            queue.append((int(child_id), depth + 1))

    return (
        root_id,
        total_nodes,
        customer_nodes,
        company_nodes,
        max_depth,
    )

In [48]:
test_root = int(customer_roots.iloc[0]["tweet_id"])

print(
    get_root_conversation_stats(test_root)
)

(8, 10, 5, 5, 6)

In [49]:
for root_id in customer_roots["tweet_id"].head(10):
    print(get_root_conversation_stats(int(root_id)))

(8, 10, 5, 5, 6)
(18, 8, 3, 5, 5)
(20, 2, 1, 1, 1)
(29, 9, 5, 4, 7)
(31, 2, 1, 1, 1)
(33, 2, 1, 1, 1)
(36, 4, 2, 2, 3)
(39, 2, 1, 1, 1)
(49, 10, 7, 3, 9)
(59, 10, 5, 5, 9)

In [50]:
# Build conversation statistics for all
# customer-started conversations.

from tqdm.auto import tqdm

all_conversation_stats = []

for root_id in tqdm(
    customer_roots["tweet_id"],
    total=len(customer_roots),
    desc="Building conversation targets"
):
    all_conversation_stats.append(
        get_root_conversation_stats(int(root_id))
    )

conversation_stats_full = pd.DataFrame(
    all_conversation_stats,
    columns=[
        "root_id",
        "total_nodes",
        "customer_nodes",
        "company_nodes",
        "max_depth",
    ]
)

print("Shape:", conversation_stats_full.shape)
conversation_stats_full.head()

Building conversation targets:   0%|          | 0/787346 [00:00<?, ?it/s]

Building conversation targets: 100%|██████████| 787346/787346 [03:05<00:00, 4244.25it/s]

Shape: (787346, 5)

   root_id  total_nodes  customer_nodes  company_nodes  max_depth
0        8           10               5              5          6
1       18            8               3              5          5
2       20            2               1              1          1
3       29            9               5              4          7
4       31            2               1              1          1

In [51]:
conversation_stats_full["multi_turn"] = (
    conversation_stats_full["max_depth"] >= 2
)

print("Target distribution:")
print(
    conversation_stats_full["multi_turn"]
    .value_counts()
    .sort_index()
)

print("\nTarget percentage:")
print(
    conversation_stats_full["multi_turn"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Target distribution:
multi_turn
False    463161
True     324185
Name: count, dtype: int64

Target percentage:
multi_turn
False    58.83
True     41.17
Name: proportion, dtype: float64

In [52]:
ci_dataset = customer_roots[
    ["tweet_id", "text"]
].rename(
    columns={
        "tweet_id": "root_id"
    }
).merge(
    conversation_stats_full[
        [
            "root_id",
            "total_nodes",
            "customer_nodes",
            "company_nodes",
            "max_depth",
            "multi_turn",
        ]
    ],
    on="root_id",
    how="inner",
    validate="one_to_one",
)

print("CI dataset shape:", ci_dataset.shape)
print("\nColumns:")
print(ci_dataset.columns.tolist())

ci_dataset.head()

CI dataset shape: (787346, 7)

Columns:
['root_id', 'text', 'total_nodes', 'customer_nodes', 'company_nodes', 'max_depth', 'multi_turn']

,root_id,text,total_nodes,customer_nodes,company_nodes,max_depth,multi_turn
0,8,@sprintcare is the worst customer service,10,5,5,6,True
1,18,@115714 y’all lie about your “great” connectio...,8,3,5,5,True
2,20,"@115714 whenever I contact customer support, t...",2,1,1,1,False
3,29,actually that's a broken link you sent me and ...,9,5,4,7,True
4,31,"Yo @Ask_Spectrum, your customer service reps a...",2,1,1,1,False

In [53]:
print("Rows:", len(ci_dataset))

print(
    "Unique root IDs:",
    ci_dataset["root_id"].nunique()
)

print(
    "Missing text:",
    ci_dataset["text"].isna().sum()
)

print(
    "Missing target:",
    ci_dataset["multi_turn"].isna().sum()
)

print(
    "\nTarget counts:"
)

print(
    ci_dataset["multi_turn"]
    .value_counts()
    .sort_index()
)

Rows: 787346
Unique root IDs: 787346
Missing text: 0
Missing target: 0

Target counts:
multi_turn
False    463161
True     324185
Name: count, dtype: int64

In [54]:
print("\nTarget vs maximum depth:")

print(
    pd.crosstab(
        ci_dataset["max_depth"],
        ci_dataset["multi_turn"]
    ).head(10)
)

Target vs maximum depth:
multi_turn   False   True
max_depth
1           463161       0
2                0  103358
3                0  113489
4                0   33262
5                0   33326
6                0   11890
7                0   11462
8                0    4742
9                0    4383
10               0    2035

In [55]:
ci_dataset["text_chars"] = ci_dataset["text"].str.len()

ci_dataset["text_words"] = (
    ci_dataset["text"]
    .str.split()
    .str.len()
)

print("Character length by target:")
print(
    ci_dataset.groupby("multi_turn")["text_chars"]
    .describe()
)

print("\nWord count by target:")
print(
    ci_dataset.groupby("multi_turn")["text_words"]
    .describe()
)

Character length by target:
               count        mean        std  min   25%    50%    75%    max
multi_turn
False       463161.0  116.389977  51.429351  3.0  80.0  116.0  139.0  315.0
True        324185.0  124.607052  52.143930  1.0  90.0  125.0  140.0  328.0

Word count by target:
               count       mean       std  min   25%   50%   75%    max
multi_turn
False       463161.0  19.804109  9.680162  1.0  13.0  19.0  25.0  112.0
True        324185.0  21.184055  9.785779  1.0  15.0  21.0  25.0  137.0

In [56]:
print("\nMedian / mean comparison:")

print(
    ci_dataset.groupby("multi_turn")[
        ["text_chars", "text_words"]
    ].agg(["mean", "median"])
)

Median / mean comparison:
            text_chars        text_words
                  mean median       mean median
multi_turn
False       116.389977  116.0  19.804109   19.0
True        124.607052  125.0  21.184055   21.0

In [57]:
short_message_stats = (
    ci_dataset
    .assign(
        char_bucket=pd.cut(
            ci_dataset["text_chars"],
            bins=[0, 10, 20, 40, 60, 80, 100, 150, 200, 400],
            include_lowest=True
        )
    )
    .groupby(["char_bucket", "multi_turn"], observed=True)
    .size()
    .unstack(fill_value=0)
)

print(short_message_stats)

multi_turn       False   True
char_bucket
(-0.001, 10.0]     305     169
(10.0, 20.0]      2428    1216
(20.0, 40.0]     18419    9168
(40.0, 60.0]     40065   20495
(60.0, 80.0]     55199   31285
(80.0, 100.0]    62537   39119
(100.0, 150.0]  207345  157502
(150.0, 200.0]   44753   36920
(200.0, 400.0]   32110   28311

In [58]:
bucket_target_rate = (
    ci_dataset
    .assign(
        char_bucket=pd.cut(
            ci_dataset["text_chars"],
            bins=[0, 10, 20, 40, 60, 80, 100, 150, 200, 400],
            include_lowest=True
        )
    )
    .groupby("char_bucket", observed=True)["multi_turn"]
    .agg(
        conversations="count",
        multi_turn_rate="mean"
    )
)

bucket_target_rate["multi_turn_rate"] = (
    bucket_target_rate["multi_turn_rate"] * 100
).round(2)

print(bucket_target_rate)

                conversations  multi_turn_rate
char_bucket
(-0.001, 10.0]            474            35.65
(10.0, 20.0]             3644            33.37
(20.0, 40.0]            27587            33.23
(40.0, 60.0]            60560            33.84
(60.0, 80.0]            86484            36.17
(80.0, 100.0]          101656            38.48
(100.0, 150.0]         364847            43.17
(150.0, 200.0]          81673            45.20
(200.0, 400.0]          60421            46.86

In [59]:
duplicate_text_target = (
    ci_dataset
    .groupby("text")["multi_turn"]
    .agg(
        occurrences="size",
        unique_targets="nunique"
    )
)

print("Unique root texts:", len(duplicate_text_target))

print(
    "\nTexts appearing more than once:",
    (duplicate_text_target["occurrences"] > 1).sum()
)

print(
    "Texts appearing with multiple targets:",
    (duplicate_text_target["unique_targets"] > 1).sum()
)

Unique root texts: 784060

Texts appearing more than once: 974
Texts appearing with multiple targets: 415

In [60]:
conflicting_texts = duplicate_text_target[
    duplicate_text_target["unique_targets"] > 1
]

print("Conflicting duplicate texts:", len(conflicting_texts))

if len(conflicting_texts) > 0:
    print("\nExamples:")
    print(
        conflicting_texts
        .sort_values("occurrences", ascending=False)
        .head(20)
    )

Conflicting duplicate texts: 415

Examples:
                                                    occurrences  \
text
@AirAsiaSupport                                             287
@HPSupport [TYPE YOUR QUESTION HERE] #hppsdr #i...          168
@azuresupport #azTechHelp                                   167
@ComcastCares\n#mobile_Care                                 161
@ComcastCares\n#mobile_CareXI                                82
@AskAmex                                                     78
Wish @SouthwestAir would have some #SouthwestHe...           73
@azuresupport #azhelp:                                       61
@HPSupport [REPLACE THIS TEXT WITH YOUR QUESTIO...           45
@Uber_Support                                                40
I need my in-flight coffee @Delta, but I can't ...           39
@Safaricom_Care check DM                                     37
@115714                                                      36
@BofA_Help                                                   33
Love that @AmericanAir has soy creamer in the A...           29
@HPSupport [ASK YOUR QUESTION HERE] #HPcpIN                  28
@azuresupport #azcommunity                                   27
@Safaricom_Care check dm                                     26
@XboxSupport I need help                                     22
@Delta                                                       21

                                                    unique_targets
text
@AirAsiaSupport                                                  2
@HPSupport [TYPE YOUR QUESTION HERE] #hppsdr #i...               2
@azuresupport #azTechHelp                                        2
@ComcastCares\n#mobile_Care                                      2
@ComcastCares\n#mobile_CareXI                                    2
@AskAmex                                                         2
Wish @SouthwestAir would have some #SouthwestHe...               2
@azuresupport #azhelp:                                           2
@HPSupport [REPLACE THIS TEXT WITH YOUR QUESTIO...               2
@Uber_Support                                                    2
I need my in-flight coffee @Delta, but I can't ...               2
@Safaricom_Care check DM                                         2
@115714                                                          2
@BofA_Help                                                       2
Love that @AmericanAir has soy creamer in the A...               2
@HPSupport [ASK YOUR QUESTION HERE] #HPcpIN                      2
@azuresupport #azcommunity                                       2
@Safaricom_Care check dm                                         2
@XboxSupport I need help                                         2
@Delta                                                           2

In [61]:
ci_dataset["alpha_chars"] = (
    ci_dataset["text"]
    .str.count(r"[A-Za-z]")
)

ci_dataset["alpha_ratio"] = (
    ci_dataset["alpha_chars"]
    / ci_dataset["text_chars"]
)

print("Alphabetic-character ratio:")
print(
    ci_dataset.groupby("multi_turn")["alpha_ratio"]
    .describe()
)

Alphabetic-character ratio:
               count      mean       std  min       25%       50%       75%  \
multi_turn
False       463161.0  0.736300  0.087118  0.0  0.709677  0.752381  0.785714
True        324185.0  0.738213  0.082155  0.0  0.712644  0.753165  0.784615

            max
multi_turn
False       1.0
True        1.0

In [62]:
print("\nMessages with very low alphabetic content:")

for threshold in [0.25, 0.50, 0.75]:
    count = (ci_dataset["alpha_ratio"] < threshold).sum()
    percentage = count / len(ci_dataset) * 100

    print(
        f"< {threshold:.2f}: "
        f"{count:,} ({percentage:.2f}%)"
    )

Messages with very low alphabetic content:
< 0.25: 5,551 (0.71%)
< 0.50: 11,999 (1.52%)
< 0.75: 372,454 (47.30%)

In [63]:
alpha_bucket_stats = (
    ci_dataset
    .assign(
        alpha_bucket=pd.cut(
            ci_dataset["alpha_ratio"],
            bins=[-0.01, 0.25, 0.50, 0.75, 1.0],
            labels=[
                "<25%",
                "25–50%",
                "50–75%",
                "75–100%"
            ]
        )
    )
    .groupby("alpha_bucket", observed=True)["multi_turn"]
    .agg(
        conversations="count",
        multi_turn_rate="mean"
    )
)

alpha_bucket_stats["multi_turn_rate"] = (
    alpha_bucket_stats["multi_turn_rate"] * 100
).round(2)

print(alpha_bucket_stats)

              conversations  multi_turn_rate
alpha_bucket
<25%                   5659            37.11
25–50%                 7150            38.14
50–75%               372003            41.00
75–100%              402534            41.44

In [64]:
ci_dataset["has_url"] = (
    ci_dataset["text"]
    .str.contains(r"https?://|www\.", case=False, regex=True, na=False)
)

ci_dataset["has_mention"] = (
    ci_dataset["text"]
    .str.contains(r"@\w+", regex=True, na=False)
)

print("URL presence:")
print(ci_dataset["has_url"].value_counts())

print("\nMention presence:")
print(ci_dataset["has_mention"].value_counts())

URL presence:
has_url
False    625705
True     161641
Name: count, dtype: int64

Mention presence:
has_mention
True     734313
False     53033
Name: count, dtype: int64

In [65]:
url_target_stats = (
    ci_dataset
    .groupby("has_url")["multi_turn"]
    .agg(
        conversations="count",
        multi_turn_rate="mean"
    )
)

mention_target_stats = (
    ci_dataset
    .groupby("has_mention")["multi_turn"]
    .agg(
        conversations="count",
        multi_turn_rate="mean"
    )
)

url_target_stats["multi_turn_rate"] *= 100
mention_target_stats["multi_turn_rate"] *= 100

url_target_stats["multi_turn_rate"] = (
    url_target_stats["multi_turn_rate"].round(2)
)

mention_target_stats["multi_turn_rate"] = (
    mention_target_stats["multi_turn_rate"].round(2)
)

print("URL vs target:")
print(url_target_stats)

print("\nMention vs target:")
print(mention_target_stats)

URL vs target:
         conversations  multi_turn_rate
has_url
False           625705            40.68
True            161641            43.07

Mention vs target:
             conversations  multi_turn_rate
has_mention
False                53033            45.63
True                734313            40.85

In [66]:
print("\nAverage mention count:")

mention_counts = (
    ci_dataset["text"]
    .str.count(r"@\w+")
)

print(
    mention_counts.groupby(
        ci_dataset["multi_turn"]
    ).describe()
)

Average mention count:
               count      mean       std  min  25%  50%  75%   max
multi_turn
False       463161.0  1.117978  0.601195  0.0  1.0  1.0  1.0  25.0
True        324185.0  1.131289  0.660354  0.0  1.0  1.0  1.0  22.0

In [67]:
ci_dataset["first_mention"] = (
    ci_dataset["text"]
    .str.extract(r"(@\w+)", expand=False)
)

print("First mention coverage:")
print(
    ci_dataset["first_mention"]
    .notna()
    .value_counts()
)

print("\nUnique first-mentioned accounts:")
print(
    ci_dataset["first_mention"].nunique()
)

First mention coverage:
first_mention
True     734315
False     53031
Name: count, dtype: int64

Unique first-mentioned accounts:
11389

In [68]:
mention_target = (
    ci_dataset
    .dropna(subset=["first_mention"])
    .groupby("first_mention")["multi_turn"]
    .agg(
        conversations="count",
        multi_turn_rate="mean"
    )
)

mention_target["multi_turn_rate"] = (
    mention_target["multi_turn_rate"] * 100
).round(2)

print(
    mention_target
    .sort_values("conversations", ascending=False)
    .head(30)
)

                  conversations  multi_turn_rate
first_mention
@AppleSupport             44479            34.80
@115858                   30626            28.89
@AmericanAir              23535            42.54
@Delta                    20957            35.24
@SouthwestAir             18520            32.01
@AmazonHelp               17863            62.36
@Uber_Support             16699            34.59
@115873                   15749            34.71
@115821                   15715            58.13
@British_Airways          15104            42.53
@Tesco                    14898            47.23
@VirginTrains             13279            58.94
@ChipotleTweets           12742            32.49
@115850                   12685            50.09
@SpotifyCares             11960            32.47
@115888                   11804            35.09
@115911                   10823            37.34
@AskPlayStation           10364            43.50
@Ask_Spectrum             10047            31.94
@XboxSupport              10020            52.45
@GWRHelp                   9834            62.64
@sainsburys                9624            52.44
@115714                    8699            40.04
@116062                    8689            31.51
@O2                        7926            44.08
@115817                    7802            30.62
@Safaricom_Care            7460            42.29
@marksandspencer           7363            38.27
@hulu_support              7209            38.60
@115830                    6881            63.83

In [69]:
print("Messages covered by top 10 mentioned accounts:")

top10_mentions = (
    ci_dataset["first_mention"]
    .value_counts()
    .head(10)
)

print(top10_mentions)

print(
    "\nCoverage:",
    round(
        top10_mentions.sum()
        / len(ci_dataset)
        * 100,
        2
    ),
    "%"
)

Messages covered by top 10 mentioned accounts:
first_mention
@AppleSupport       44479
@115858             30626
@AmericanAir        23535
@Delta              20957
@SouthwestAir       18520
@AmazonHelp         17863
@Uber_Support       16699
@115873             15749
@115821             15715
@British_Airways    15104
Name: count, dtype: int64

Coverage: 27.85 %

In [70]:
# Keep only the fields that are allowed to reach the model.
# root_id is retained for traceability; text + multi_turn are the modelling fields.

modeling_dataset = ci_dataset[
    ["root_id", "text", "multi_turn"]
].copy()

print("Modelling dataset shape:", modeling_dataset.shape)

print("\nColumns:")
print(modeling_dataset.columns.tolist())

print("\nFirst 5 rows:")
display(modeling_dataset.head())

Modelling dataset shape: (787346, 3)

Columns:
['root_id', 'text', 'multi_turn']

First 5 rows:

   root_id                                               text  multi_turn
0        8          @sprintcare is the worst customer service        True
1       18  @115714 y’all lie about your “great” connectio...        True
2       20  @115714 whenever I contact customer support, t...       False
3       29  actually that's a broken link you sent me and ...        True
4       31  Yo @Ask_Spectrum, your customer service reps a...       False

In [71]:
forbidden_columns = [
    "total_nodes",
    "customer_nodes",
    "company_nodes",
    "max_depth",
]

remaining_forbidden = [
    col for col in forbidden_columns
    if col in modeling_dataset.columns
]

print("Forbidden target-derived columns remaining:")
print(remaining_forbidden)

assert len(remaining_forbidden) == 0

print("\nLeakage check passed.")

Forbidden target-derived columns remaining:
[]

Leakage check passed.

In [72]:
print("Text missing:", modeling_dataset["text"].isna().sum())
print("Target missing:", modeling_dataset["multi_turn"].isna().sum())

print("\nUnique root IDs:", modeling_dataset["root_id"].nunique())
print("Total rows:", len(modeling_dataset))

assert modeling_dataset["text"].notna().all()
assert modeling_dataset["multi_turn"].notna().all()
assert modeling_dataset["root_id"].is_unique

print("\nModelling dataset integrity check passed.")

Text missing: 0
Target missing: 0

Unique root IDs: 787346
Total rows: 787346

Modelling dataset integrity check passed.

In [73]:
text_frequency = (
    modeling_dataset
    .groupby("text")
    .size()
    .rename("text_frequency")
)

modeling_dataset = modeling_dataset.merge(
    text_frequency,
    on="text",
    how="left",
    validate="many_to_one",
)

print("Rows with duplicated text:")
print(
    (modeling_dataset["text_frequency"] > 1).sum()
)

print(
    "Rows with unique text:",
    (modeling_dataset["text_frequency"] == 1).sum()
)

Rows with duplicated text:
4260
Rows with unique text: 783086

In [74]:
text_target_groups = (
    modeling_dataset
    .groupby("text")["multi_turn"]
    .nunique()
)

conflicting_texts = text_target_groups[
    text_target_groups > 1
]

print(
    "Conflicting duplicate text groups:",
    len(conflicting_texts)
)

print(
    "Rows belonging to conflicting groups:",
    modeling_dataset["text"].isin(conflicting_texts.index).sum()
)

Conflicting duplicate text groups: 415
Rows belonging to conflicting groups: 2852

In [75]:
modeling_dataset = modeling_dataset[
    ["root_id", "text", "multi_turn"]
].copy()

print("Final modelling dataset:")
print(modeling_dataset.shape)
print(modeling_dataset.columns.tolist())

Final modelling dataset:
(787346, 3)
['root_id', 'text', 'multi_turn']

In [76]:
import sklearn

print("scikit-learn version:", sklearn.__version__)

scikit-learn version: 1.9.0

In [77]:
from sklearn.model_selection import train_test_split

# One row per unique initial customer message.
# A text belongs to exactly one split.
text_groups = (
    modeling_dataset[
        ["text", "multi_turn"]
    ]
    .groupby("text", as_index=False)
    .agg(
        target=("multi_turn", "first"),
        occurrences=("multi_turn", "size"),
        unique_targets=("multi_turn", "nunique"),
    )
)

print("Unique text groups:", len(text_groups))

print("\nTarget distribution across text groups:")
print(
    text_groups["target"]
    .value_counts()
    .sort_index()
)

print("\nConflicting groups:")
print(
    (text_groups["unique_targets"] > 1).sum()
)

Unique text groups: 784060

Target distribution across text groups:
target
False    460778
True     323282
Name: count, dtype: int64

Conflicting groups:
415

In [78]:
conflicting_texts = text_groups[
    text_groups["unique_targets"] > 1
]["text"]

conflicting_examples = modeling_dataset[
    modeling_dataset["text"].isin(conflicting_texts)
].sort_values("text")

print("Conflicting text groups:", len(conflicting_texts))
print("Rows belonging to conflicting groups:", len(conflicting_examples))

print("\nFirst 20 conflicting groups:\n")

for text, group in conflicting_examples.groupby("text", sort=False):
    print("=" * 100)
    print("TEXT:", text)
    print("TARGET COUNTS:")
    print(group["multi_turn"].value_counts().sort_index().to_dict())
    
    # Show only the first few root IDs for verification
    print("Example root IDs:", group["root_id"].head(5).tolist())

Conflicting text groups: 415
Rows belonging to conflicting groups: 2852

First 20 conflicting groups:

====================================================================================================
TEXT: #Comcast #Xfinity cancels #Weatherscan in Philly area. Less product, more money, no concern for customers. FIOS and Dish have 2 b better.
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [1710898, 2145030, 2198693]
====================================================================================================
TEXT: .@Sainsburys @318507, don’t ditch Fairtrade! Your new ‘Fairly Traded’ label is #NotMyCupOfTea
TARGET COUNTS:
{False: 4, True: 1}
Example root IDs: [833588, 833598, 838910, 1059941, 1066090]
====================================================================================================
TEXT: 4 hrs w/iOS 11.1, no change in battery consumption @AppleSupport. Thanks anyway. Can we have iOS 10 back @115858?
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [15315, 1677846]
====================================================================================================
TEXT: @115714
TARGET COUNTS:
{False: 35, True: 1}
Example root IDs: [13427, 48744, 562614, 624613, 1188759]
====================================================================================================
TEXT: @115714 fuck you
TARGET COUNTS:
{False: 3, True: 1}
Example root IDs: [596998, 978068, 1327995, 1832030]
====================================================================================================
TEXT: @115714 sucks
TARGET COUNTS:
{False: 3, True: 1}
Example root IDs: [716344, 1010453, 2211150, 2332619]
====================================================================================================
TEXT: @115714 you fucking suck
TARGET COUNTS:
{False: 3, True: 1}
Example root IDs: [741793, 770679, 826828, 2175529]
====================================================================================================
TEXT: @115714 your service is trash
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2195900, 2928011]
====================================================================================================
TEXT: @115714 your service sucks ass
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1763447, 2282726]
====================================================================================================
TEXT: @115758
Will there be a Bo3 old gen update?
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [193899, 269694]
====================================================================================================
TEXT: @115765 fix your game
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2371952, 2722978]
====================================================================================================
TEXT: @115765 please fix your game
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [650927, 2165321]
====================================================================================================
TEXT: @115766 FIX YOUR GAME
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1637481, 2429768]
====================================================================================================
TEXT: @115766 fix your servers
TARGET COUNTS:
{False: 1, True: 2}
Example root IDs: [98559, 1486758, 2351609]
====================================================================================================
TEXT: @115817
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [2057466, 2065395, 2654605]
====================================================================================================
TEXT: @115817 you guys suck
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [496987, 2646113]
====================================================================================================
TEXT: @115821 @115851 seriously more items are late. I find this unacceptable. I need a call today from a high level manager or I start a lawsuit.
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [542149, 2927737]
====================================================================================================
TEXT: @115821 help
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [694435, 1232140]
====================================================================================================
TEXT: @115850
TARGET COUNTS:
{False: 4, True: 3}
Example root IDs: [179101, 1738998, 2094109, 2393579, 2553948]
====================================================================================================
TEXT: @115850 Hi
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [128142, 998049]
====================================================================================================
TEXT: @115850 I ordered an MI4 Phone and received a different product.

#406-8163465-8665102

Please refer images. Ensure a return and delivery of correct product in next 48 hours or else expect an FIR, followed by Legal Action.

Thanks
Mehar Nazeer
9711747938
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [71875, 2610756]
====================================================================================================
TEXT: @115850 is #OnePlus5T  available for all customers or only prime member on the sale on 24 November???
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [644856, 677619]
====================================================================================================
TEXT: @115858 FIX MY PHONE
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1589915, 2032098]
====================================================================================================
TEXT: @115858 fix my phone
TARGET COUNTS:
{False: 1, True: 2}
Example root IDs: [962180, 1447257, 2143960]
====================================================================================================
TEXT: @115858 fix this I️
TARGET COUNTS:
{False: 10, True: 2}
Example root IDs: [50068, 1584613, 1635780, 1640818, 1705334]
====================================================================================================
TEXT: @115858 fix this I️ shit
TARGET COUNTS:
{False: 3, True: 1}
Example root IDs: [1517061, 1742396, 1754118, 2633092]
====================================================================================================
TEXT: @115858 please fix this I️
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [1995871, 2283801, 2505108]
====================================================================================================
TEXT: @115858 pls fix our phones
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1418614, 2314372]
====================================================================================================
TEXT: @115858 since the intro of iOS 11 I’ve noticed several bugs; including difficulty sending/receiving mail, updates not working and it crashes!
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [401706, 2078072]
====================================================================================================
TEXT: @115858 your update killed my phone
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [368781, 2082448]
====================================================================================================
TEXT: @115900 @comcastcares Please bring high speed internet to Deer Creek Canyon, Littleton, CO. #HughesNet is way too slow and unreliable!
TARGET COUNTS:
{False: 6, True: 1}
Example root IDs: [1278325, 1729567, 1795368, 1998773, 2433100]
====================================================================================================
TEXT: @115900 you’re the worst
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [465332, 2079629]
====================================================================================================
TEXT: @115911
TARGET COUNTS:
{False: 1, True: 2}
Example root IDs: [2370200, 2472793, 2938064]
====================================================================================================
TEXT: @115911 Dm
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2749653, 2827861]
====================================================================================================
TEXT: @115911 i have a question
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2134158, 2665002]
====================================================================================================
TEXT: @115911 is the worst
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1596279, 1638004]
====================================================================================================
TEXT: @115911 need some help
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [638230, 2786825]
====================================================================================================
TEXT: @115911 u suck
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2134074, 2583582]
====================================================================================================
TEXT: @115911 your service sucks
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [104659, 1404394]
====================================================================================================
TEXT: @115913
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1098788, 1898177]
====================================================================================================
TEXT: @115937 thanks for that lack of help I got after my account was hacked.
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1543848, 2090040]
====================================================================================================
TEXT: @115955 your internet sucks ass
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1544293, 2058112]
====================================================================================================
TEXT: @116016
TARGET COUNTS:
{False: 3, True: 2}
Example root IDs: [642417, 1409348, 1499418, 2173501, 2646869]
====================================================================================================
TEXT: @116016 fuck you
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [195137, 1980613]
====================================================================================================
TEXT: @116035 i need help
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [1462364, 1902745, 2191367]
====================================================================================================
TEXT: @116136  download 14.7. Upload 7.3
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [701976, 705919]
====================================================================================================
TEXT: @116136 you suck
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2094596, 2252583]
====================================================================================================
TEXT: @116245 Is there any possible way that a HUGE fan like me simply get a follow from you it would truly mean the world to me! 😁
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [2227901, 2227935, 2325870]
====================================================================================================
TEXT: @116329 I am very disappointing for 4g speed is poor @airtel_care
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2118151, 2395642]
====================================================================================================
TEXT: @116333 Hey there, I got laid by Istanbul Zorlu Center Apple Store.Please could you help me, Im a victim here.
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2320602, 2398103]
====================================================================================================
TEXT: @116589  sir, when customers from Jio network call to Idea network they are made to listen promotional message from idea which is more than 20 secs long.Dis is a marketting tactic frm idea but harassment 4 the customers as they are made to listen this everytime 4 evry call
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2165173, 2775581]
====================================================================================================
TEXT: @116827 FUCK YOU
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [204034, 616824]
====================================================================================================
TEXT: @116827 fuck you
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [467294, 1853186, 2868181]
====================================================================================================
TEXT: @116827 you suck
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [303964, 2307660]
====================================================================================================
TEXT: @116935 when are you launching in India?
TARGET COUNTS:
{False: 1, True: 2}
Example root IDs: [1881142, 2361849, 2410478]
====================================================================================================
TEXT: @117153
TARGET COUNTS:
{False: 4, True: 1}
Example root IDs: [45302, 566346, 897195, 1158353, 1400831]
====================================================================================================
TEXT: @118919 worst service
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [363687, 2452841]
====================================================================================================
TEXT: @121984 preciso de ajuda
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [346426, 1515255, 2625527]
====================================================================================================
TEXT: @824
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1151074, 2503409]
====================================================================================================
TEXT: @ATVIAssist
TARGET COUNTS:
{False: 3, True: 2}
Example root IDs: [1048644, 1058666, 1801940, 1905152, 2432321]
====================================================================================================
TEXT: @ATVIAssist I need assistance
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [122962, 2456937]
====================================================================================================
TEXT: @ATVIAssist I need help
TARGET COUNTS:
{False: 1, True: 3}
Example root IDs: [130477, 174818, 197522, 1706543]
====================================================================================================
TEXT: @AdobeCare I just added payment details after a year of CC Student Edition, do I automatically renew it for the same price? I didn't have to confirm my student status and I can't find how much I'll have to pay now..
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [604514, 2794758]
====================================================================================================
TEXT: @AirAsiaSupport
TARGET COUNTS:
{False: 215, True: 72}
Example root IDs: [12900, 13813, 18083, 23942, 49028]
====================================================================================================
TEXT: @AirAsiaSupport hi
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1253581, 1292841]
====================================================================================================
TEXT: @AirAsiaSupport hi,please help to make name correction for booking code ZIPGQV, correct passenger name should be FIRDZARULLAH BIN  AMIDDUDIN
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1492239, 1568393]
====================================================================================================
TEXT: @AirAsiaSupport please reply my DM, thanks
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2846017, 2868683]
====================================================================================================
TEXT: @AirbnbHelp
TARGET COUNTS:
{False: 7, True: 1}
Example root IDs: [364606, 491324, 1008260, 1120907, 1306250]
====================================================================================================
TEXT: @AmazonHelp
TARGET COUNTS:
{False: 2, True: 2}
Example root IDs: [19109, 774236, 971295, 1231273]
====================================================================================================
TEXT: @AmazonHelp DM
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1847505, 1897820]
====================================================================================================
TEXT: @AmazonHelp help
TARGET COUNTS:
{False: 1, True: 4}
Example root IDs: [346973, 764160, 773497, 1032387, 2753585]
====================================================================================================
TEXT: @AmazonHelp i have a question
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1028203, 1746066]
====================================================================================================
TEXT: @AmericanAir
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [1425841, 2301677, 2773615]
====================================================================================================
TEXT: @AmericanAir Please allow pets to travel in cargo area &amp; extend the waiver fee period for pets in cabin. No Pets Left Behind #PuertoRico
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [992709, 1073600]
====================================================================================================
TEXT: @AmericanAir damaged my bag. I have the pictures and instead of giving me a new one. They want me to drive 40 miles to SEE my bag! That’s ridiculous! Improve your service and take care of your client’s luggage! Guys, advice: choose another company to travel!
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2710209, 2731989]
====================================================================================================
TEXT: @AmericanAir you suck
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2807820, 2867988]
====================================================================================================
TEXT: @AppleSupport
Hello, there is serious problem in iOS 11.1 and iOS 11.1.1
hundreds, maybe thousands of iPhones in our region are restarting by itself and stuck on apple logo
we have to restore it with recovery or back to iOS 11.0.3 to fix it
please take it seriously and solve it
TARGET COUNTS:
{False: 1, True: 2}
Example root IDs: [2356492, 2363104, 2367857]
====================================================================================================
TEXT: @AppleSupport @115858 ur new update 11.0.2 is draining battery like hell pls fix this asap
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [647359, 2064225]
====================================================================================================
TEXT: @AppleSupport HELP ME
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [631805, 1569688]
====================================================================================================
TEXT: @AppleSupport HELP ME PLEASE
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [929706, 1296701]
====================================================================================================
TEXT: @AppleSupport Hi, the reservations (iPhone X) for today was supposed to start at 6:00 AM on Mexico. Do you know when will be available?
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [1578473, 1586313]
====================================================================================================
TEXT: @AppleSupport I have a question
TARGET COUNTS:
{False: 2, True: 1}
Example root IDs: [340916, 1038172, 2117123]
====================================================================================================
TEXT: @AppleSupport I have the iPhone 7 and I updated my phone to IOS 11.1.1 and when I turned off the phone it would not come back on. It's been stuck in a loop on the Apple logo screen every since. I tried to restore it with iTunes and it didn’t work.
TARGET COUNTS:
{False: 1, True: 1}
Example root IDs: [2364482, 2366161]

In [79]:
from sklearn.model_selection import train_test_split

# ---------------------------------------------------------
# Split unique text groups first.
# Every identical initial message stays in one split.
# ---------------------------------------------------------

train_groups, temp_groups = train_test_split(
    text_groups,
    test_size=0.20,
    random_state=42,
    stratify=text_groups["target"],
)

val_groups, test_groups = train_test_split(
    temp_groups,
    test_size=0.50,
    random_state=42,
    stratify=temp_groups["target"],
)

print("Unique text groups:")
print("Train:", len(train_groups))
print("Validation:", len(val_groups))
print("Test:", len(test_groups))

print("\nTarget distribution:")
print("\nTrain:")
print(train_groups["target"].value_counts().sort_index())

print("\nValidation:")
print(val_groups["target"].value_counts().sort_index())

print("\nTest:")
print(test_groups["target"].value_counts().sort_index())

Unique text groups:
Train: 627248
Validation: 78406
Test: 78406

Target distribution:

Train:
target
False    368622
True     258626
Name: count, dtype: int64

Validation:
target
False    46078
True     32328
Name: count, dtype: int64

Test:
target
False    46078
True     32328
Name: count, dtype: int64

In [80]:
# ---------------------------------------------------------
# Assign every original modelling row to the split
# according to its exact initial-message text.
# ---------------------------------------------------------

train_texts = set(train_groups["text"])
val_texts = set(val_groups["text"])
test_texts = set(test_groups["text"])

modeling_dataset["split"] = np.select(
    [
        modeling_dataset["text"].isin(train_texts),
        modeling_dataset["text"].isin(val_texts),
        modeling_dataset["text"].isin(test_texts),
    ],
    [
        "train",
        "validation",
        "test",
    ],
    default="unknown",
)

print("Split distribution:")
print(modeling_dataset["split"].value_counts())

print("\nMissing/unknown split rows:")
print((modeling_dataset["split"] == "unknown").sum())

Split distribution:
split
train         630075
validation     78675
test           78596
Name: count, dtype: int64

Missing/unknown split rows:
0

In [81]:
# ---------------------------------------------------------
# Final split integrity and exact-text leakage checks
# ---------------------------------------------------------

train_df = modeling_dataset[
    modeling_dataset["split"] == "train"
].copy()

val_df = modeling_dataset[
    modeling_dataset["split"] == "validation"
].copy()

test_df = modeling_dataset[
    modeling_dataset["split"] == "test"
].copy()

# 1. Row conservation
total_split_rows = len(train_df) + len(val_df) + len(test_df)

print("Original rows :", len(modeling_dataset))
print("Split rows    :", total_split_rows)

assert total_split_rows == len(modeling_dataset)

# 2. No missing split
assert not modeling_dataset["split"].isna().any()
assert (modeling_dataset["split"] != "unknown").all()

# 3. Exact-text leakage checks
train_text_set = set(train_df["text"])
val_text_set = set(val_df["text"])
test_text_set = set(test_df["text"])

train_val_overlap = train_text_set & val_text_set
train_test_overlap = train_text_set & test_text_set
val_test_overlap = val_text_set & test_text_set

print("\nExact-text overlap:")
print("Train ↔ Validation:", len(train_val_overlap))
print("Train ↔ Test      :", len(train_test_overlap))
print("Validation ↔ Test :", len(val_test_overlap))

assert len(train_val_overlap) == 0
assert len(train_test_overlap) == 0
assert len(val_test_overlap) == 0

# 4. Target distribution by original rows
print("\nTarget distribution by original rows:")

for name, split_df in [
    ("Train", train_df),
    ("Validation", val_df),
    ("Test", test_df),
]:
    counts = split_df["multi_turn"].value_counts().sort_index()
    percentages = (
        split_df["multi_turn"]
        .value_counts(normalize=True)
        .sort_index()
        .mul(100)
    )

    print(f"\n{name}:")
    print("Counts:")
    print(counts)
    print("Percentages:")
    print(percentages.round(2))

print("\nAll integrity checks passed.")

Original rows : 787346
Split rows    : 787346

Exact-text overlap:
Train ↔ Validation: 0
Train ↔ Test      : 0
Validation ↔ Test : 0

Target distribution by original rows:

Train:
Counts:
multi_turn
False    370706
True     259369
Name: count, dtype: int64
Percentages:
multi_turn
False    58.84
True     41.16
Name: proportion, dtype: float64

Validation:
Counts:
multi_turn
False    46253
True     32422
Name: count, dtype: int64
Percentages:
multi_turn
False    58.79
True     41.21
Name: proportion, dtype: float64

Test:
Counts:
multi_turn
False    46202
True     32394
Name: count, dtype: int64
Percentages:
multi_turn
False    58.78
True     41.22
Name: proportion, dtype: float64

All integrity checks passed.

In [82]:
import datasets

print("Hugging Face Datasets version:", datasets.__version__)

Hugging Face Datasets version: 5.0.1

In [83]:
from datasets import Dataset

# ---------------------------------------------------------
# Convert Pandas splits to Hugging Face Datasets
# ---------------------------------------------------------

train_dataset = Dataset.from_pandas(
    train_df[["root_id", "text", "multi_turn"]],
    preserve_index=False,
)

validation_dataset = Dataset.from_pandas(
    val_df[["root_id", "text", "multi_turn"]],
    preserve_index=False,
)

test_dataset = Dataset.from_pandas(
    test_df[["root_id", "text", "multi_turn"]],
    preserve_index=False,
)

print("Train:")
print(train_dataset)

print("\nValidation:")
print(validation_dataset)

print("\nTest:")
print(test_dataset)

Train:
Dataset({
    features: ['root_id', 'text', 'multi_turn'],
    num_rows: 630075
})

Validation:
Dataset({
    features: ['root_id', 'text', 'multi_turn'],
    num_rows: 78675
})

Test:
Dataset({
    features: ['root_id', 'text', 'multi_turn'],
    num_rows: 78596
})

In [84]:
# ---------------------------------------------------------
# Verify Hugging Face Dataset conversion
# ---------------------------------------------------------

print("Train rows      :", train_dataset.num_rows)
print("Validation rows :", validation_dataset.num_rows)
print("Test rows       :", test_dataset.num_rows)

print("\nTrain columns:")
print(train_dataset.column_names)

print("\nSample train record:")
print(train_dataset[0])

# ---------------------------------------------------------
# Verify target values
# ---------------------------------------------------------

print("\nUnique target values:")

print(
    "Train:",
    sorted(set(train_dataset["multi_turn"]))
)

print(
    "Validation:",
    sorted(set(validation_dataset["multi_turn"]))
)

print(
    "Test:",
    sorted(set(test_dataset["multi_turn"]))
)

# ---------------------------------------------------------
# Verify no missing text / target
# ---------------------------------------------------------

assert all(
    text is not None and str(text).strip() != ""
    for text in train_dataset["text"]
)

assert all(
    text is not None and str(text).strip() != ""
    for text in validation_dataset["text"]
)

assert all(
    text is not None and str(text).strip() != ""
    for text in test_dataset["text"]
)

assert set(train_dataset["multi_turn"]) == {False, True}
assert set(validation_dataset["multi_turn"]) == {False, True}
assert set(test_dataset["multi_turn"]) == {False, True}

print("\nHugging Face dataset integrity checks passed.")

Train rows      : 630075
Validation rows : 78675
Test rows       : 78596

Train columns:
['root_id', 'text', 'multi_turn']

Sample train record:
{'root_id': 18, 'text': '@115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.', 'multi_turn': True}

Unique target values:
Train: [False, True]
Validation: [False, True]
Test: [False, True]

Hugging Face dataset integrity checks passed.

In [85]:
# ---------------------------------------------------------
# Define the classification label mapping
# ---------------------------------------------------------

label2id = {
    False: 0,
    True: 1,
}

id2label = {
    0: "SIMPLE",
    1: "MULTI_TURN",
}

print("label2id:", label2id)
print("id2label:", id2label)

# Verify mapping
assert label2id[False] == 0
assert label2id[True] == 1

print("\nLabel mapping verified.")

label2id: {False: 0, True: 1}
id2label: {0: 'SIMPLE', 1: 'MULTI_TURN'}

Label mapping verified.

In [86]:
from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

print("Model:", model_name)
print("Tokenizer:", tokenizer.__class__.__name__)
print("Vocabulary size:", tokenizer.vocab_size)
print("Maximum model length:", tokenizer.model_max_length)

Model: distilbert-base-uncased
Tokenizer: BertTokenizer
Vocabulary size: 30522
Maximum model length: 512

In [87]:
# ---------------------------------------------------------
# Inspect DistilBERT tokenization on real Twitter messages
# ---------------------------------------------------------

sample_texts = [
    train_dataset[0]["text"],
    train_dataset[1]["text"],
    train_dataset[2]["text"],
    "Can you please help me?? @AppleSupport I've been waiting :(",
]

for i, text in enumerate(sample_texts, start=1):

    encoded = tokenizer(
        text,
        truncation=True,
        max_length=128,
    )

    tokens = tokenizer.convert_ids_to_tokens(
        encoded["input_ids"]
    )

    print("=" * 100)
    print(f"Example {i}")
    print("Original:")
    print(text)

    print("\nTokens:")
    print(tokens)

    print("\nToken count:", len(tokens))

====================================================================================================
Example 1
Original:
@115714 y’all lie about your “great” connection. 5 bars LTE, still won’t load something. Smh.

Tokens:
['[CLS]', '@', '115', '##7', '##14', 'y', '’', 'all', 'lie', 'about', 'your', '“', 'great', '”', 'connection', '.', '5', 'bars', 'lt', '##e', ',', 'still', 'won', '’', 't', 'load', 'something', '.', 'sm', '##h', '.', '[SEP]']

Token count: 32
====================================================================================================
Example 2
Original:
@115714 whenever I contact customer support, they tell me I have shortcode enabled on my account, but I have never in the 4 years I've tried https://t.co/0G98RtNxPK

Tokens:
['[CLS]', '@', '115', '##7', '##14', 'whenever', 'i', 'contact', 'customer', 'support', ',', 'they', 'tell', 'me', 'i', 'have', 'short', '##code', 'enabled', 'on', 'my', 'account', ',', 'but', 'i', 'have', 'never', 'in', 'the', '4', 'years', 'i', "'", 've', 'tried', 'https', ':', '/', '/', 't', '.', 'co', '/', '0', '##g', '##9', '##8', '##rt', '##nx', '##p', '##k', '[SEP]']

Token count: 52
====================================================================================================
Example 3
Original:
Yo @Ask_Spectrum, your customer service reps are super nice— but imma start trippin if y’all don’t get my service going!

Tokens:
['[CLS]', 'yo', '@', 'ask', '_', 'spectrum', ',', 'your', 'customer', 'service', 'rep', '##s', 'are', 'super', 'nice', '—', 'but', 'im', '##ma', 'start', 'trip', '##pin', 'if', 'y', '’', 'all', 'don', '’', 't', 'get', 'my', 'service', 'going', '!', '[SEP]']

Token count: 35
====================================================================================================
Example 4
Original:
Can you please help me?? @AppleSupport I've been waiting :(

Tokens:
['[CLS]', 'can', 'you', 'please', 'help', 'me', '?', '?', '@', 'apples', '##up', '##port', 'i', "'", 've', 'been', 'waiting', ':', '(', '[SEP]']

Token count: 20

In [88]:
# ---------------------------------------------------------
# Measure DistilBERT token-length distribution
# on the training data only.
# ---------------------------------------------------------

from tqdm.auto import tqdm

train_texts = train_dataset["text"]

token_lengths = []

batch_size = 5000

for start in tqdm(
    range(0, len(train_texts), batch_size),
    desc="Measuring token lengths"
):
    batch = train_texts[start:start + batch_size]

    encoded = tokenizer(
        batch,
        truncation=False,
        padding=False,
        return_length=True,
    )

    token_lengths.extend(encoded["length"])

token_lengths = np.array(token_lengths)

print("Training examples:", len(token_lengths))

print("\nToken length statistics:")
print(
    pd.Series(token_lengths).describe(
        percentiles=[
            0.50,
            0.75,
            0.90,
            0.95,
            0.99,
            0.995,
            0.999,
        ]
    )
)

print("\nMaximum token length:", token_lengths.max())

Measuring token lengths: 100%|██████████| 127/127 [01:22<00:00,  1.55it/s]

Training examples: 630075

Token length statistics:
count    630075.000000
mean         35.718470
std          14.528572
min           3.000000
50%          34.000000
75%          43.000000
90%          55.000000
95%          63.000000
99%          80.000000
99.5%        87.000000
99.9%       106.000000
max         256.000000
dtype: float64

Maximum token length: 256

In [89]:
# ---------------------------------------------------------
# Quantify potential truncation at max_length = 128
# ---------------------------------------------------------

max_length = 128

over_limit = token_lengths > max_length

print("Chosen max_length:", max_length)

print("\nExamples requiring truncation:")
print("Count:", over_limit.sum())
print("Percentage:", round(over_limit.mean() * 100, 4))

print("\nExamples within limit:")
print("Count:", (~over_limit).sum())
print("Percentage:", round((~over_limit).mean() * 100, 4))

assert over_limit.sum() >= 0
assert (~over_limit).sum() + over_limit.sum() == len(token_lengths)

Chosen max_length: 128

Examples requiring truncation:
Count: 140
Percentage: 0.0222

Examples within limit:
Count: 629935
Percentage: 99.9778

In [90]:
# ---------------------------------------------------------
# Tokenize all modelling splits
# ---------------------------------------------------------

max_length = 128

def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=max_length,
        padding=False,
    )


train_tokenized = train_dataset.map(
    tokenize_batch,
    batched=True,
    batch_size=5000,
    desc="Tokenizing training data",
)

validation_tokenized = validation_dataset.map(
    tokenize_batch,
    batched=True,
    batch_size=5000,
    desc="Tokenizing validation data",
)

test_tokenized = test_dataset.map(
    tokenize_batch,
    batched=True,
    batch_size=5000,
    desc="Tokenizing test data",
)

print("Tokenization complete.")

print("\nTrain columns:")
print(train_tokenized.column_names)

print("\nValidation columns:")
print(validation_tokenized.column_names)

print("\nTest columns:")
print(test_tokenized.column_names)

Tokenizing training data: 100%|██████████| 630075/630075 [01:21<00:00, 7736.23 examples/s]
Tokenizing validation data: 100%|██████████| 78675/78675 [00:09<00:00, 8449.80 examples/s]
Tokenizing test data: 100%|██████████| 78596/78596 [00:09<00:00, 8350.59 examples/s]

Tokenization complete.

Train columns:
['root_id', 'text', 'multi_turn', 'input_ids', 'token_type_ids', 'attention_mask']

Validation columns:
['root_id', 'text', 'multi_turn', 'input_ids', 'token_type_ids', 'attention_mask']

Test columns:
['root_id', 'text', 'multi_turn', 'input_ids', 'token_type_ids', 'attention_mask']

In [91]:
# ---------------------------------------------------------
# Create the Hugging Face training label
# ---------------------------------------------------------

def add_labels(batch):
    return {
        "labels": [
            label2id[value]
            for value in batch["multi_turn"]
        ]
    }


train_tokenized = train_tokenized.map(
    add_labels,
    batched=True,
    batch_size=5000,
    desc="Creating training labels",
)

validation_tokenized = validation_tokenized.map(
    add_labels,
    batched=True,
    batch_size=5000,
    desc="Creating validation labels",
)

test_tokenized = test_tokenized.map(
    add_labels,
    batched=True,
    batch_size=5000,
    desc="Creating test labels",
)

print("Labels created.")

Creating training labels: 100%|██████████| 630075/630075 [00:00<00:00, 1226209.21 examples/s]
Creating validation labels: 100%|██████████| 78675/78675 [00:00<00:00, 772754.11 examples/s]
Creating test labels: 100%|██████████| 78596/78596 [00:00<00:00, 798410.03 examples/s]

Labels created.

In [92]:
print("Train label distribution:")
print(train_tokenized["labels"].count(0), "SIMPLE")
print(train_tokenized["labels"].count(1), "MULTI_TURN")

print("\nValidation label distribution:")
print(validation_tokenized["labels"].count(0), "SIMPLE")
print(validation_tokenized["labels"].count(1), "MULTI_TURN")

print("\nTest label distribution:")
print(test_tokenized["labels"].count(0), "SIMPLE")
print(test_tokenized["labels"].count(1), "MULTI_TURN")

print("\nUnique label values:")
print(sorted(set(train_tokenized["labels"])))

print("\nExpected mapping:")
print(label2id)
print(id2label)

Train label distribution:
370706 SIMPLE
259369 MULTI_TURN

Validation label distribution:
46253 SIMPLE
32422 MULTI_TURN

Test label distribution:
46202 SIMPLE
32394 MULTI_TURN

Unique label values:
[0, 1]

Expected mapping:
{False: 0, True: 1}
{0: 'SIMPLE', 1: 'MULTI_TURN'}

In [93]:
columns_to_remove = [
    "root_id",
    "text",
    "multi_turn",
    "token_type_ids",
]

train_tokenized = train_tokenized.remove_columns(columns_to_remove)
validation_tokenized = validation_tokenized.remove_columns(columns_to_remove)
test_tokenized = test_tokenized.remove_columns(columns_to_remove)

print("Training columns:", train_tokenized.column_names)
print("Validation columns:", validation_tokenized.column_names)
print("Test columns:", test_tokenized.column_names)

Training columns: ['input_ids', 'attention_mask', 'labels']
Validation columns: ['input_ids', 'attention_mask', 'labels']
Test columns: ['input_ids', 'attention_mask', 'labels']

In [94]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU count:", torch.cuda.device_count())
    print(
        "GPU memory:",
        round(torch.cuda.get_device_properties(0).total_memory / (1024**3), 2),
        "GB",
    )
else:
    print("Training will use CPU.")

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
GPU count: 1
GPU memory: 6.0 GB

In [95]:
from transformers import AutoModelForSequenceClassification

model_name = "distilbert-base-uncased"

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label=id2label,
    label2id={
        "SIMPLE": 0,
        "MULTI_TURN": 1,
    },
)

print("Model:", model_name)
print("Number of labels:", model.config.num_labels)
print("Label mapping:", model.config.id2label)
print("Model device:", next(model.parameters()).device)

c:\Users\danie\anaconda3\envs\supportmind\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\danie\.cache\huggingface\hub\models--distilbert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 100/100 [00:00<00:00, 4217.29it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model: distilbert-base-uncased
Number of labels: 2
Label mapping: {0: 'SIMPLE', 1: 'MULTI_TURN'}
Model device: cpu

In [96]:
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("Total parameters:", f"{total_params:,}")
print("Trainable parameters:", f"{trainable_params:,}")
print(
    "Approx. FP32 model size:",
    round(total_params * 4 / (1024**2), 2),
    "MB",
)

Total parameters: 66,955,010
Trainable parameters: 66,955,010
Approx. FP32 model size: 255.41 MB

In [97]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer,
)

print("Data collator created.")

Data collator created.

In [98]:
sample_batch = train_tokenized.select(range(4))

batch = data_collator(
    [sample_batch[i] for i in range(len(sample_batch))]
)

print("Batch keys:", batch.keys())
print("input_ids shape:", batch["input_ids"].shape)
print("attention_mask shape:", batch["attention_mask"].shape)
print("labels shape:", batch["labels"].shape)
print("labels:", batch["labels"].tolist())
print("Maximum sequence length in batch:", batch["input_ids"].shape[1])

Batch keys: KeysView({'input_ids': tensor([[  101,  1030, 10630,  2581, 16932,  1061,  1521,  2035,  4682,  2055,
          2115,  1523,  2307,  1524,  4434,  1012,  1019,  6963,  8318,  2063,
          1010,  2145,  2180,  1521,  1056,  7170,  2242,  1012, 15488,  2232,
          1012,   102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [  101,  1030, 10630,  2581, 16932,  7188,  1045,  3967,  8013,  2490,
          1010,  2027,  2425,  2033,  1045,  2031,  2460, 16044,  9124,  2006,
          2026,  4070,  1010,  2021,  1045,  2031,  2196,  1999,  1996,  1018,
          2086,  1045,  1005,  2310,  2699, 16770,  1024,  1013,  1013,  1056,
          1012,  2522,  1013,  1014,  2290,  2683,  2620,  5339, 26807,  2361,
          2243,   102],
        [  101, 10930,  1030,  3198,  1035,  8674,  1010,  2115,  8013,  2326,
         16360,  2015,  2024,  3565,  3835,  1517,  2021, 10047,  2863,  2707,
          4440,  8091,  2065,  1061,  1521,  2035,  2123,  1521,  1056,  2131,
          2026,  2326,  2183,   999,   102,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0],
        [  101,  1030,  2310, 21885,  5644,  6279,  6442,  2026,  2767,  2003,
          2302,  4274,  2057,  2342,  2000,  2377,  2678, 26393,  2362,  3531,
          2256,  4813, 11737,  5498,  4095,  2296,  2617,  2302,  4274,  2480,
           102,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0])})
input_ids shape: torch.Size([4, 52])
attention_mask shape: torch.Size([4, 52])
labels shape: torch.Size([4])
labels: [1, 0, 0, 0]
Maximum sequence length in batch: 52

In [99]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary",
        zero_division=0,
    )

    macro_precision, macro_recall, macro_f1, _ = (
        precision_recall_fscore_support(
            labels,
            predictions,
            average="macro",
            zero_division=0,
        )
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision_multi_turn": precision,
        "recall_multi_turn": recall,
        "f1_multi_turn": f1,
        "macro_precision": macro_precision,
        "macro_recall": macro_recall,
        "macro_f1": macro_f1,
    }

print("Evaluation metrics function created.")

Evaluation metrics function created.

In [100]:
test_logits = np.array([
    [2.0, 0.5],   # predicted SIMPLE
    [0.2, 2.5],   # predicted MULTI_TURN
    [1.8, 0.4],   # predicted SIMPLE
    [0.3, 2.1],   # predicted MULTI_TURN
])

test_labels = np.array([0, 1, 0, 1])

test_metrics = compute_metrics((test_logits, test_labels))

print(test_metrics)

{'accuracy': 1.0, 'precision_multi_turn': 1.0, 'recall_multi_turn': 1.0, 'f1_multi_turn': 1.0, 'macro_precision': 1.0, 'macro_recall': 1.0, 'macro_f1': 1.0}

In [101]:
import transformers

from transformers import (
    Trainer,
    TrainingArguments,
)

print("Transformers version:", transformers.__version__)
print("Trainer:", Trainer)
print("TrainingArguments:", TrainingArguments)

Transformers version: 5.13.0
Trainer: <class 'transformers.trainer.Trainer'>
TrainingArguments: <class 'transformers.training_args.TrainingArguments'>

In [102]:
from pathlib import Path

model_output_dir = Path(
    r"C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity"
)

model_output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

print("Model output directory:")
print(model_output_dir)
print("Directory exists:", model_output_dir.exists())

Model output directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity
Directory exists: True

In [107]:
from pathlib import Path
import torch
from transformers import TrainingArguments

# --------------------------------------------------
# Training / checkpoint directories
# --------------------------------------------------

training_output_dir = Path(
    r"C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\training_checkpoints"
)

training_output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

print("Training checkpoint directory:")
print(training_output_dir)

print("\nFinal model directory:")
print(model_output_dir)


# --------------------------------------------------
# Hardware-aware training settings
# --------------------------------------------------

training_args = TrainingArguments(
    output_dir=str(training_output_dir),

    # Training
    num_train_epochs=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_ratio=0.05,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,

    # Evaluation and checkpoints
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,

    # Best model selection
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,

    # Precision
    fp16=torch.cuda.is_available(),
    bf16=False,

    # Logging
    logging_strategy="steps",
    logging_steps=500,

    # Reproducibility
    seed=42,
    data_seed=42,

    # Performance
    dataloader_num_workers=2,
    dataloader_pin_memory=torch.cuda.is_available(),

    # Reporting
    report_to="none",

    # Run name
    run_name="supportmind_conversation_complexity_distilbert",
)

print("\nTrainingArguments created successfully.\n")

print("Train batch size per GPU:",
      training_args.per_device_train_batch_size)

print("Gradient accumulation steps:",
      training_args.gradient_accumulation_steps)

print(
    "Effective train batch size:",
    training_args.per_device_train_batch_size
    * training_args.gradient_accumulation_steps
)

print("FP16 enabled:", training_args.fp16)
print("Epochs:", training_args.num_train_epochs)
print("Learning rate:", training_args.learning_rate)
print("Evaluation strategy:", training_args.eval_strategy)
print("Save strategy:", training_args.save_strategy)
print("Best model metric:", training_args.metric_for_best_model)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Training checkpoint directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\training_checkpoints

Final model directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=1.1.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=1.1.0'`

In [108]:
import importlib
import transformers.utils.import_utils as import_utils

importlib.reload(import_utils)

print("Accelerate version:", accelerate.__version__)
print(
    "Transformers sees Accelerate:",
    import_utils.is_accelerate_available(),
)
print(
    "Detected Accelerate version:",
    import_utils._accelerate_version,
)

Accelerate version: 1.15.0
Transformers sees Accelerate: True

AttributeError: module 'transformers.utils.import_utils' has no attribute '_accelerate_version'

In [109]:
training_args = TrainingArguments(
    output_dir=str(training_output_dir),

    # Training
    num_train_epochs=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_ratio=0.05,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,

    # Evaluation and checkpoints
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,

    # Best model selection
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,

    # Precision
    fp16=torch.cuda.is_available(),
    bf16=False,

    # Logging
    logging_strategy="steps",
    logging_steps=500,

    # Reproducibility
    seed=42,
    data_seed=42,

    # Performance
    dataloader_num_workers=2,
    dataloader_pin_memory=torch.cuda.is_available(),

    # Reporting
    report_to="none",

    # Run name
    run_name="supportmind_conversation_complexity_distilbert",
)

print("TrainingArguments created successfully.")
print("Train batch size:", training_args.per_device_train_batch_size)
print("Gradient accumulation:", training_args.gradient_accumulation_steps)
print(
    "Effective batch size:",
    training_args.per_device_train_batch_size
    * training_args.gradient_accumulation_steps,
)
print("FP16:", training_args.fp16)
print("Epochs:", training_args.num_train_epochs)
print("Learning rate:", training_args.learning_rate)
print("Best metric:", training_args.metric_for_best_model)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=1.1.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=1.1.0'`

In [110]:
from pathlib import Path

tokenized_dataset_dir = Path(
    r"C:\Users\danie\supportmind-ai\data\processed\conversation_intelligence\tokenized"
)

tokenized_dataset_dir.mkdir(
    parents=True,
    exist_ok=True,
)

train_tokenized.save_to_disk(
    str(tokenized_dataset_dir / "train")
)

validation_tokenized.save_to_disk(
    str(tokenized_dataset_dir / "validation")
)

test_tokenized.save_to_disk(
    str(tokenized_dataset_dir / "test")
)

print("Tokenized datasets saved successfully.")
print("Location:", tokenized_dataset_dir)

Saving the dataset (1/1 shards): 100%|██████████| 630075/630075 [00:00<00:00, 808999.43 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 78675/78675 [00:00<00:00, 771103.65 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 78596/78596 [00:00<00:00, 1220471.73 examples/s]

Tokenized datasets saved successfully.
Location: C:\Users\danie\supportmind-ai\data\processed\conversation_intelligence\tokenized

In [1]:
from pathlib import Path
from datasets import load_from_disk

tokenized_dataset_dir = Path(
    r"C:\Users\danie\supportmind-ai\data\processed\conversation_intelligence\tokenized"
)

train_tokenized = load_from_disk(
    str(tokenized_dataset_dir / "train")
)

validation_tokenized = load_from_disk(
    str(tokenized_dataset_dir / "validation")
)

test_tokenized = load_from_disk(
    str(tokenized_dataset_dir / "test")
)

print("Tokenized datasets restored.")
print("Train:", len(train_tokenized))
print("Validation:", len(validation_tokenized))
print("Test:", len(test_tokenized))

c:\Users\danie\anaconda3\envs\supportmind\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Tokenized datasets restored.
Train: 630075
Validation: 78675
Test: 78596

In [2]:
from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(
    model_name
)

print("Tokenizer restored.")
print("Model:", model_name)
print("Tokenizer:", tokenizer.__class__.__name__)

Tokenizer restored.
Model: distilbert-base-uncased
Tokenizer: BertTokenizer

In [3]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

print("Data collator restored.")

Data collator restored.

In [4]:
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="binary",
        zero_division=0,
    )

    macro_precision, macro_recall, macro_f1, _ = (
        precision_recall_fscore_support(
            labels,
            predictions,
            average="macro",
            zero_division=0,
        )
    )

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
        "precision_multi_turn": precision,
        "recall_multi_turn": recall,
        "f1_multi_turn": f1,
        "macro_precision": macro_precision,
        "macro_recall": macro_recall,
        "macro_f1": macro_f1,
    }

print("Evaluation metrics restored.")

Evaluation metrics restored.

In [5]:
from transformers import AutoModelForSequenceClassification

label2id = {
    "SIMPLE": 0,
    "MULTI_TURN": 1,
}

id2label = {
    0: "SIMPLE",
    1: "MULTI_TURN",
}

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
)

print("Model restored.")
print("Labels:", model.config.id2label)
print(
    "Trainable parameters:",
    f"{sum(p.numel() for p in model.parameters()):,}"
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1983.87it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model restored.
Labels: {0: 'SIMPLE', 1: 'MULTI_TURN'}
Trainable parameters: 66,955,010

In [6]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "VRAM:",
        round(
            torch.cuda.get_device_properties(0).total_memory
            / (1024**3),
            2,
        ),
        "GB",
    )

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
VRAM: 6.0 GB

In [7]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=r"C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\training_checkpoints",
    num_train_epochs=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_ratio=0.05,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,

    fp16=True,

    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,

    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,

    logging_steps=500,

    seed=42,
    data_seed=42,

    dataloader_num_workers=2,
    dataloader_pin_memory=True,

    report_to="none",

    run_name="supportmind_conversation_complexity_distilbert",
)

print("TrainingArguments created successfully.")
print("Epochs:", training_args.num_train_epochs)
print("Train batch size:", training_args.per_device_train_batch_size)
print("Eval batch size:", training_args.per_device_eval_batch_size)
print("Gradient accumulation:", training_args.gradient_accumulation_steps)
print("FP16:", training_args.fp16)
print("Evaluation:", training_args.eval_strategy)
print("Save strategy:", training_args.save_strategy)
print("Best metric:", training_args.metric_for_best_model)

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

TrainingArguments created successfully.
Epochs: 2
Train batch size: 16
Eval batch size: 32
Gradient accumulation: 2
FP16: True
Evaluation: IntervalStrategy.EPOCH
Save strategy: SaveStrategy.EPOCH
Best metric: macro_f1

In [8]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=r"C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\training_checkpoints",

    num_train_epochs=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=1970,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=2,

    fp16=True,

    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,

    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,

    logging_steps=500,

    seed=42,
    data_seed=42,

    dataloader_num_workers=2,
    dataloader_pin_memory=True,

    report_to="none",

    run_name="supportmind_conversation_complexity_distilbert",
)

print("TrainingArguments finalized successfully.")
print("Warmup steps:", training_args.warmup_steps)
print("Epochs:", training_args.num_train_epochs)
print("Effective batch size:", 16 * 2)
print("FP16:", training_args.fp16)
print("Evaluation:", training_args.eval_strategy)
print("Best metric:", training_args.metric_for_best_model)

TrainingArguments finalized successfully.
Warmup steps: 1970
Epochs: 2
Effective batch size: 32
FP16: True
Evaluation: IntervalStrategy.EPOCH
Best metric: macro_f1

In [9]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=train_tokenized,
    eval_dataset=validation_tokenized,

    processing_class=tokenizer,
    data_collator=data_collator,

    compute_metrics=compute_metrics,
)

print("Trainer created successfully.")
print("Training examples:", len(trainer.train_dataset))
print("Validation examples:", len(trainer.eval_dataset))
print("Model device:", next(trainer.model.parameters()).device)

Trainer created successfully.
Training examples: 630075
Validation examples: 78675
Model device: cuda:0

In [10]:
import torch

print("Before smoke test:")
print("GPU:", torch.cuda.get_device_name(0))
print(
    "Allocated:",
    round(torch.cuda.memory_allocated() / (1024**2), 2),
    "MB"
)
print(
    "Reserved:",
    round(torch.cuda.memory_reserved() / (1024**2), 2),
    "MB"
)

# Take only a tiny batch for pipeline validation.
smoke_test_dataset = train_tokenized.select(range(32))

print("\nRunning smoke test on 32 examples...")

smoke_output = trainer.evaluate(
    eval_dataset=smoke_test_dataset,
)

print("\nSmoke test completed successfully.")
print("Metrics:")
for key, value in smoke_output.items():
    print(f"{key}: {value}")

Before smoke test:
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Allocated: 256.5 MB
Reserved: 292.0 MB

Running smoke test on 32 examples...

Smoke test completed successfully.
Metrics:
eval_loss: 0.701202392578125
eval_accuracy: 0.375
eval_precision_multi_turn: 0.4
eval_recall_multi_turn: 0.8571428571428571
eval_f1_multi_turn: 0.5454545454545454
eval_macro_precision: 0.2
eval_macro_recall: 0.42857142857142855
eval_macro_f1: 0.2727272727272727

In [11]:
print("=" * 60)
print("STARTING FULL SUPPORTMIND TRAINING")
print("=" * 60)

print(f"Training examples : {len(train_tokenized):,}")
print(f"Validation examples: {len(validation_tokenized):,}")
print(f"Epochs             : {training_args.num_train_epochs}")
print(f"Learning rate      : {training_args.learning_rate}")
print(f"Effective batch    : {16 * 2}")
print(f"FP16               : {training_args.fp16}")
print(f"GPU                : {torch.cuda.get_device_name(0)}")

print("=" * 60)
print("Training started...")
print("=" * 60)

train_result = trainer.train()

print("=" * 60)
print("FULL TRAINING COMPLETED")
print("=" * 60)

print("Training metrics:")
for key, value in train_result.metrics.items():
    print(f"{key}: {value}")

============================================================
STARTING FULL SUPPORTMIND TRAINING
============================================================
Training examples : 630,075
Validation examples: 78,675
Epochs             : 2
Learning rate      : 2e-05
Effective batch    : 32
FP16               : True
GPU                : NVIDIA GeForce RTX 3050 6GB Laptop GPU
============================================================
Training started...
============================================================

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.89it/s]
Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.83it/s]

============================================================
FULL TRAINING COMPLETED
============================================================
Training metrics:
train_runtime: 7065.962
train_samples_per_second: 178.341
train_steps_per_second: 5.573
total_flos: 2.1717293159746176e+16
train_loss: 1.2543007474311298
epoch: 2.0

In [12]:
print("=" * 60)
print("FINAL TEST SET EVALUATION")
print("=" * 60)

print(f"Test examples: {len(test_tokenized):,}")

test_results = trainer.evaluate(
    eval_dataset=test_tokenized,
)

print("\nTest metrics:")
for key, value in test_results.items():
    print(f"{key}: {value}")

print("=" * 60)
print("TEST EVALUATION COMPLETED")
print("=" * 60)

============================================================
FINAL TEST SET EVALUATION
============================================================
Test examples: 78,596

Test metrics:
eval_loss: 0.6263986825942993
eval_accuracy: 0.6494987022240317
eval_precision_multi_turn: 0.612582473747793
eval_recall_multi_turn: 0.406988948570723
eval_f1_multi_turn: 0.4890570517100675
eval_macro_precision: 0.6380009470746884
eval_macro_recall: 0.6132602852892142
eval_macro_f1: 0.6111577523936293
============================================================
TEST EVALUATION COMPLETED
============================================================

In [13]:
# ============================================================
# STEP 47 — CONFUSION MATRIX + CLASSIFICATION REPORT
# ============================================================

import numpy as np
import pandas as pd

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
)

print("=" * 60)
print("STEP 47 — TEST SET ERROR ANALYSIS")
print("=" * 60)

print(f"Test examples: {len(test_tokenized):,}")

# ------------------------------------------------------------
# 1. Get predictions from the locked test set
# ------------------------------------------------------------

test_prediction_output = trainer.predict(test_tokenized)

test_logits = test_prediction_output.predictions
test_labels = test_prediction_output.label_ids

test_predictions = np.argmax(
    test_logits,
    axis=-1,
)

print("\nPredictions generated successfully.")

print(f"Logits shape:       {test_logits.shape}")
print(f"Labels shape:       {test_labels.shape}")
print(f"Predictions shape:  {test_predictions.shape}")


# ------------------------------------------------------------
# 2. Confusion matrix
# ------------------------------------------------------------

cm = confusion_matrix(
    test_labels,
    test_predictions,
    labels=[0, 1],
)

print("\n" + "=" * 60)
print("CONFUSION MATRIX")
print("=" * 60)

cm_df = pd.DataFrame(
    cm,
    index=["Actual SIMPLE", "Actual MULTI_TURN"],
    columns=["Predicted SIMPLE", "Predicted MULTI_TURN"],
)

print(cm_df)


# ------------------------------------------------------------
# 3. Classification report
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

report = classification_report(
    test_labels,
    test_predictions,
    labels=[0, 1],
    target_names=["SIMPLE", "MULTI_TURN"],
    digits=4,
    zero_division=0,
)

print(report)


# ------------------------------------------------------------
# 4. Explicit error counts
# ------------------------------------------------------------

true_simple = (test_labels == 0)
true_multi = (test_labels == 1)

pred_simple = (test_predictions == 0)
pred_multi = (test_predictions == 1)

true_negatives = np.sum(true_simple & pred_simple)
false_positives = np.sum(true_simple & pred_multi)
false_negatives = np.sum(true_multi & pred_simple)
true_positives = np.sum(true_multi & pred_multi)

print("=" * 60)
print("ERROR COUNTS")
print("=" * 60)

print(f"True Negatives  (SIMPLE → SIMPLE):      {true_negatives:,}")
print(f"False Positives (SIMPLE → MULTI_TURN):  {false_positives:,}")
print(f"False Negatives (MULTI_TURN → SIMPLE):  {false_negatives:,}")
print(f"True Positives  (MULTI_TURN → MULTI_TURN): {true_positives:,}")


# ------------------------------------------------------------
# 5. Sanity check
# ------------------------------------------------------------

total_predictions = (
    true_negatives
    + false_positives
    + false_negatives
    + true_positives
)

print("\n" + "=" * 60)
print("SANITY CHECK")
print("=" * 60)

print(f"Total confusion-matrix samples: {total_predictions:,}")
print(f"Expected test samples:          {len(test_tokenized):,}")

assert total_predictions == len(test_tokenized)

print("Sanity check: PASSED")
print("=" * 60)
print("STEP 47 COMPLETED")
print("=" * 60)

============================================================
STEP 47 — TEST SET ERROR ANALYSIS
============================================================
Test examples: 78,596

Predictions generated successfully.
Logits shape:       (78596, 2)
Labels shape:       (78596,)
Predictions shape:  (78596,)

============================================================
CONFUSION MATRIX
============================================================
                   Predicted SIMPLE  Predicted MULTI_TURN
Actual SIMPLE                 37864                  8338
Actual MULTI_TURN             19210                 13184

============================================================
CLASSIFICATION REPORT
============================================================
              precision    recall  f1-score   support

      SIMPLE     0.6634    0.8195    0.7333     46202
  MULTI_TURN     0.6126    0.4070    0.4891     32394

    accuracy                         0.6495     78596
   macro avg     0.6380    0.6133    0.6112     78596
weighted avg     0.6425    0.6495    0.6326     78596

============================================================
ERROR COUNTS
============================================================
True Negatives  (SIMPLE → SIMPLE):      37,864
False Positives (SIMPLE → MULTI_TURN):  8,338
False Negatives (MULTI_TURN → SIMPLE):  19,210
True Positives  (MULTI_TURN → MULTI_TURN): 13,184

============================================================
SANITY CHECK
============================================================
Total confusion-matrix samples: 78,596
Expected test samples:          78,596
Sanity check: PASSED
============================================================
STEP 47 COMPLETED
============================================================

In [14]:
# ============================================================
# STEP 48 — SAVE FINAL CONVERSATION COMPLEXITY MODEL
# ============================================================

from pathlib import Path

final_model_dir = Path(
    r"C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity"
)

final_model_dir.mkdir(
    parents=True,
    exist_ok=True,
)

print("=" * 60)
print("STEP 48 — SAVING FINAL MODEL")
print("=" * 60)

print(f"Output directory:\n{final_model_dir}")

# ------------------------------------------------------------
# 1. Save model
# ------------------------------------------------------------

trainer.save_model(
    str(final_model_dir)
)

print("\nModel saved successfully.")

# ------------------------------------------------------------
# 2. Save tokenizer
# ------------------------------------------------------------

tokenizer.save_pretrained(
    str(final_model_dir)
)

print("Tokenizer saved successfully.")

# ------------------------------------------------------------
# 3. Inspect saved files
# ------------------------------------------------------------

saved_files = sorted(
    path.name
    for path in final_model_dir.iterdir()
    if path.is_file()
)

print("\nSaved files:")

for filename in saved_files:
    print(f"  - {filename}")

print("\n" + "=" * 60)
print("STEP 48 COMPLETED")
print("=" * 60)

============================================================
STEP 48 — SAVING FINAL MODEL
============================================================
Output directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.08it/s]

Model saved successfully.
Tokenizer saved successfully.

Saved files:
  - config.json
  - model.safetensors
  - tokenizer.json
  - tokenizer_config.json
  - training_args.bin

============================================================
STEP 48 COMPLETED
============================================================

In [1]:
# ============================================================
# STEP 49 — RELOAD SAVED MODEL + INFERENCE VERIFICATION
# ============================================================

import numpy as np
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
)

print("=" * 60)
print("STEP 49 — SAVED MODEL RELOAD VERIFICATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Define final model directory
# ------------------------------------------------------------

final_model_dir = (
    r"C:\Users\danie\supportmind-ai\backend\app\nlp"
    r"\conversation_intelligence\models"
    r"\supportmind_conversation_complexity"
)

print(f"Model directory:\n{final_model_dir}")


# ------------------------------------------------------------
# 2. Reload tokenizer independently
# ------------------------------------------------------------

reloaded_tokenizer = AutoTokenizer.from_pretrained(
    final_model_dir
)

print("\nTokenizer reloaded successfully.")
print(f"Tokenizer class: {reloaded_tokenizer.__class__.__name__}")
print(f"Vocabulary size: {reloaded_tokenizer.vocab_size}")


# ------------------------------------------------------------
# 3. Reload model independently
# ------------------------------------------------------------

reloaded_model = AutoModelForSequenceClassification.from_pretrained(
    final_model_dir
)

print("\nModel reloaded successfully.")
print(f"Model class: {reloaded_model.__class__.__name__}")
print(f"Number of labels: {reloaded_model.config.num_labels}")
print(f"Label mapping: {reloaded_model.config.id2label}")


# ------------------------------------------------------------
# 4. Move model to the available device
# ------------------------------------------------------------

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

reloaded_model.to(device)
reloaded_model.eval()

print(f"\nInference device: {device}")


# ------------------------------------------------------------
# 5. Test with real customer messages
# ------------------------------------------------------------

test_messages = [
    "I have been waiting for my order and still haven't received it.",
    "Can you please help me fix this issue?",
    "My account has been locked and I cannot log in.",
    "I just wanted to say thank you for your help.",
]


inputs = reloaded_tokenizer(
    test_messages,
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="pt",
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}


# ------------------------------------------------------------
# 6. Run inference
# ------------------------------------------------------------

with torch.no_grad():
    outputs = reloaded_model(**inputs)

logits = outputs.logits

probabilities = torch.softmax(
    logits,
    dim=-1,
)

predictions = torch.argmax(
    probabilities,
    dim=-1,
)


# ------------------------------------------------------------
# 7. Display predictions
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("INFERENCE RESULTS")
print("=" * 60)

for message, prediction, probability in zip(
    test_messages,
    predictions.cpu().numpy(),
    probabilities.cpu().numpy(),
):

    label = reloaded_model.config.id2label[
        int(prediction)
    ]

    confidence = float(
        probability[int(prediction)]
    )

    print(f"\nMessage:")
    print(f"  {message}")

    print(f"Prediction:")
    print(f"  {label}")

    print(f"Confidence:")
    print(f"  {confidence:.4f}")


# ------------------------------------------------------------
# 8. Verify output shape
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("OUTPUT VALIDATION")
print("=" * 60)

print(f"Logits shape:        {tuple(logits.shape)}")
print(f"Probabilities shape: {tuple(probabilities.shape)}")
print(f"Predictions shape:   {tuple(predictions.shape)}")

assert logits.shape == (len(test_messages), 2)
assert probabilities.shape == (len(test_messages), 2)
assert predictions.shape == (len(test_messages),)

print("\nOutput shape validation: PASSED")


# ------------------------------------------------------------
# 9. Verify probability sums
# ------------------------------------------------------------

probability_sums = probabilities.sum(
    dim=-1
).cpu().numpy()

print("\nProbability sums:")

for index, value in enumerate(probability_sums):
    print(f"  Message {index + 1}: {value:.6f}")

assert np.allclose(
    probability_sums,
    1.0,
    atol=1e-6,
)

print("Probability validation: PASSED")


# ------------------------------------------------------------
# Final status
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 49 COMPLETED")
print("Saved model can be independently reloaded.")
print("=" * 60)

c:\Users\danie\anaconda3\envs\supportmind\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

============================================================
STEP 49 — SAVED MODEL RELOAD VERIFICATION
============================================================
Model directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\conversation_intelligence\models\supportmind_conversation_complexity

Tokenizer reloaded successfully.
Tokenizer class: BertTokenizer
Vocabulary size: 30522

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 8001.02it/s]

Model reloaded successfully.
Model class: DistilBertForSequenceClassification
Number of labels: 2
Label mapping: {0: 'SIMPLE', 1: 'MULTI_TURN'}

Inference device: cuda

============================================================
INFERENCE RESULTS
============================================================

Message:
  I have been waiting for my order and still haven't received it.
Prediction:
  MULTI_TURN
Confidence:
  0.9800

Message:
  Can you please help me fix this issue?
Prediction:
  MULTI_TURN
Confidence:
  0.9896

Message:
  My account has been locked and I cannot log in.
Prediction:
  MULTI_TURN
Confidence:
  0.9821

Message:
  I just wanted to say thank you for your help.
Prediction:
  MULTI_TURN
Confidence:
  0.9797

============================================================
OUTPUT VALIDATION
============================================================
Logits shape:        (4, 2)
Probabilities shape: (4, 2)
Predictions shape:   (4,)

Output shape validation: PASSED

Probability sums:
  Message 1: 1.000000
  Message 2: 1.000000
  Message 3: 1.000000
  Message 4: 1.000000
Probability validation: PASSED

============================================================
STEP 49 COMPLETED
Saved model can be independently reloaded.
============================================================