In [1]:
print("hello world")

hello world

In [3]:
from pathlib import Path
import pandas as pd

# --------------------------------------------------
# Project and dataset paths
# --------------------------------------------------

PROJECT_ROOT = Path(r"C:\Users\danie\supportmind-ai")

DATA_PATH = (
    PROJECT_ROOT
    / "rawsupportminddata"
    / "final clean Customer Support Ticket Dataset"
    / "supportmind_final_clean_dataset.csv"
)

print("Dataset path:")
print(DATA_PATH)

print("\nFile exists:", DATA_PATH.exists())

# --------------------------------------------------
# Load dataset
# --------------------------------------------------

df = pd.read_csv(DATA_PATH)

print("\nDataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
# --------------------------------------------------
# 2. Inspect topic-modeling text columns
# --------------------------------------------------
TEXT_COLUMNS = [
    "Ticket Type",
    "Ticket Subject",
    "Ticket Description",
    "Resolution"
]

print("\n" + "=" * 70)
print("TEXT COLUMN ANALYSIS")
print("=" * 70)

for column in TEXT_COLUMNS:
    print(f"\n--- {column} ---")
    print("Missing values:", df[column].isna().sum())
    print("Non-null values:", df[column].notna().sum())
    print("Unique values:", df[column].nunique())

    print("\nSample values:")
    print(df[column].dropna().head(5).to_string(index=False))


# --------------------------------------------------
# 3. Analyze Ticket Type and Ticket Subject distributions
# --------------------------------------------------
print("\n" + "=" * 70)
print("TICKET TYPE DISTRIBUTION")
print("=" * 70)
print(df["Ticket Type"].value_counts(dropna=False))


print("\n" + "=" * 70)
print("TOP 20 TICKET SUBJECTS")
print("=" * 70)
print(df["Ticket Subject"].value_counts(dropna=False).head(20))


# --------------------------------------------------
# 4. Analyze Ticket Description quality
# --------------------------------------------------
descriptions = df["Ticket Description"].dropna().astype(str)

print("\n" + "=" * 70)
print("TICKET DESCRIPTION ANALYSIS")
print("=" * 70)

print("Total non-null descriptions:", len(descriptions))
print("Empty/whitespace descriptions:",
      descriptions.str.strip().eq("").sum())

description_lengths = descriptions.str.len()
word_counts = descriptions.str.split().str.len()

print("\nCharacter length statistics:")
print(description_lengths.describe())

print("\nWord count statistics:")
print(word_counts.describe())


# --------------------------------------------------
# 5. Check exact duplicate descriptions
# --------------------------------------------------
print("\n" + "=" * 70)
print("DUPLICATE ANALYSIS")
print("=" * 70)

print(
    "Exact duplicate Ticket Descriptions:",
    descriptions.duplicated().sum()
)

print(
    "Duplicate rows based on Ticket Subject + Ticket Description:",
    df.duplicated(
        subset=["Ticket Subject", "Ticket Description"]
    ).sum()
)


# --------------------------------------------------
# 6. Inspect random examples
# --------------------------------------------------
print("\n" + "=" * 70)
print("RANDOM TICKET EXAMPLES")
print("=" * 70)

sample_columns = [
    "Ticket Type",
    "Ticket Subject",
    "Ticket Description"
]

print(
    df[sample_columns]
    .sample(10, random_state=42)
    .to_string(index=False)
)

Dataset path:
C:\Users\danie\supportmind-ai\rawsupportminddata\final clean Customer Support Ticket Dataset\supportmind_final_clean_dataset.csv

File exists: True

Dataset shape: (8469, 17)

Columns:
['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

======================================================================
TEXT COLUMN ANALYSIS
======================================================================

--- Ticket Type ---
Missing values: 0
Non-null values: 8469
Unique values: 5

Sample values:
Technical issue
Technical issue
Technical issue
Billing inquiry
Billing inquiry

--- Ticket Subject ---
Missing values: 0
Non-null values: 8469
Unique values: 16

Sample values:
           Product setup
Peripheral compatibility
         Network problem
          Account access
               Data loss

--- Ticket Description ---
Missing values: 0
Non-null values: 8469
Unique values: 8396

Sample values:
I'm having an issue with the GoPro Hero. Please...
I'm having an issue with the LG Smart TV. Pleas...
I'm facing a problem with my Dell XPS. The Dell...
I'm having an issue with the Microsoft Office. ...
I'm having an issue with the Autodesk AutoCAD. ...

--- Resolution ---
Missing values: 8469
Non-null values: 0
Unique values: 0

Sample values:
Series([], )

======================================================================
TICKET TYPE DISTRIBUTION
======================================================================
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

======================================================================
TOP 20 TICKET SUBJECTS
======================================================================
Ticket Subject
Refund request              576
Software bug                574
Product compatibility       567
Delivery problem            561
Hardware issue              547
Battery life                542
Network problem             539
Installation support        530
Product setup               529
Payment issue               526
Product recommendation      517
Account access              509
Peripheral compatibility    496
Data loss                   491
Cancellation request        487
Display issue               478
Name: count, dtype: int64

======================================================================
TICKET DESCRIPTION ANALYSIS
======================================================================
Total non-null descriptions: 8469
Empty/whitespace descriptions: 0

Character length statistics:
count    8469.000000
mean      278.834573
std        45.816406
min        64.000000
25%       259.000000
50%       288.000000
75%       309.000000
max       402.000000
Name: Ticket Description, dtype: float64

Word count statistics:
count    8469.000000
mean       48.510332
std         8.713261
min        10.000000
25%        45.000000
50%        51.000000
75%        55.000000
max        67.000000
Name: Ticket Description, dtype: float64

======================================================================
DUPLICATE ANALYSIS
======================================================================
Exact duplicate Ticket Descriptions: 73
Duplicate rows based on Ticket Subject + Ticket Description: 6

======================================================================
RANDOM TICKET EXAMPLES
======================================================================
    Ticket Type           Ticket Subject                                                                                                                                                                                                                                                                                                                              Ticket Description
 Refund request            Product setup                                            I'm having an issue with the Roomba Robot Vacuum. Please assist. I'm using xda-developer for something different. If there are issues with the Roomba Robot Vacuum it's likely you are not using the I've tried clearing the cache and data for the Roomba Robot Vacuum app, but the issue persists.
Product inquiry             Battery life                   I'm having trouble connecting my Roomba Robot Vacuum to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. What can be done to resolve this issue? I will refer to this issue I've checked for any available software updates for my Roomba Robot Vacuum, but there are none.
Billing inquiry           Refund request                                                                                                                                       I'm having an issue with the Philips Hue Lights. Please assist. Please give credit to: @joeyclay I'm concerned about the security of my Philips Hue Lights and would like to ensure that my data is safe.
Billing inquiry Peripheral compatibility                             I'm having an issue with the LG OLED. Please assist. 4. Check and compare product pricing You will see that prices are based on the current prices on your credit card. If you are a resident of I've noticed a peculiar error message popping up on my LG OLED screen. It says '[PLACEHOLDER]'. What does it mean?
 Refund request Peripheral compatibility                                                      I'm having an issue with the Roomba Robot Vacuum. Please assist. I would like my price to rise so that I can return it. Please notify me if you do not want their refund. Please do I've noticed a sudden decrease in battery life on my Roomba Robot Vacuum. It used to last much longer.
 Refund request           Refund request I've encountered a data loss issue with my Sony PlayStation. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? I cannot verify this information though. It doesn't look very I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.
Product inquiry             Software bug                                                                                                                                                           I'm having an issue with the Sony 4K HDR TV. Please assist. I've noticed a peculiar error message popping up on my Sony 4K HDR TV screen. It says '[PLACEHOLDER]'. What does it mean?
 Refund request     Installation support                                                                             I'm having an issue with the Xbox. Please assist. If you are having trouble with your package you need to contact customer service with the following: Website P.O. Box 300 I've noticed a sudden decrease in battery life on my Xbox. It used to last much longer.
 Refund request           Hardware issue    I'm encountering a software bug in the Microsoft Office. Whenever I try to perform a specific action, the application crashes. Are there any updates or fixes available? Will my account get frozen in order to save money? Is my password I've checked for software updates, and my Microsoft Office is already running the latest version.
Product inquiry             Battery life                                                                                                                                                                          I'm having an issue with the Canon EOS. Please assist. Thanks, and thanks a lot, I've tried clearing the cache and data for the Canon EOS app, but the issue persists.

In [4]:
# ============================================================
# EDA STEP 2 — Inspect Ticket Description Structure
# ============================================================

import re
from collections import Counter

text = df["Ticket Description"].astype(str)


# ------------------------------------------------------------
# 1. Common sentence / phrase patterns
# ------------------------------------------------------------
print("=" * 70)
print("COMMON DESCRIPTION PHRASES")
print("=" * 70)

words = re.findall(r"\b[a-zA-Z][a-zA-Z'-]*\b", " ".join(text).lower())

word_counts = Counter(words)

print("\nTop 30 words:")
for word, count in word_counts.most_common(30):
    print(f"{word:<20} {count}")


# ------------------------------------------------------------
# 2. Potential boilerplate phrases
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("COMMON SENTENCE STARTS / PHRASES")
print("=" * 70)

phrase_patterns = [
    r"^I'm having an issue with",
    r"^I'm facing a problem with",
    r"^I'm having trouble",
    r"^I've noticed",
    r"^I've encountered",
    r"^I would like",
    r"^Please",
    r"^I'm concerned",
    r"^Thanks",
    r"^I cannot",
    r"^Will my",
    r"^I've tried",
    r"^I've checked",
]

for pattern in phrase_patterns:
    matches = text.str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{pattern:<45} {matches}")


# ------------------------------------------------------------
# 3. Placeholder / URL / email / @mention / number signals
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SPECIAL CONTENT SIGNALS")
print("=" * 70)

patterns = {
    "Placeholder [PLACEHOLDER]": r"\[PLACEHOLDER\]",
    "URLs": r"https?://|www\.",
    "Email addresses": r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
    "@mentions": r"@[A-Za-z0-9_]+",
    "Numbers": r"\b\d+(?:[.,]\d+)?\b",
    "Currency symbols": r"[$€£₹]",
}

for name, pattern in patterns.items():
    matches = text.str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    percentage = matches / len(text) * 100

    print(f"{name:<30} {matches:>5} ({percentage:>6.2f}%)")


# ------------------------------------------------------------
# 4. Very short / very long descriptions
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("EXTREME LENGTH EXAMPLES")
print("=" * 70)

word_count = text.str.split().str.len()

print("\nShortest 10 descriptions:")
print(
    df.loc[word_count.nsmallest(10).index,
           ["Ticket Subject", "Ticket Description"]]
    .to_string(index=False)
)

print("\nLongest 10 descriptions:")
print(
    df.loc[word_count.nlargest(10).index,
           ["Ticket Subject", "Ticket Description"]]
    .to_string(index=False)
)


# ------------------------------------------------------------
# 5. Compare Subject vs Description vocabulary
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SUBJECT / DESCRIPTION VOCABULARY")
print("=" * 70)

subject_words = set(
    re.findall(
        r"\b[a-zA-Z][a-zA-Z'-]*\b",
        " ".join(df["Ticket Subject"].astype(str)).lower()
    )
)

description_words = set(words)

overlap = subject_words & description_words

print("Unique subject words:", len(subject_words))
print("Unique description words:", len(description_words))
print("Vocabulary overlap:", len(overlap))

print("\nSubject vocabulary:")
print(sorted(subject_words))


# ------------------------------------------------------------
# 6. Subject + description examples
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SUBJECT vs DESCRIPTION — 20 RANDOM EXAMPLES")
print("=" * 70)

print(
    df[["Ticket Subject", "Ticket Description"]]
    .sample(20, random_state=123)
    .to_string(index=False)
)

======================================================================
COMMON DESCRIPTION PHRASES
======================================================================

Top 30 words:
the                  26430
issue                11527
to                   10806
i'm                  10292
my                   9591
please               8815
with                 8326
it                   7460
an                   7251
a                    6850
having               6430
assist               6258
and                  6020
i've                 6001
i                    5991
is                   5666
you                  4446
but                  4384
this                 4354
on                   3922
in                   3342
for                  3150
of                   2750
be                   2736
that                 2579
problem              2284
not                  2282
can                  2271
if                   2263
product              2180

======================================================================
COMMON SENTENCE STARTS / PHRASES
======================================================================
^I'm having an issue with                     5868
^I'm facing a problem with                    179
^I'm having trouble                           178
^I've noticed                                 179
^I've encountered                             164
^I would like                                 0
^Please                                       0
^I'm concerned                                0
^Thanks                                       0
^I cannot                                     0
^Will my                                      0
^I've tried                                   0
^I've checked                                 0

======================================================================
SPECIAL CONTENT SIGNALS
======================================================================
Placeholder [PLACEHOLDER]        676 (  7.98%)
URLs                               7 (  0.08%)
Email addresses                   73 (  0.86%)
@mentions                        196 (  2.31%)
Numbers                         1894 ( 22.36%)
Currency symbols                 434 (  5.12%)

======================================================================
EXTREME LENGTH EXAMPLES
======================================================================

Shortest 10 descriptions:
        Ticket Subject                                                                                                                                 Ticket Description
         Payment issue                                                                                   I'm having an issue with the Xbox. Please assist. [CODE_REMOVED]
  Cancellation request                                                            I'm having an issue with the Microsoft Xbox Controller. Please assist. " [CODE_REMOVED]
Product recommendation                                                              I'm having an issue with the LG OLED. Please assist. " ) [PLACEHOLDER] [CODE_REMOVED]
         Product setup                              I'm having an issue with the Asus ROG. Please assist. Thank you. I appreciate your time. return export [CODE_REMOVED]
        Refund request        I'm having an issue with the Xbox. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.
      Delivery problem I'm having an issue with the PlayStation. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.
          Battery life I'm having an issue with the HP Pavilion. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.
         Payment issue I'm having an issue with the Google Nest. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.
 Product compatibility     I'm having an issue with the Nikon D. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.
  Installation support    I'm having an issue with the PlayStation. Please assist. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

Longest 10 descriptions:
          Ticket Subject                                                                                                                                                                                                                                                                                                                                                                          Ticket Description
         Network problem                         I'm having an issue with the Sony 4K HDR TV. Please assist. If the product is an Xbox One and you have purchased a Kinect headset or a digital image that you wouldn't want to be copied by other devices, please contact me I've recently updated the firmware of my Sony 4K HDR TV, and the issue started happening afterward. Could it be related to the update?
          Refund request       I'm having an issue with the Nintendo Switch Pro Controller. Please assist. You can also tell me if your item will be shipping with a standard quote that will be charged to your credit address by either using PayPal or calling 1- I'm unable to find the option to perform the desired action in the Nintendo Switch Pro Controller. Could you please guide me through the steps?
            Software bug     I've accidentally deleted important data from my Microsoft Xbox Controller. Is there any way to recover the deleted files? I need them urgently. I know that they were sent to me as stolen material and are the originals. No one would get I'm unable to find the option to perform the desired action in the Microsoft Xbox Controller. Could you please guide me through the steps?
         Network problem    I'm having an issue with the Roomba Robot Vacuum. Please assist. If the customer has the required information for the product or it appears it is an error while opening the product, please forward it to the team at the point of purchase I've recently updated the firmware of my Roomba Robot Vacuum, and the issue started happening afterward. Could it be related to the update?
          Hardware issue I've encountered a data loss issue with my Nintendo Switch Pro Controller. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? It is common to find the items that are missing or stolen I've recently updated the firmware of my Nintendo Switch Pro Controller, and the issue started happening afterward. Could it be related to the update?
            Software bug I'm having an issue with the Nintendo Switch Pro Controller. Please assist. The requested address will be returned within 3 – 9 business days. Please do not hesitate to contact us using the appropriate form. (9 weeks from purchase time I'm unable to find the option to perform the desired action in the Nintendo Switch Pro Controller. Could you please guide me through the steps?
    Cancellation request                   There seems to be a hardware problem with my Nintendo Switch Pro Controller. The screen is flickering, and I'm unable to use it. What should I do? I've been running a version of Adobe Photoshop for about two years now I'm unable to find the option to perform the desired action in the Nintendo Switch Pro Controller. Could you please guide me through the steps?
            Software bug                                          I'm facing issues logging into my Sony 4K HDR TV account. It says my account is locked. What should I do to unlock it? Is there a way I can force it to unlock? Please share your thoughts in the comments. I've recently updated the firmware of my Sony 4K HDR TV, and the issue started happening afterward. Could it be related to the update?
        Delivery problem  My Nintendo Switch Pro Controller is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? Thanks for your help I'm using a third party to perform these tests and we I've noticed a peculiar error message popping up on my Nintendo Switch Pro Controller screen. It says '[PLACEHOLDER]'. What does it mean?
Peripheral compatibility                                 I'm having an issue with the Google Nest. Please assist. * This product is a bit out of my price range but is available to us for use in other categories like health care * It might also work with some other devices I've recently updated the firmware of my Google Nest, and the issue started happening afterward. Could it be related to the update?

======================================================================
SUBJECT / DESCRIPTION VOCABULARY
======================================================================
Unique subject words: 25
Unique description words: 6024
Vocabulary overlap: 24

Subject vocabulary:
['access', 'account', 'battery', 'bug', 'cancellation', 'compatibility', 'data', 'delivery', 'display', 'hardware', 'installation', 'issue', 'life', 'loss', 'network', 'payment', 'peripheral', 'problem', 'product', 'recommendation', 'refund', 'request', 'setup', 'software', 'support']

======================================================================
SUBJECT vs DESCRIPTION — 20 RANDOM EXAMPLES
======================================================================
          Ticket Subject                                                                                                                                                                                                                                                                                                                                      Ticket Description
         Network problem                                                              I'm having an issue with the Fitbit Versa Smartwatch. Please assist. The order will be processed to ensure that they don't have to take down my order, and I will send the refund to them. I can I've already contacted customer support multiple times, but the issue remains unresolved.
           Payment issue                                                            I'm having an issue with the Autodesk AutoCAD. Please assist. 0x0000000000000 0x00000000000000 0x00000000000000 0x00000000000000 0x00000000000000 0 I've recently updated the firmware of my Autodesk AutoCAD, and the issue started happening afterward. Could it be related to the update?
    Installation support                                I've accidentally deleted important data from my Amazon Echo. Is there any way to recover the deleted files? I need them urgently. A large amount of time has passed since a lot of users decided to re-download files from their I need assistance as soon as possible because it's affecting my work and productivity.
               Data loss                          I'm encountering a software bug in the Amazon Echo. Whenever I try to perform a specific action, the application crashes. Are there any updates or fixes available? Yes, the software updates or fixes are always available. Updates I've already contacted customer support multiple times, but the issue remains unresolved.
            Battery life                                                        I'm having an issue with the Asus ROG. Please assist. Thank you. What's the Problem? The product is not available to purchase on the market today. We are in the business of maintaining and improving I've already contacted customer support multiple times, but the issue remains unresolved.
        Delivery problem                                                                            I'm having an issue with the Autodesk AutoCAD. Please assist. I can't find the product price for the e-dictionary for $4.95, if that might be a good reason. Do note The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
   Product compatibility                                      There seems to be a glitch in the Bose SoundLink Speaker software. It freezes frequently, making it difficult to use. Can you please provide a solution? Bose SoundLink Speaker has a workaround. Thanks! 4 I've tried different settings and configurations on my Bose SoundLink Speaker, but the issue persists.
            Battery life                                                                                                             I'm having an issue with the Sony PlayStation. Please assist. [05:11:55] So, the thing is it's your job to do. But I guess if someone's I've noticed a sudden decrease in battery life on my Sony PlayStation. It used to last much longer.
  Product recommendation                                                                                                              I'm having an issue with the LG OLED. Please assist. The LG OLED. Please assist. 0 10 1010 5:00 AM The Product Props I made last week have gone I've noticed a sudden decrease in battery life on my LG OLED. It used to last much longer.
          Hardware issue                                                                                                                                               I'm having an issue with the Canon DSLR Camera. Please assist. Thanks. You can also log in with [URL] I'm using the original charger that came with my Canon DSLR Camera, but it's not charging properly.
          Refund request                                            I've encountered a data loss issue with my Fitbit Charge. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? "I can't. I have no way of knowing. This should I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.
  Product recommendation                         I'm having an issue with the Google Pixel. Please assist. We're working on getting it up and running to our userbase! Keep in mind that there's a very small possibility that it may get stuck... I'm unable to find the option to perform the desired action in the Google Pixel. Could you please guide me through the steps?
           Product setup                                                                           I'm having an issue with the LG OLED. Please assist. No way for me to fix it. Thanks for looking at this product. Rated 5 out of 5 by Anonymous from It fits the problem. It fits the I've checked the device settings and made sure that everything is configured correctly.
          Hardware issue I'm having an issue with the Adobe Photoshop. Please assist. I have an issue with the "Product Details" field on the product page. I have a number of questions about this topic, especially about the "product I've recently updated the firmware of my Adobe Photoshop, and the issue started happening afterward. Could it be related to the update?
               Data loss                                                I'm having an issue with the Bose SoundLink Speaker. Please assist. Please refer to the purchase details that appear in the "Rename Your Product" link in the box. * Please include the name/email of the product I need assistance as soon as possible because it's affecting my work and productivity.
          Hardware issue                                                   I'm having an issue with the iPhone. Please assist. Otherwise it doesn't match or it doesn't exist. If the product is not listed, simply contact me with the price and the email address you purchased. I'm worried that the issue might be hardware-related and might require repair or replacement.
          Refund request                                      I'm having trouble connecting my iPhone to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. What can be done to resolve this issue? I am using the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.
    Installation support                                                                                                                                                                   I'm having an issue with the LG Smart TV. Please assist. I'm unable to find the option to perform the desired action in the LG Smart TV. Could you please guide me through the steps?
Peripheral compatibility                                                   I've noticed a software bug in the Lenovo ThinkPad app. It's causing data loss and unexpected errors. How can I resolve this issue? We've found an easy to fix issue that we can work around and will I've tried different settings and configurations on my Lenovo ThinkPad, but the issue persists.
          Account access                                                                                                                                                                   I'm having an issue with the Microsoft Office. Please assist. Here's video from iStock. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

In [5]:
# ============================================================
# EDA STEP 3 — Repetition, Boilerplate & Subject Consistency
# ============================================================

import re
from collections import Counter

text = df["Ticket Description"].astype(str)
subjects = df["Ticket Subject"].astype(str)


# ------------------------------------------------------------
# 1. Measure exact repetition of common boilerplate sentences
# ------------------------------------------------------------
print("=" * 70)
print("REPEATED BOILERPLATE / SENTENCE PATTERNS")
print("=" * 70)

patterns = {
    "Generic opening":
        r"I'm having an issue with .*?\. Please assist\.",

    "Generic opening - facing":
        r"I'm facing a problem with .*?\. Please assist\.",

    "Generic opening - trouble":
        r"I'm having trouble .*?\.",

    "Unresolved support":
        r"I've already contacted customer support multiple times, but the issue remains unresolved\.",

    "Firmware update pattern":
        r"I've recently updated the firmware.*?issue started happening afterward.*?\?",

    "Troubleshooting pattern":
        r"I've (?:tried|followed|checked).*?(?:issue persists|problem persists|no luck).*?\."
}

for name, pattern in patterns.items():
    matches = text.str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{name:<35} {matches:>5} ({matches / len(text) * 100:>6.2f}%)")


# ------------------------------------------------------------
# 2. Count how many sentences each description contains
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SENTENCE COUNT")
print("=" * 70)

def sentence_count(value: str) -> int:
    # Simple sentence boundary estimate for EDA only.
    sentences = re.split(r"(?<=[.!?])\s+", value.strip())
    return len([s for s in sentences if s.strip()])


sentence_counts = text.apply(sentence_count)

print(sentence_counts.describe())

print("\nSentence count distribution:")
print(sentence_counts.value_counts().sort_index())


# ------------------------------------------------------------
# 3. Check how much of each description is repeated boilerplate
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("BOILERPLATE DENSITY")
print("=" * 70)

boilerplate_patterns = [
    r"I'm having an issue with .*?\. Please assist\.",
    r"I'm facing a problem with .*?\. Please assist\.",
    r"I'm having trouble .*?\.",
    r"I've already contacted customer support multiple times, but the issue remains unresolved\.",
    r"I've recently updated the firmware.*?\?",
    r"I've tried .*?\.?",
    r"I've checked .*?\.?",
]

def boilerplate_length(value: str) -> int:
    total = 0

    for pattern in boilerplate_patterns:
        matches = re.findall(
            pattern,
            value,
            flags=re.IGNORECASE
        )

        total += sum(len(match) for match in matches)

    return total


boilerplate_chars = text.apply(boilerplate_length)

boilerplate_ratio = (
    boilerplate_chars / text.str.len()
).clip(upper=1.0)

print("Mean estimated boilerplate ratio:",
      round(boilerplate_ratio.mean(), 4))

print("Median estimated boilerplate ratio:",
      round(boilerplate_ratio.median(), 4))

print("Tickets with >25% estimated boilerplate:",
      (boilerplate_ratio > 0.25).sum())

print("Tickets with >50% estimated boilerplate:",
      (boilerplate_ratio > 0.50).sum())


# ------------------------------------------------------------
# 4. Compare Subject words against Description
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SUBJECT-DESCRIPTION WORD OVERLAP")
print("=" * 70)

def normalize_words(value: str) -> set[str]:
    return set(
        re.findall(
            r"\b[a-zA-Z][a-zA-Z'-]*\b",
            value.lower()
        )
    )

overlap_ratios = []

for subject, description in zip(subjects, text):

    subject_words = normalize_words(subject)
    description_words = normalize_words(description)

    if subject_words:
        overlap = len(subject_words & description_words)
        ratio = overlap / len(subject_words)
    else:
        ratio = 0

    overlap_ratios.append(ratio)

overlap_ratios = pd.Series(overlap_ratios)

print(overlap_ratios.describe())

print("\nOverlap categories:")

print(
    "0% overlap:",
    (overlap_ratios == 0).sum()
)

print(
    "1–49% overlap:",
    ((overlap_ratios > 0) & (overlap_ratios < 1)).sum()
)

print(
    "100% overlap:",
    (overlap_ratios == 1).sum()
)


# ------------------------------------------------------------
# 5. Show examples with very low subject-description overlap
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("LOW SUBJECT-DESCRIPTION OVERLAP EXAMPLES")
print("=" * 70)

low_overlap_indices = overlap_ratios.nsmallest(10).index

print(
    df.loc[
        low_overlap_indices,
        ["Ticket Subject", "Ticket Description"]
    ].to_string(index=False)
)


# ------------------------------------------------------------
# 6. Show examples with high subject-description overlap
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("HIGH SUBJECT-DESCRIPTION OVERLAP EXAMPLES")
print("=" * 70)

high_overlap_indices = overlap_ratios.nlargest(10).index

print(
    df.loc[
        high_overlap_indices,
        ["Ticket Subject", "Ticket Description"]
    ].to_string(index=False)
)

======================================================================
REPEATED BOILERPLATE / SENTENCE PATTERNS
======================================================================
Generic opening                      5868 ( 69.29%)
Generic opening - facing                0 (  0.00%)
Generic opening - trouble             178 (  2.10%)
Unresolved support                    460 (  5.43%)
Firmware update pattern               485 (  5.73%)
Troubleshooting pattern              1404 ( 16.58%)

======================================================================
SENTENCE COUNT
======================================================================
count    8469.000000
mean        4.609635
std         1.163908
min         2.000000
25%         4.000000
50%         4.000000
75%         5.000000
max        14.000000
Name: Ticket Description, dtype: float64

Sentence count distribution:
Ticket Description
2        1
3     1350
4     2950
5     2540
6     1115
7      370
8      104
9       24
10      10
11       3
12       1
14       1
Name: count, dtype: int64

======================================================================
BOILERPLATE DENSITY
======================================================================
Mean estimated boilerplate ratio: 0.2229
Median estimated boilerplate ratio: 0.2134
Tickets with >25% estimated boilerplate: 2781
Tickets with >50% estimated boilerplate: 675

======================================================================
SUBJECT-DESCRIPTION WORD OVERLAP
======================================================================
count    8469.000000
mean        0.143405
std         0.241429
min         0.000000
25%         0.000000
50%         0.000000
75%         0.500000
max         1.000000
dtype: float64

Overlap categories:
0% overlap: 6161
1–49% overlap: 2187
100% overlap: 121

======================================================================
LOW SUBJECT-DESCRIPTION OVERLAP EXAMPLES
======================================================================
          Ticket Subject                                                                                                                                                                                                                                                                                                                                             Ticket Description
           Product setup                                                                               I'm having an issue with the GoPro Hero. Please assist. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.
Peripheral compatibility                                                                                        I'm having an issue with the LG Smart TV. Please assist. If you need to change an existing product. I'm having an issue with the LG Smart TV. Please assist. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
          Account access                                                                                             I'm having an issue with the Microsoft Office. Please assist. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.
               Data loss                          I'm having an issue with the Autodesk AutoCAD. Please assist. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.
           Payment issue                                                                        I'm facing a problem with my Microsoft Office. The Microsoft Office is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new Microsoft Office I've checked for any available software updates for my Microsoft Office, but there are none.
          Refund request               I'm unable to access my Microsoft Surface account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account? Solution 1 I'm unable to find the option to perform the desired action in the Microsoft Surface. Could you please guide me through the steps?
            Battery life                        I'm having an issue with the Philips Hue Lights. Please assist. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.
    Installation support I'm having an issue with the Fitbit Versa Smartwatch. Please assist. Thank you. Fitbit Versa Smartwatch is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my Fitbit Versa Smartwatch, and the issue started happening afterward. Could it be related to the update?
               Data loss                                                                                               I'm having an issue with the Nintendo Switch. Please assist. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.
            Software bug                                                   I'm having an issue with the Microsoft Xbox Controller. Please assist. 4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown. 5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

======================================================================
HIGH SUBJECT-DESCRIPTION OVERLAP EXAMPLES
======================================================================
 Ticket Subject                                                                                                                                                                                                                                                                                                                                  Ticket Description
   Software bug      I'm encountering a software bug in the Sony Xperia. Whenever I try to perform a specific action, the application crashes. Are there any updates or fixes available? There are several packages that run in memory by default. These I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.
      Data loss                 I've encountered a data loss issue with my Dyson Vacuum Cleaner. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? Please take time to ask. If there is something else I can do I've checked for software updates, and my Dyson Vacuum Cleaner is already running the latest version.
      Data loss                                           I've encountered a data loss issue with my Roomba Robot Vacuum. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them? Thanks!" Seth A. Vissers The data loss I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.
 Hardware issue                                                         I'm having an issue with the Nintendo Switch Pro Controller. Please assist. What does this do? My $45k purchase was just for a computer and I wasn't paid for hardware. It didn't go above my I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.
 Hardware issue                                              My Asus ROG is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? Thanks, Trent O'Neil Founder and Sales Manager I've performed a factory reset on my Asus ROG, hoping it would resolve the problem, but it didn't help.
 Refund request                                                                       I'm having an issue with the Nikon D. Please assist. If you wish to request a refund, please send an email to info@cadetv.net. Please send the email to [email protected]. I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.
Network problem The GoPro Hero is unable to establish a stable internet connection. It keeps disconnecting intermittently. How can I troubleshoot this network problem? We recommend you test your ISP's internal network in the next week or I've noticed a peculiar error message popping up on my GoPro Hero screen. It says '[PLACEHOLDER]'. What does it mean?
   Battery life                                    I've noticed a software bug in the Apple AirPods app. It's causing data loss and unexpected errors. How can I resolve this issue? To prevent data loss, upgrade the firmware to theolia package version 1.22 or I've noticed a sudden decrease in battery life on my Apple AirPods. It used to last much longer.
  Payment issue                                               I'm having an issue with the HP Pavilion. Please assist. • Please be sure you check your email to confirm which invoice you've purchased. It may take up to 3-4 weeks for the payment information to arrive I've already contacted customer support multiple times, but the issue remains unresolved.
   Software bug                                                                            I've noticed a software bug in the Garmin Forerunner app. It's causing data loss and unexpected errors. How can I resolve this issue? The vendor will now create a patch at [URL] I need assistance as soon as possible because it's affecting my work and productivity.

In [6]:
# ============================================================
# EDA STEP 4 — Sentence-Level Repetition Analysis
# ============================================================

import re
from collections import Counter

text = df["Ticket Description"].astype(str)


# ------------------------------------------------------------
# 1. Split descriptions into sentences
# ------------------------------------------------------------
def split_sentences(value: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", value.strip())
    return [s.strip() for s in sentences if s.strip()]


all_sentences = []

for value in text:
    all_sentences.extend(split_sentences(value))


print("=" * 70)
print("SENTENCE-LEVEL CORPUS")
print("=" * 70)

print("Total sentences:", len(all_sentences))
print("Unique sentences:", len(set(all_sentences)))


# ------------------------------------------------------------
# 2. Exact repeated sentences
# ------------------------------------------------------------
sentence_counts = Counter(all_sentences)

print("\n" + "=" * 70)
print("TOP 40 EXACT REPEATED SENTENCES")
print("=" * 70)

for sentence, count in sentence_counts.most_common(40):
    if count > 1:
        print(f"\nCount: {count}")
        print(sentence)


# ------------------------------------------------------------
# 3. Sentence frequency distribution
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SENTENCE REPETITION DISTRIBUTION")
print("=" * 70)

frequency_counts = Counter(sentence_counts.values())

for frequency in sorted(frequency_counts):
    print(
        f"Sentences appearing {frequency} time(s): "
        f"{frequency_counts[frequency]}"
    )


# ------------------------------------------------------------
# 4. Normalize sentences to identify templates
# ------------------------------------------------------------
def normalize_sentence(sentence: str) -> str:

    value = sentence.lower().strip()

    # Replace product-like names with placeholder for template detection
    value = re.sub(
        r"\b(?:gopro hero|lg smart tv|microsoft office|"
        r"sony playstation|iphone|xbox|amazon echo|"
        r"nintendo switch|nintendo switch pro controller|"
        r"roomba robot vacuum|google nest|"
        r"fitbit versa smartwatch|apple airpods)\b",
        "<PRODUCT>",
        value,
        flags=re.IGNORECASE
    )

    # Normalize numbers
    value = re.sub(r"\b\d+(?:[.,]\d+)?\b", "<NUMBER>", value)

    # Normalize whitespace
    value = re.sub(r"\s+", " ", value)

    return value


normalized_sentences = [
    normalize_sentence(sentence)
    for sentence in all_sentences
]

template_counts = Counter(normalized_sentences)


# ------------------------------------------------------------
# 5. Most common normalized templates
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("TOP 40 NORMALIZED SENTENCE TEMPLATES")
print("=" * 70)

for template, count in template_counts.most_common(40):

    if count > 3:

        print(f"\nCount: {count}")
        print(template)


# ------------------------------------------------------------
# 6. How concentrated is the sentence corpus?
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("SENTENCE CORPUS CONCENTRATION")
print("=" * 70)

for threshold in [2, 5, 10, 25, 50, 100]:

    count = sum(
        1
        for frequency in template_counts.values()
        if frequency >= threshold
    )

    print(
        f"Templates appearing >= {threshold:>3} times: "
        f"{count}"
    )


# ------------------------------------------------------------
# 7. Show a few complete descriptions containing
#    highly repeated non-opening sentences
# ------------------------------------------------------------
print("\n" + "=" * 70)
print("EXAMPLES WITH REPEATED SENTENCE TEMPLATES")
print("=" * 70)

repeated_templates = {
    template
    for template, count in template_counts.items()
    if count >= 25
}

shown = 0

for index, value in enumerate(text):

    sentences = split_sentences(value)

    matched = [
        sentence
        for sentence in sentences
        if normalize_sentence(sentence) in repeated_templates
    ]

    if matched:

        print(f"\n--- Ticket row {index} ---")
        print("Subject:", df.loc[index, "Ticket Subject"])
        print("Description:", value)

        shown += 1

        if shown >= 10:
            break

======================================================================
SENTENCE-LEVEL CORPUS
======================================================================
Total sentences: 39039
Unique sentences: 14772

======================================================================
TOP 40 EXACT REPEATED SENTENCES
======================================================================

Count: 6182
Please assist.

Count: 498
Sometimes it works fine, but other times it acts up unexpectedly.

Count: 490
Could you please guide me through the steps?

Count: 485
Could it be related to the update?

Count: 472
It says '[PLACEHOLDER]'.

Count: 472
What does it mean?

Count: 470
I haven't made any other changes to the device.

Count: 286
It used to last much longer.

Count: 224
Thank you.

Count: 189
It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information.

Count: 189
How can I regain access to my account?

Count: 188
How can I recover my account?

Count: 186
How can I troubleshoot this network problem?

Count: 184
It keeps disconnecting intermittently.

Count: 183
Whenever I try to perform a specific action, the application crashes.

Count: 183
Are there any updates or fixes available?

Count: 182
I suspect there might be a hardware issue.

Count: 181
Can you please help me with this?

Count: 179
It was working fine until yesterday, but now it doesn't respond.

Count: 179
What steps should I take to troubleshoot this issue?

Count: 179
It's causing data loss and unexpected errors.

Count: 179
How can I resolve this issue?

Count: 178
It doesn't detect any networks, although other devices are connecting fine.

Count: 178
What can be done to resolve this issue?

Count: 176
I'm having an issue with the Canon EOS.

Count: 169
The screen is flickering, and I'm unable to use it.

Count: 169
What should I do?

Count: 165
Is there any way to recover the deleted files?

Count: 165
I need them urgently.

Count: 164
It freezes frequently, making it difficult to use.

Count: 164
Can you please provide a solution?

Count: 164
All the files and documents seem to have disappeared.

Count: 162
I'm having an issue with the Nest Thermostat.

Count: 161
I'm having an issue with the Apple AirPods.

Count: 161
Can you guide me on how to retrieve them?

Count: 160
I'm having an issue with the Philips Hue Lights.

Count: 156
I'm having an issue with the GoPro Hero.

Count: 156
I'm having an issue with the LG Washing Machine.

Count: 154
It says my account is locked.

Count: 153
What should I do to unlock it?

======================================================================
SENTENCE REPETITION DISTRIBUTION
======================================================================
Sentences appearing 1 time(s): 13570
Sentences appearing 2 time(s): 393
Sentences appearing 3 time(s): 217
Sentences appearing 4 time(s): 182
Sentences appearing 5 time(s): 118
Sentences appearing 6 time(s): 92
Sentences appearing 7 time(s): 45
Sentences appearing 8 time(s): 24
Sentences appearing 9 time(s): 13
Sentences appearing 10 time(s): 9
Sentences appearing 11 time(s): 5
Sentences appearing 12 time(s): 1
Sentences appearing 13 time(s): 1
Sentences appearing 14 time(s): 1
Sentences appearing 15 time(s): 3
Sentences appearing 23 time(s): 1
Sentences appearing 29 time(s): 1
Sentences appearing 31 time(s): 1
Sentences appearing 39 time(s): 2
Sentences appearing 41 time(s): 1
Sentences appearing 42 time(s): 1
Sentences appearing 44 time(s): 1
Sentences appearing 45 time(s): 1
Sentences appearing 46 time(s): 1
Sentences appearing 47 time(s): 1
Sentences appearing 48 time(s): 1
Sentences appearing 49 time(s): 1
Sentences appearing 51 time(s): 1
Sentences appearing 65 time(s): 1
Sentences appearing 83 time(s): 1
Sentences appearing 90 time(s): 1
Sentences appearing 92 time(s): 1
Sentences appearing 94 time(s): 1
Sentences appearing 108 time(s): 1
Sentences appearing 121 time(s): 2
Sentences appearing 125 time(s): 1
Sentences appearing 128 time(s): 1
Sentences appearing 129 time(s): 1
Sentences appearing 130 time(s): 1
Sentences appearing 131 time(s): 2
Sentences appearing 133 time(s): 1
Sentences appearing 134 time(s): 1
Sentences appearing 135 time(s): 1
Sentences appearing 136 time(s): 1
Sentences appearing 137 time(s): 3
Sentences appearing 138 time(s): 3
Sentences appearing 141 time(s): 3
Sentences appearing 142 time(s): 5
Sentences appearing 145 time(s): 1
Sentences appearing 146 time(s): 2
Sentences appearing 147 time(s): 3
Sentences appearing 148 time(s): 2
Sentences appearing 149 time(s): 2
Sentences appearing 152 time(s): 2
Sentences appearing 153 time(s): 1
Sentences appearing 154 time(s): 1
Sentences appearing 156 time(s): 2
Sentences appearing 160 time(s): 1
Sentences appearing 161 time(s): 2
Sentences appearing 162 time(s): 1
Sentences appearing 164 time(s): 3
Sentences appearing 165 time(s): 2
Sentences appearing 169 time(s): 2
Sentences appearing 176 time(s): 1
Sentences appearing 178 time(s): 2
Sentences appearing 179 time(s): 4
Sentences appearing 181 time(s): 1
Sentences appearing 182 time(s): 1
Sentences appearing 183 time(s): 2
Sentences appearing 184 time(s): 1
Sentences appearing 186 time(s): 1
Sentences appearing 188 time(s): 1
Sentences appearing 189 time(s): 2
Sentences appearing 224 time(s): 1
Sentences appearing 286 time(s): 1
Sentences appearing 470 time(s): 1
Sentences appearing 472 time(s): 2
Sentences appearing 485 time(s): 1
Sentences appearing 490 time(s): 1
Sentences appearing 498 time(s): 1
Sentences appearing 6182 time(s): 1

======================================================================
TOP 40 NORMALIZED SENTENCE TEMPLATES
======================================================================

Count: 6182
please assist.

Count: 1744
i'm having an issue with the <PRODUCT>.

Count: 498
sometimes it works fine, but other times it acts up unexpectedly.

Count: 490
could you please guide me through the steps?

Count: 485
could it be related to the update?

Count: 472
it says '[placeholder]'.

Count: 472
what does it mean?

Count: 470
i haven't made any other changes to the device.

Count: 286
it used to last much longer.

Count: 234
thank you.

Count: 231
<NUMBER>.

Count: 189
it keeps displaying an 'invalid credentials' error, even though i'm using the correct login information.

Count: 189
how can i regain access to my account?

Count: 188
how can i recover my account?

Count: 186
how can i troubleshoot this network problem?

Count: 184
it keeps disconnecting intermittently.

Count: 183
whenever i try to perform a specific action, the application crashes.

Count: 183
are there any updates or fixes available?

Count: 182
i suspect there might be a hardware issue.

Count: 181
can you please help me with this?

Count: 179
it was working fine until yesterday, but now it doesn't respond.

Count: 179
what steps should i take to troubleshoot this issue?

Count: 179
it's causing data loss and unexpected errors.

Count: 179
how can i resolve this issue?

Count: 178
it doesn't detect any networks, although other devices are connecting fine.

Count: 178
what can be done to resolve this issue?

Count: 176
i'm having an issue with the canon eos.

Count: 169
the screen is flickering, and i'm unable to use it.

Count: 169
what should i do?

Count: 165
is there any way to recover the deleted files?

Count: 165
i need them urgently.

Count: 164
it freezes frequently, making it difficult to use.

Count: 164
can you please provide a solution?

Count: 164
all the files and documents seem to have disappeared.

Count: 162
i'm having an issue with the nest thermostat.

Count: 161
can you guide me on how to retrieve them?

Count: 160
i'm having an issue with the philips hue lights.

Count: 156
i'm having an issue with the lg washing machine.

Count: 154
it says my account is locked.

Count: 153
what should i do to unlock it?

======================================================================
SENTENCE CORPUS CONCENTRATION
======================================================================
Templates appearing >=   2 times: 980
Templates appearing >=   5 times: 341
Templates appearing >=  10 times: 127
Templates appearing >=  25 times: 102
Templates appearing >=  50 times: 82
Templates appearing >= 100 times: 69

======================================================================
EXAMPLES WITH REPEATED SENTENCE TEMPLATES
======================================================================

--- Ticket row 0 ---
Subject: Product setup
Description: I'm having an issue with the GoPro Hero. Please assist. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 1 ---
Subject: Peripheral compatibility
Description: I'm having an issue with the LG Smart TV. Please assist. If you need to change an existing product. I'm having an issue with the LG Smart TV. Please assist. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 2 ---
Subject: Network problem
Description: I'm facing a problem with my Dell XPS. The Dell XPS is not turning on. It was working fine until yesterday, but now it doesn't respond. 1.8.3 I really I'm using the original charger that came with my Dell XPS, but it's not charging properly.

--- Ticket row 3 ---
Subject: Account access
Description: I'm having an issue with the Microsoft Office. Please assist. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---
Subject: Data loss
Description: I'm having an issue with the Autodesk AutoCAD. Please assist. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 5 ---
Subject: Payment issue
Description: I'm facing a problem with my Microsoft Office. The Microsoft Office is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new Microsoft Office I've checked for any available software updates for my Microsoft Office, but there are none.

--- Ticket row 6 ---
Subject: Refund request
Description: I'm unable to access my Microsoft Surface account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account? Solution 1 I'm unable to find the option to perform the desired action in the Microsoft Surface. Could you please guide me through the steps?

--- Ticket row 7 ---
Subject: Battery life
Description: I'm having an issue with the Philips Hue Lights. Please assist. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 8 ---
Subject: Installation support
Description: I'm having an issue with the Fitbit Versa Smartwatch. Please assist. Thank you. Fitbit Versa Smartwatch is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my Fitbit Versa Smartwatch, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 9 ---
Subject: Payment issue
Description: My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

In [7]:
# ============================================================
# EDA STEP 5 — Estimate Removable Boilerplate Per Ticket
# ============================================================

import re

# Clearly generic support/conversational sentences identified
# from the repetition analysis.
generic_sentences = {
    "please assist.",
    "thank you.",
    "what should i do?",
    "can you please help me with this?",
    "can you please provide a solution?",
    "how can i resolve this issue?",
    "what does it mean?",
    "could you please guide me through the steps?",
    "what can be done to resolve this issue?",
    "how can i troubleshoot this network problem?",
    "what steps should i take to troubleshoot this issue?",
    "are there any updates or fixes available?",
    "how can i regain access to my account?",
    "how can i recover my account?",
    "can you guide me on how to retrieve them?",
    "i need them urgently.",
}

def split_sentences(value: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", value.strip())
    return [s.strip() for s in sentences if s.strip()]

def normalize_for_matching(sentence: str) -> str:
    return re.sub(r"\s+", " ", sentence.lower().strip())

results = []

for index, value in enumerate(df["Ticket Description"].astype(str)):

    sentences = split_sentences(value)

    removable = []
    informative = []

    for sentence in sentences:

        normalized = normalize_for_matching(sentence)

        if normalized in generic_sentences:
            removable.append(sentence)
        else:
            informative.append(sentence)

    total = len(sentences)
    removable_count = len(removable)

    results.append({
        "row": index,
        "total_sentences": total,
        "removable_sentences": removable_count,
        "remaining_sentences": len(informative),
        "removable_ratio": removable_count / total if total else 0,
    })

boilerplate_df = pd.DataFrame(results)

print("=" * 70)
print("TARGETED BOILERPLATE ANALYSIS")
print("=" * 70)

print(
    "\nAverage removable sentence ratio:",
    round(boilerplate_df["removable_ratio"].mean(), 4)
)

print(
    "Median removable sentence ratio:",
    round(boilerplate_df["removable_ratio"].median(), 4)
)

print(
    "Tickets with >= 25% removable:",
    int((boilerplate_df["removable_ratio"] >= 0.25).sum())
)

print(
    "Tickets with >= 50% removable:",
    int((boilerplate_df["removable_ratio"] >= 0.50).sum())
)

print(
    "Tickets with >= 75% removable:",
    int((boilerplate_df["removable_ratio"] >= 0.75).sum())
)

print(
    "Tickets with ALL sentences removable:",
    int((boilerplate_df["remaining_sentences"] == 0).sum())
)

print("\n" + "=" * 70)
print("REMAINING SENTENCE COUNT")
print("=" * 70)

print(
    boilerplate_df["remaining_sentences"]
    .value_counts()
    .sort_index()
    .to_string()
)

print("\n" + "=" * 70)
print("HIGHEST BOILERPLATE TICKETS")
print("=" * 70)

print(
    boilerplate_df
    .sort_values("removable_ratio", ascending=False)
    .head(20)
    .to_string(index=False)
)

======================================================================
TARGETED BOILERPLATE ANALYSIS
======================================================================

Average removable sentence ratio: 0.2485
Median removable sentence ratio: 0.25
Tickets with >= 25% removable: 5229
Tickets with >= 50% removable: 174
Tickets with >= 75% removable: 3
Tickets with ALL sentences removable: 0

======================================================================
REMAINING SENTENCE COUNT
======================================================================
remaining_sentences
2     1449
3     3137
4     2565
5     1018
6      244
7       40
8       11
9        3
10       1
11       1

======================================================================
HIGHEST BOILERPLATE TICKETS
======================================================================
 row  total_sentences  removable_sentences  remaining_sentences  removable_ratio
3087               14                   12                    2         0.857143
4556               10                    8                    2         0.800000
7482                9                    7                    2         0.777778
6208               10                    7                    3         0.700000
3521                8                    5                    3         0.625000
4926                5                    3                    2         0.600000
6324                5                    3                    2         0.600000
2457                7                    4                    3         0.571429
7550                7                    4                    3         0.571429
1463                7                    4                    3         0.571429
8135                7                    4                    3         0.571429
6310                7                    4                    3         0.571429
 887                7                    4                    3         0.571429
 868                7                    4                    3         0.571429
3935                9                    5                    4         0.555556
4761               11                    6                    5         0.545455
2215                4                    2                    2         0.500000
3264                4                    2                    2         0.500000
2973                4                    2                    2         0.500000
7044                4                    2                    2         0.500000

In [8]:
# ============================================================
# EDA STEP 6 — Sentence Relevance / Topic Consistency
# ============================================================

import re
import pandas as pd
from collections import Counter

def split_sentences(value: str) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", value.strip())
    return [s.strip() for s in sentences if s.strip()]

# Extract sentences from every ticket
ticket_sentences = []

for index, value in enumerate(df["Ticket Description"].astype(str)):
    sentences = split_sentences(value)

    ticket_sentences.append({
        "row": index,
        "sentences": sentences
    })

# ------------------------------------------------------------
# 1. Inspect suspiciously unrelated sentences manually
# ------------------------------------------------------------

print("=" * 70)
print("SUSPICIOUS SENTENCE EXAMPLES")
print("=" * 70)

# Keywords seen in the contamination examples.
# These are ONLY for investigation, not cleaning rules.
suspicious_patterns = [
    r"\bbilling zip code\b",
    r"\bwebsite address\b",
    r"\bfeedback\b",
    r"\bseller\b",
    r"\bdamages arising\b",
    r"\bbattleground game\b",
    r"\bsuppliers\b",
    r"\binventory\b",
    r"\brequest\b.*\bdav\b",
]

pattern = re.compile(
    "|".join(suspicious_patterns),
    flags=re.IGNORECASE
)

found = []

for item in ticket_sentences:

    for sentence in item["sentences"]:

        if pattern.search(sentence):

            found.append({
                "row": item["row"],
                "sentence": sentence
            })

print("Suspicious sentence matches:", len(found))

for item in found[:40]:

    print(f"\nRow: {item['row']}")
    print("Sentence:", item["sentence"])


# ------------------------------------------------------------
# 2. Count sentences containing suspicious patterns
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUSPICIOUS SENTENCE FREQUENCY")
print("=" * 70)

sentence_counter = Counter(
    item["sentence"]
    for item in found
)

for sentence, count in sentence_counter.most_common(30):

    print(f"\nCount: {count}")
    print(sentence)


# ------------------------------------------------------------
# 3. Inspect complete tickets containing suspicious content
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMPLETE TICKET EXAMPLES")
print("=" * 70)

shown_rows = set()

for item in found:

    row = item["row"]

    if row in shown_rows:
        continue

    shown_rows.add(row)

    print(f"\n--- Ticket row {row} ---")
    print("Subject:", df.loc[row, "Ticket Subject"])
    print("Description:", df.loc[row, "Ticket Description"])

    if len(shown_rows) >= 15:
        break

======================================================================
SUSPICIOUS SENTENCE EXAMPLES
======================================================================
Suspicious sentence matches: 177

Row: 0
Sentence: Your billing zip code is: 71701.

Row: 0
Sentence: We appreciate that you have requested a website address.

Row: 3
Sentence: If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback.

Row: 4
Sentence: Note: The seller is not responsible for any damages arising out of the delivery of the battleground game.

Row: 7
Sentence: (Thanks) I will contact all my suppliers and confirm.

Row: 7
Sentence: Please try and find out whether their inventory is currently stocked, or any other reason.

Row: 9
Sentence: If we can, please send a "request" to dav The issue I'm facing is intermittent.

Row: 10
Sentence: Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

Row: 31
Sentence: The seller has sold the item for $29.89.

Row: 147
Sentence: Thank you for your information." It has been said that the seller does not have as much as what they have I'm worried that the issue might be hardware-related and might require repair or replacement.

Row: 161
Sentence: If this is not your case, please refer to the seller's This problem started occurring after the recent software update.

Row: 246
Sentence: Please try to have an informed discussion about this issue with the seller.

Row: 478
Sentence: The seller says on 3/1/16 The base plate is missing a metal bracket.

Row: 490
Sentence: " " In order to avoid this error (via the search engine, we did make some changes with new users and their feedback) a new tab is created I've noticed a sudden decrease in battery life on my Microsoft Office.

Row: 520
Sentence: If you have any further feedback, please drop me an email at xanj@comcast.net.

Row: 526
Sentence: (814353716) Thank you for your feedback.

Row: 530
Sentence: First, look at the seller's web site.

Row: 533
Sentence: [01:13:12] [Client thread/ERROR] [FML]: Unable to remove a config variable from net.minecraft.inventory.ItemStack I've checked for any available software updates for my LG Smart TV, but there are none.

Row: 745
Sentence: Please send feedback here -V.3.0 This problem started occurring after the recent software update.

Row: 787
Sentence: The product that I purchased from the sellers is not in the product description and the seller won't change it.

Row: 838
Sentence: In the event you have never bought from this site, then the information here and the "Cancel" button have been replaced by "Retain Seller Info".

Row: 842
Sentence: When you're looking at the seller, there's a lot of information that you may see there.

Row: 965
Sentence: If you were the seller, please add a check to that transaction to make sure you're actually paying for the merchandise.

Row: 982
Sentence: Simply click on it (in this case, the seller's name) on the The issue I'm facing is intermittent.

Row: 1002
Sentence: */ d-> errno = 0 ; /* * This function returns the product * from the inventory of the item I'm unable to find the option to perform the desired action in the LG Smart TV.

Row: 1128
Sentence: — the product The product is not an item in your inventory.

Row: 1128
Sentence: If you have an item that is not an item in your inventory, you may contact us I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.

Row: 1162
Sentence: Please do not order this item unless it comes with a physical item to which the seller is responsible.

Row: 1190
Sentence: We use a third party seller(d-w) who may use their name or contact details to place a charge I'm not sure if this issue is specific to my device or if others have reported similar problems.

Row: 1215
Sentence: I understand you're upset because he offered to give the seller of I've tried different settings and configurations on my Nikon D, but the issue persists.

Row: 1240
Sentence: I am trying to determine if it's the original product or a copy of some other product, you can try to reach out to the seller to make sure I've performed a factory reset on my PlayStation, hoping it would resolve the problem, but it didn't help.

Row: 1343
Sentence: If its a small item from the same seller as the original, I'm sorry $29.

Row: 1408
Sentence: Seller Notes: 0.29% OFF the I've tried clearing the cache and data for the Xbox app, but the issue persists.

Row: 1435
Sentence: We had been searching through the inventory at the tankers that were shipped overseas (We I've recently updated the firmware of my Sony Xperia, and the issue started happening afterward.

Row: 1513
Sentence: It's kind of difficult, but I found one in my inventory in This problem started occurring after the recent software update.

Row: 1577
Sentence: How do you respond to feedback about products that aren't listed?

Row: 1603
Sentence: It's probably a good idea to use the product information you get from the seller before sending the invoice.

Row: 1603
Sentence: This can be achieved using the "Manage Seller I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.

Row: 1628
Sentence: This will be handled in a different priority process of the seller and I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

Row: 1736
Sentence: [B]Please contact the seller when available and confirm purchase will begin.

======================================================================
SUSPICIOUS SENTENCE FREQUENCY
======================================================================

Count: 3
Thank you for your feedback.

Count: 2
Your feedback is critical.

Count: 1
Your billing zip code is: 71701.

Count: 1
We appreciate that you have requested a website address.

Count: 1
If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback.

Count: 1
Note: The seller is not responsible for any damages arising out of the delivery of the battleground game.

Count: 1
(Thanks) I will contact all my suppliers and confirm.

Count: 1
Please try and find out whether their inventory is currently stocked, or any other reason.

Count: 1
If we can, please send a "request" to dav The issue I'm facing is intermittent.

Count: 1
Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

Count: 1
The seller has sold the item for $29.89.

Count: 1
Thank you for your information." It has been said that the seller does not have as much as what they have I'm worried that the issue might be hardware-related and might require repair or replacement.

Count: 1
If this is not your case, please refer to the seller's This problem started occurring after the recent software update.

Count: 1
Please try to have an informed discussion about this issue with the seller.

Count: 1
The seller says on 3/1/16 The base plate is missing a metal bracket.

Count: 1
" " In order to avoid this error (via the search engine, we did make some changes with new users and their feedback) a new tab is created I've noticed a sudden decrease in battery life on my Microsoft Office.

Count: 1
If you have any further feedback, please drop me an email at xanj@comcast.net.

Count: 1
(814353716) Thank you for your feedback.

Count: 1
First, look at the seller's web site.

Count: 1
[01:13:12] [Client thread/ERROR] [FML]: Unable to remove a config variable from net.minecraft.inventory.ItemStack I've checked for any available software updates for my LG Smart TV, but there are none.

Count: 1
Please send feedback here -V.3.0 This problem started occurring after the recent software update.

Count: 1
The product that I purchased from the sellers is not in the product description and the seller won't change it.

Count: 1
In the event you have never bought from this site, then the information here and the "Cancel" button have been replaced by "Retain Seller Info".

Count: 1
When you're looking at the seller, there's a lot of information that you may see there.

Count: 1
If you were the seller, please add a check to that transaction to make sure you're actually paying for the merchandise.

Count: 1
Simply click on it (in this case, the seller's name) on the The issue I'm facing is intermittent.

Count: 1
*/ d-> errno = 0 ; /* * This function returns the product * from the inventory of the item I'm unable to find the option to perform the desired action in the LG Smart TV.

Count: 1
— the product The product is not an item in your inventory.

Count: 1
If you have an item that is not an item in your inventory, you may contact us I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.

Count: 1
Please do not order this item unless it comes with a physical item to which the seller is responsible.

======================================================================
COMPLETE TICKET EXAMPLES
======================================================================

--- Ticket row 0 ---
Subject: Product setup
Description: I'm having an issue with the GoPro Hero. Please assist. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 3 ---
Subject: Account access
Description: I'm having an issue with the Microsoft Office. Please assist. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---
Subject: Data loss
Description: I'm having an issue with the Autodesk AutoCAD. Please assist. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 7 ---
Subject: Battery life
Description: I'm having an issue with the Philips Hue Lights. Please assist. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 9 ---
Subject: Payment issue
Description: My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 10 ---
Subject: Data loss
Description: I'm having an issue with the Nintendo Switch. Please assist. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

--- Ticket row 31 ---
Subject: Product compatibility
Description: I'm having an issue with the GoPro Action Camera. Please assist. The seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 147 ---
Subject: Product compatibility
Description: I'm having an issue with the Apple AirPods. Please assist. And of course, please make a list. Thank you for your information." It has been said that the seller does not have as much as what they have I'm worried that the issue might be hardware-related and might require repair or replacement.

--- Ticket row 161 ---
Subject: Product setup
Description: I'm having an issue with the HP Pavilion. Please assist. Note: The number 0, where "0" is the customer that bought the product. If this is not your case, please refer to the seller's This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 246 ---
Subject: Account access
Description: I'm having an issue with the GoPro Hero. Please assist. We have nothing to do with it. Please try to have an informed discussion about this issue with the seller. Thank you for your time! 3/28 The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 478 ---
Subject: Software bug
Description: I'm having an issue with the Lenovo ThinkPad. Please assist. The seller says on 3/1/16 The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 490 ---
Subject: Display issue
Description: I'm having an issue with the Microsoft Office. Please assist. " " In order to avoid this error (via the search engine, we did make some changes with new users and their feedback) a new tab is created I've noticed a sudden decrease in battery life on my Microsoft Office. It used to last much longer.

--- Ticket row 520 ---
Subject: Software bug
Description: I'm having an issue with the LG Smart TV. Please assist. If you have any further feedback, please drop me an email at xanj@comcast.net. [This post has been updated.] I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 526 ---
Subject: Display issue
Description: I'm having an issue with the Bose QuietComfort. Please assist. (814353716) Thank you for your feedback. (16791812) Hi everyone! Sorry for having a bad issue so I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 530 ---
Subject: Product compatibility
Description: I'm having an issue with the Apple AirPods. Please assist. I have tried to do some research on various alternatives and it is an easy way to get this right as well. First, look at the seller's web site. I need assistance as soon as possible because it's affecting my work and productivity.

In [9]:
# ============================================================
# PREPROCESSING RULE 1
# Remove generic conversational/support boilerplate
# ============================================================

import re
import pandas as pd

GENERIC_BOILERPLATE = {
    "please assist.",
    "thank you.",
    "what should i do?",
    "can you please help me with this?",
    "can you please provide a solution?",
    "how can i resolve this issue?",
    "what does it mean?",
    "could you please guide me through the steps?",
    "what can be done to resolve this issue?",
    "how can i troubleshoot this network problem?",
    "what steps should i take to troubleshoot this issue?",
    "are there any updates or fixes available?",
    "how can i regain access to my account?",
    "how can i recover my account?",
    "can you guide me on how to retrieve them?",
    "i need them urgently.",
}


def split_sentences(text: str) -> list[str]:
    """Split a ticket description into sentences."""
    
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    
    return [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]


def normalize_sentence(sentence: str) -> str:
    """Normalize only for matching boilerplate."""
    
    return re.sub(
        r"\s+",
        " ",
        sentence.lower().strip()
    )


def remove_generic_boilerplate(text: str) -> str:
    """
    Remove only explicitly identified generic support sentences.

    No product names, numbers, technical terms, or issue-bearing
    sentences are removed by this rule.
    """
    
    sentences = split_sentences(text)
    
    remaining_sentences = [
        sentence
        for sentence in sentences
        if normalize_sentence(sentence) not in GENERIC_BOILERPLATE
    ]
    
    return " ".join(remaining_sentences)


# Apply Rule 1
df["description_rule1"] = (
    df["Ticket Description"]
    .astype(str)
    .apply(remove_generic_boilerplate)
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

df["original_sentence_count"] = (
    df["Ticket Description"]
    .astype(str)
    .apply(lambda x: len(split_sentences(x)))
)

df["rule1_sentence_count"] = (
    df["description_rule1"]
    .apply(lambda x: len(split_sentences(x)))
)

df["removed_sentence_count"] = (
    df["original_sentence_count"]
    - df["rule1_sentence_count"]
)


print("=" * 70)
print("RULE 1 — PREPROCESSING VALIDATION")
print("=" * 70)

print(
    "\nOriginal tickets:",
    len(df)
)

print(
    "Empty after Rule 1:",
    int((df["description_rule1"].str.strip() == "").sum())
)

print(
    "Tickets with at least one sentence removed:",
    int((df["removed_sentence_count"] > 0).sum())
)

print(
    "Total sentences removed:",
    int(df["removed_sentence_count"].sum())
)

print(
    "Average sentences removed per ticket:",
    round(df["removed_sentence_count"].mean(), 4)
)

print(
    "Maximum sentences removed from one ticket:",
    int(df["removed_sentence_count"].max())
)


print("\n" + "=" * 70)
print("REMOVAL DISTRIBUTION")
print("=" * 70)

print(
    df["removed_sentence_count"]
    .value_counts()
    .sort_index()
    .to_string()
)


# ------------------------------------------------------------
# Before / after examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("BEFORE / AFTER EXAMPLES")
print("=" * 70)

examples = df[
    df["removed_sentence_count"] > 0
].head(10)

for index, row in examples.iterrows():

    print(f"\n--- Ticket row {index} ---")

    print("\nBEFORE:")
    print(row["Ticket Description"])

    print("\nAFTER RULE 1:")
    print(row["description_rule1"])

======================================================================
RULE 1 — PREPROCESSING VALIDATION
======================================================================

Original tickets: 8469
Empty after Rule 1: 0
Tickets with at least one sentence removed: 8022
Total sentences removed: 9500
Average sentences removed per ticket: 1.1217
Maximum sentences removed from one ticket: 12

======================================================================
REMOVAL DISTRIBUTION
======================================================================
removed_sentence_count
0      447
1     6671
2     1266
3       65
4       13
5        2
6        1
7        2
8        1
12       1

======================================================================
BEFORE / AFTER EXAMPLES
======================================================================

--- Ticket row 0 ---

BEFORE:
I'm having an issue with the GoPro Hero. Please assist. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 1:
I'm having an issue with the GoPro Hero. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 1 ---

BEFORE:
I'm having an issue with the LG Smart TV. Please assist. If you need to change an existing product. I'm having an issue with the LG Smart TV. Please assist. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

AFTER RULE 1:
I'm having an issue with the LG Smart TV. If you need to change an existing product. I'm having an issue with the LG Smart TV. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 3 ---

BEFORE:
I'm having an issue with the Microsoft Office. Please assist. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---

BEFORE:
I'm having an issue with the Autodesk AutoCAD. Please assist. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

AFTER RULE 1:
I'm having an issue with the Autodesk AutoCAD. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 6 ---

BEFORE:
I'm unable to access my Microsoft Surface account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account? Solution 1 I'm unable to find the option to perform the desired action in the Microsoft Surface. Could you please guide me through the steps?

AFTER RULE 1:
I'm unable to access my Microsoft Surface account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. Solution 1 I'm unable to find the option to perform the desired action in the Microsoft Surface.

--- Ticket row 7 ---

BEFORE:
I'm having an issue with the Philips Hue Lights. Please assist. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

AFTER RULE 1:
I'm having an issue with the Philips Hue Lights. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 8 ---

BEFORE:
I'm having an issue with the Fitbit Versa Smartwatch. Please assist. Thank you. Fitbit Versa Smartwatch is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my Fitbit Versa Smartwatch, and the issue started happening afterward. Could it be related to the update?

AFTER RULE 1:
I'm having an issue with the Fitbit Versa Smartwatch. Fitbit Versa Smartwatch is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my Fitbit Versa Smartwatch, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 9 ---

BEFORE:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

AFTER RULE 1:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 10 ---

BEFORE:
I'm having an issue with the Nintendo Switch. Please assist. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

AFTER RULE 1:
I'm having an issue with the Nintendo Switch. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

--- Ticket row 11 ---

BEFORE:
I'm having an issue with the Microsoft Xbox Controller. Please assist. 4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown. 5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

AFTER RULE 1:
I'm having an issue with the Microsoft Xbox Controller. 4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown. 5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

In [10]:
# ============================================================
# PREPROCESSING RULE 2 — CANDIDATE CONTAMINATION DETECTION
# ============================================================
#
# IMPORTANT:
# This cell DOES NOT modify the dataset.
#
# It identifies candidate unrelated/injected sentences so that
# we can validate the rule before actually removing anything.
# ============================================================

import re
import pandas as pd


def split_sentences(text: str) -> list[str]:
    """Split a ticket description into sentences."""

    sentences = re.split(
        r"(?<=[.!?])\s+",
        text.strip()
    )

    return [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]


# ------------------------------------------------------------
# Candidate contamination patterns
# ------------------------------------------------------------
#
# These patterns are deliberately conservative.
# They target structures observed in our EDA rather than
# generic words such as "seller", "product", or "feedback".
#
# They are NOT yet final deletion rules.
# ------------------------------------------------------------

CONTAMINATION_PATTERNS = [

    # Marketplace / seller contamination
    (
        "seller_transaction",
        re.compile(
            r"\b(?:seller|sellers)\b.*"
            r"\b(?:sold|selling|merchandise|inventory|"
            r"purchase|purchased|invoice|transaction)\b",
            re.IGNORECASE
        )
    ),

    # Seller + website / product listing contamination
    (
        "seller_listing",
        re.compile(
            r"\b(?:seller|sellers)\b.*"
            r"\b(?:web\s*site|website|product description|"
            r"listed|listing)\b",
            re.IGNORECASE
        )
    ),

    # Supplier / inventory contamination
    (
        "supplier_inventory",
        re.compile(
            r"\b(?:suppliers?|inventory|stocked)\b",
            re.IGNORECASE
        )
    ),

    # Shipping / merchandise contamination
    (
        "shipping_merchandise",
        re.compile(
            r"\b(?:delivery|shipped|shipping|merchandise|"
            r"battleground game)\b.*"
            r"\b(?:seller|item|game|product)\b",
            re.IGNORECASE
        )
    ),

    # Feedback / website fragments
    (
        "feedback_website",
        re.compile(
            r"\b(?:feedback|website address|search engine)\b",
            re.IGNORECASE
        )
    ),

    # Embedded source-code / log contamination
    (
        "source_code_or_log",
        re.compile(
            r"(?:"
            r"\bERROR\b.*"
            r"\[.*\]"
            r"|"
            r"/\*.*\*/"
            r"|"
            r"\b(?:errno|ItemStack|FML)\b"
            r")",
            re.IGNORECASE
        )
    ),

    # Explicitly malformed injected fragments
    (
        "malformed_fragment",
        re.compile(
            r"(?:"
            r"\bReport Feedback Customer Service\b"
            r"|"
            r"\bProduct Search:\s*"
            r"|"
            r"\bplease send a ['\"]request['\"] to\b"
            r"|"
            r"\bretain seller info\b"
            r")",
            re.IGNORECASE
        )
    ),
]


# ------------------------------------------------------------
# Scan the ORIGINAL descriptions
# ------------------------------------------------------------

candidate_rows = []

for index, value in enumerate(
    df["Ticket Description"].astype(str)
):

    sentences = split_sentences(value)

    for sentence in sentences:

        matched_rules = []

        for rule_name, pattern in CONTAMINATION_PATTERNS:

            if pattern.search(sentence):
                matched_rules.append(rule_name)

        if matched_rules:

            candidate_rows.append({
                "row": index,
                "subject": df.loc[index, "Ticket Subject"],
                "sentence": sentence,
                "matched_rules": ", ".join(matched_rules),
            })


candidates_df = pd.DataFrame(candidate_rows)


# ------------------------------------------------------------
# Validation summary
# ------------------------------------------------------------

print("=" * 70)
print("RULE 2 — CANDIDATE CONTAMINATION ANALYSIS")
print("=" * 70)

print(
    "\nCandidate contaminated sentences:",
    len(candidates_df)
)

print(
    "Unique tickets affected:",
    candidates_df["row"].nunique()
    if not candidates_df.empty
    else 0
)

print(
    "Unique candidate sentences:",
    candidates_df["sentence"].nunique()
    if not candidates_df.empty
    else 0
)


# ------------------------------------------------------------
# Rule frequency
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MATCHES BY CONTAMINATION PATTERN")
print("=" * 70)

if not candidates_df.empty:

    rule_counts = (
        candidates_df["matched_rules"]
        .str.split(", ")
        .explode()
        .value_counts()
    )

    print(rule_counts.to_string())

else:
    print("No candidate sentences detected.")


# ------------------------------------------------------------
# Examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CANDIDATE SENTENCE EXAMPLES")
print("=" * 70)

if not candidates_df.empty:

    for _, row in candidates_df.head(40).iterrows():

        print(f"\nRow: {row['row']}")
        print(f"Subject: {row['subject']}")
        print(f"Rule: {row['matched_rules']}")
        print(f"Sentence: {row['sentence']}")


# ------------------------------------------------------------
# Complete ticket examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COMPLETE TICKETS WITH CANDIDATE CONTAMINATION")
print("=" * 70)

shown = set()

if not candidates_df.empty:

    for _, candidate in candidates_df.iterrows():

        row = candidate["row"]

        if row in shown:
            continue

        shown.add(row)

        print(f"\n--- Ticket row {row} ---")
        print("Subject:", df.loc[row, "Ticket Subject"])
        print("Description:", df.loc[row, "Ticket Description"])

        if len(shown) >= 15:
            break

======================================================================
RULE 2 — CANDIDATE CONTAMINATION ANALYSIS
======================================================================

Candidate contaminated sentences: 150
Unique tickets affected: 142
Unique candidate sentences: 147

======================================================================
MATCHES BY CONTAMINATION PATTERN
======================================================================
matched_rules
supplier_inventory      52
feedback_website        50
seller_transaction      15
source_code_or_log      15
shipping_merchandise    13
seller_listing           5
malformed_fragment       4

======================================================================
CANDIDATE SENTENCE EXAMPLES
======================================================================

Row: 0
Subject: Product setup
Rule: feedback_website
Sentence: We appreciate that you have requested a website address.

Row: 3
Subject: Account access
Rule: feedback_website
Sentence: If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback.

Row: 4
Subject: Data loss
Rule: shipping_merchandise
Sentence: Note: The seller is not responsible for any damages arising out of the delivery of the battleground game.

Row: 7
Subject: Battery life
Rule: supplier_inventory
Sentence: (Thanks) I will contact all my suppliers and confirm.

Row: 7
Subject: Battery life
Rule: supplier_inventory
Sentence: Please try and find out whether their inventory is currently stocked, or any other reason.

Row: 9
Subject: Payment issue
Rule: malformed_fragment
Sentence: If we can, please send a "request" to dav The issue I'm facing is intermittent.

Row: 10
Subject: Data loss
Rule: malformed_fragment
Sentence: Product Search: What's New in 2-3-4-5?

Row: 10
Subject: Data loss
Rule: feedback_website, malformed_fragment
Sentence: Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

Row: 31
Subject: Product compatibility
Rule: seller_transaction
Sentence: The seller has sold the item for $29.89.

Row: 98
Subject: Refund request
Rule: shipping_merchandise
Sentence: Please provide the product name, location and shipping address in the Product Overview.

Row: 490
Subject: Display issue
Rule: feedback_website
Sentence: " " In order to avoid this error (via the search engine, we did make some changes with new users and their feedback) a new tab is created I've noticed a sudden decrease in battery life on my Microsoft Office.

Row: 505
Subject: Peripheral compatibility
Rule: supplier_inventory
Sentence: If we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away.

Row: 520
Subject: Software bug
Rule: feedback_website
Sentence: If you have any further feedback, please drop me an email at xanj@comcast.net.

Row: 526
Subject: Display issue
Rule: feedback_website
Sentence: (814353716) Thank you for your feedback.

Row: 530
Subject: Product compatibility
Rule: seller_listing
Sentence: First, look at the seller's web site.

Row: 533
Subject: Product compatibility
Rule: supplier_inventory, source_code_or_log
Sentence: [01:13:12] [Client thread/ERROR] [FML]: Unable to remove a config variable from net.minecraft.inventory.ItemStack I've checked for any available software updates for my LG Smart TV, but there are none.

Row: 745
Subject: Account access
Rule: feedback_website
Sentence: Please send feedback here -V.3.0 This problem started occurring after the recent software update.

Row: 787
Subject: Product compatibility
Rule: seller_listing
Sentence: The product that I purchased from the sellers is not in the product description and the seller won't change it.

Row: 838
Subject: Network problem
Rule: malformed_fragment
Sentence: In the event you have never bought from this site, then the information here and the "Cancel" button have been replaced by "Retain Seller Info".

Row: 916
Subject: Product compatibility
Rule: supplier_inventory
Sentence: If the product is not already stocked, I may need to charge another retail price.

Row: 965
Subject: Hardware issue
Rule: seller_transaction
Sentence: If you were the seller, please add a check to that transaction to make sure you're actually paying for the merchandise.

Row: 1002
Subject: Data loss
Rule: supplier_inventory, source_code_or_log
Sentence: */ d-> errno = 0 ; /* * This function returns the product * from the inventory of the item I'm unable to find the option to perform the desired action in the LG Smart TV.

Row: 1128
Subject: Payment issue
Rule: supplier_inventory
Sentence: — the product The product is not an item in your inventory.

Row: 1128
Subject: Payment issue
Rule: supplier_inventory
Sentence: If you have an item that is not an item in your inventory, you may contact us I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.

Row: 1155
Subject: Payment issue
Rule: supplier_inventory
Sentence: When we are the only supplier to provide this service I've tried clearing the cache and data for the Sony PlayStation app, but the issue persists.

Row: 1219
Subject: Peripheral compatibility
Rule: supplier_inventory
Sentence: (4) The supplier's description is correct, the purchaser's name is accurate and there is no warranty.

Row: 1291
Subject: Peripheral compatibility
Rule: supplier_inventory
Sentence: The product_purchased contains all our products and our services are the exclusive property of our supplier, our distributors, and our respective affiliates I'm concerned about the security of my iPhone and would like to ensure that my data is safe.

Row: 1435
Subject: Peripheral compatibility
Rule: supplier_inventory
Sentence: We had been searching through the inventory at the tankers that were shipped overseas (We I've recently updated the firmware of my Sony Xperia, and the issue started happening afterward.

Row: 1457
Subject: Refund request
Rule: feedback_website
Sentence: By following the instructions with a single click, or by using an existing search engine?

Row: 1513
Subject: Battery life
Rule: supplier_inventory
Sentence: It's kind of difficult, but I found one in my inventory in This problem started occurring after the recent software update.

Row: 1577
Subject: Delivery problem
Rule: feedback_website
Sentence: How do you respond to feedback about products that aren't listed?

Row: 1603
Subject: Battery life
Rule: seller_transaction
Sentence: It's probably a good idea to use the product information you get from the seller before sending the invoice.

Row: 1618
Subject: Refund request
Rule: source_code_or_log
Sentence: [0:01:01] [Server thread/ERROR] [FML/]: Unable to add plugin for class [PLACEHOLDER] I rely heavily on my Dell XPS for my daily tasks, and this issue is hindering my productivity.

Row: 1736
Subject: Product setup
Rule: seller_transaction
Sentence: [B]Please contact the seller when available and confirm purchase will begin.

Row: 1742
Subject: Payment issue
Rule: feedback_website
Sentence: If you see any, please message me in the feedback section.

Row: 1801
Subject: Network problem
Rule: supplier_inventory
Sentence: [26:22:17] [Client thread/INFO] [SettlingCocoa]: The last few steps of the mod update the inventory recipe for The issue I'm facing is intermittent.

Row: 1834
Subject: Installation support
Rule: feedback_website
Sentence: Read more Tests and feedback help determine correct or incorrect configuration of an I've noticed a peculiar error message popping up on my Apple AirPods screen.

Row: 1938
Subject: Product compatibility
Rule: supplier_inventory
Sentence: If you are a supplier with another phone or tablet, please refer to our Contact Us page for specific terms and conditions.

Row: 1991
Subject: Display issue
Rule: source_code_or_log
Sentence: [22:30:43.711] [Server thread/DEBUG] [FML/]: Located mcmod.info file in file mcmod-1.

Row: 1994
Subject: Peripheral compatibility
Rule: source_code_or_log
Sentence: [14:17:55] [Client thread/ERROR]: [CHAT] G4Z [Nerf]: [URL] The issue I'm facing is intermittent.

======================================================================
COMPLETE TICKETS WITH CANDIDATE CONTAMINATION
======================================================================

--- Ticket row 0 ---
Subject: Product setup
Description: I'm having an issue with the GoPro Hero. Please assist. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 3 ---
Subject: Account access
Description: I'm having an issue with the Microsoft Office. Please assist. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---
Subject: Data loss
Description: I'm having an issue with the Autodesk AutoCAD. Please assist. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 7 ---
Subject: Battery life
Description: I'm having an issue with the Philips Hue Lights. Please assist. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 9 ---
Subject: Payment issue
Description: My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this? If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 10 ---
Subject: Data loss
Description: I'm having an issue with the Nintendo Switch. Please assist. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

--- Ticket row 31 ---
Subject: Product compatibility
Description: I'm having an issue with the GoPro Action Camera. Please assist. The seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 98 ---
Subject: Refund request
Description: I'm having an issue with the Samsung Galaxy. Please assist. Please provide the product name, location and shipping address in the Product Overview. This message will be unread for 12 seconds. I've recently updated the firmware of my Samsung Galaxy, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 490 ---
Subject: Display issue
Description: I'm having an issue with the Microsoft Office. Please assist. " " In order to avoid this error (via the search engine, we did make some changes with new users and their feedback) a new tab is created I've noticed a sudden decrease in battery life on my Microsoft Office. It used to last much longer.

--- Ticket row 505 ---
Subject: Peripheral compatibility
Description: I'm having an issue with the Philips Hue Lights. Please assist. If we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away. Sorry for the inconvenience I'm unable to find the option to perform the desired action in the Philips Hue Lights. Could you please guide me through the steps?

--- Ticket row 520 ---
Subject: Software bug
Description: I'm having an issue with the LG Smart TV. Please assist. If you have any further feedback, please drop me an email at xanj@comcast.net. [This post has been updated.] I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 526 ---
Subject: Display issue
Description: I'm having an issue with the Bose QuietComfort. Please assist. (814353716) Thank you for your feedback. (16791812) Hi everyone! Sorry for having a bad issue so I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 530 ---
Subject: Product compatibility
Description: I'm having an issue with the Apple AirPods. Please assist. I have tried to do some research on various alternatives and it is an easy way to get this right as well. First, look at the seller's web site. I need assistance as soon as possible because it's affecting my work and productivity.

--- Ticket row 533 ---
Subject: Product compatibility
Description: I'm having an issue with the LG Smart TV. Please assist. [01:13:12] [Client thread/ERROR] [FML]: Unable to remove a config variable from net.minecraft.inventory.ItemStack I've checked for any available software updates for my LG Smart TV, but there are none.

--- Ticket row 745 ---
Subject: Account access
Description: I'm having an issue with the Microsoft Surface. Please assist. We can confirm the purchase at the time of purchase, but we need your help to XVI! Please send feedback here -V.3.0 This problem started occurring after the recent software update. I haven't made any other changes to the device.

In [11]:
# ============================================================
# PREPROCESSING RULE 2
# Remove demonstrably unrelated injected content
# ============================================================
#
# Input:
#     description_rule1
#
# Output:
#     description_rule2
#
# Rule 2 operates conservatively at the fragment level.
# It does NOT use Ticket Subject or Ticket Type.
# ============================================================

import re
import pandas as pd


def clean_injected_content(text: str) -> str:
    """
    Remove clearly unrelated injected fragments while preserving
    genuine support-ticket information.
    """

    value = str(text)

    # --------------------------------------------------------
    # 1. Remove embedded source-code / Minecraft log fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\[[0-9]{1,2}:\d{2}:\d{2}(?:\.\d+)?\]\s*"
        r"\[[^\]]+\]\s*"
        r"\[[^\]]+\]\s*"
        r".*?(?=(?:I['’]?m|I've|I am|The issue|"
        r"This problem|I've noticed|I'm experiencing|"
        r"I've tried|I need|I suspect|I rely|"
        r"I['’]?ve performed|$))",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Common source-code fragments
    value = re.sub(
        r"/\*.*?\*/",
        "",
        value,
        flags=re.DOTALL,
    )

    value = re.sub(
        r"\b(?:errno\s*=\s*0|"
        r"net\.minecraft\.inventory\.ItemStack|"
        r"\[FML/?\])",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 2. Remove explicit malformed injected fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bProduct Search:\s*What's New in 2-3-4-5\?",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bReport Feedback Customer Service is your best\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bplease send a ['\"]request['\"] to\s+\w+",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bRetain Seller Info\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 3. Remove clearly unrelated seller / marketplace fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bThe seller has sold the item for \$[\d,.]+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller is not responsible for any damages "
        r"arising out of the delivery of the battleground game\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease have the game in good condition and shipped to you\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bFirst, look at the seller['’]?s web site\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 4. Remove clearly unrelated supplier / inventory fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\(?Thanks\)? I will contact all my suppliers and confirm\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease try and find out whether their inventory is "
        r"currently stocked, or any other reason\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 5. Remove isolated feedback / website injection
    # --------------------------------------------------------

    value = re.sub(
        r"\bWe appreciate that you have requested a website address\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have a problem you're interested in and I'd love "
        r"to see this happen, please check out the Feedback\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have any further feedback, please drop me an "
        r"email at [A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease send feedback here -V\.3\.0\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 6. Remove clearly unrelated supplier/seller fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bWhen we are the only supplier to provide this service\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf we can't keep this up, and the supplier can't figure "
        r"this out, we should have sent something in this particular "
        r"order right away\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 7. Remove obvious standalone transaction fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bYour billing zip code is:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller says on \d{1,2}/\d{1,2}/\d{2,4}\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 8. Clean whitespace left by removals
    # --------------------------------------------------------

    value = re.sub(r"\s{2,}", " ", value)
    value = re.sub(r"\s+([,.!?])", r"\1", value)

    return value.strip()


# ------------------------------------------------------------
# Apply Rule 2
# ------------------------------------------------------------

df["description_rule2"] = (
    df["description_rule1"]
    .astype(str)
    .apply(clean_injected_content)
)


# ------------------------------------------------------------
# Validation statistics
# ------------------------------------------------------------

df["rule1_char_count"] = df["description_rule1"].str.len()
df["rule2_char_count"] = df["description_rule2"].str.len()

df["rule2_removed_chars"] = (
    df["rule1_char_count"]
    - df["rule2_char_count"]
)

df["rule2_empty"] = (
    df["description_rule2"].str.strip() == ""
)


print("=" * 70)
print("RULE 2 — PREPROCESSING VALIDATION")
print("=" * 70)

print(
    "\nOriginal tickets:",
    len(df)
)

print(
    "Empty after Rule 2:",
    int(df["rule2_empty"].sum())
)

print(
    "Tickets modified by Rule 2:",
    int((df["rule2_removed_chars"] > 0).sum())
)

print(
    "Total characters removed:",
    int(df["rule2_removed_chars"].sum())
)

print(
    "Average characters removed per ticket:",
    round(df["rule2_removed_chars"].mean(), 4)
)


# ------------------------------------------------------------
# Before / after examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RULE 2 BEFORE / AFTER")
print("=" * 70)

modified = df[
    df["rule2_removed_chars"] > 0
].head(20)

for index, row in modified.iterrows():

    print(f"\n--- Ticket row {index} ---")

    print("\nAFTER RULE 1:")
    print(row["description_rule1"])

    print("\nAFTER RULE 2:")
    print(row["description_rule2"])

======================================================================
RULE 2 — PREPROCESSING VALIDATION
======================================================================

Original tickets: 8469
Empty after Rule 2: 0
Tickets modified by Rule 2: 124
Total characters removed: 2036
Average characters removed per ticket: 0.2404

======================================================================
RULE 2 BEFORE / AFTER
======================================================================

--- Ticket row 0 ---

AFTER RULE 1:
I'm having an issue with the GoPro Hero. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 2:
I'm having an issue with the GoPro Hero. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 3 ---

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 2:
I'm having an issue with the Microsoft Office. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---

AFTER RULE 1:
I'm having an issue with the Autodesk AutoCAD. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

AFTER RULE 2:
I'm having an issue with the Autodesk AutoCAD. Note: I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 7 ---

AFTER RULE 1:
I'm having an issue with the Philips Hue Lights. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

AFTER RULE 2:
I'm having an issue with the Philips Hue Lights. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 9 ---

AFTER RULE 1:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

AFTER RULE 2:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. If we can, The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 10 ---

AFTER RULE 1:
I'm having an issue with the Nintendo Switch. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

AFTER RULE 2:
I'm having an issue with the Nintendo Switch. 1- [PHONE]. I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

--- Ticket row 19 ---

AFTER RULE 1:
I'm having an issue with the Canon EOS. I'm having an issue with the product_purchased . Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my Canon EOS, but there are none.

AFTER RULE 2:
I'm having an issue with the Canon EOS. I'm having an issue with the product_purchased. Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my Canon EOS, but there are none.

--- Ticket row 31 ---

AFTER RULE 1:
I'm having an issue with the GoPro Action Camera. The seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 2:
I'm having an issue with the GoPro Action Camera. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 49 ---

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at [PHONE] . I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

AFTER RULE 2:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at [PHONE]. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

--- Ticket row 108 ---

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. " , " [URL] " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. ", " [URL] " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

--- Ticket row 118 ---

AFTER RULE 1:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion . 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 2:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion. 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 131 ---

AFTER RULE 1:
I'm having an issue with the LG Smart TV. I'm having an issue with the product_purchased . " User Info: zerogel zerogel 3 years ago I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

AFTER RULE 2:
I'm having an issue with the LG Smart TV. I'm having an issue with the product_purchased. " User Info: zerogel zerogel 3 years ago I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

--- Ticket row 153 ---

AFTER RULE 1:
I'm having an issue with the GoPro Action Camera. #4: The product. #5: GoPro Action Camera . #6: "Vaporizer": GoPro Action Camera . I've tried using different cables, adapters, or peripherals with my GoPro Action Camera, but the issue persists.

AFTER RULE 2:
I'm having an issue with the GoPro Action Camera. #4: The product. #5: GoPro Action Camera. #6: "Vaporizer": GoPro Action Camera. I've tried using different cables, adapters, or peripherals with my GoPro Action Camera, but the issue persists.

--- Ticket row 164 ---

AFTER RULE 1:
I'm having an issue with the HP Pavilion. I'm having an issue with the product_purchased . I'm having an issue with the product_purchased . This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the HP Pavilion. I'm having an issue with the product_purchased. I'm having an issue with the product_purchased. This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 221 ---

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm having an issue with the product_purchased . Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm having an issue with the product_purchased. Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

--- Ticket row 478 ---

AFTER RULE 1:
I'm having an issue with the Lenovo ThinkPad. The seller says on 3/1/16 The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 505 ---

AFTER RULE 1:
I'm having an issue with the Philips Hue Lights. If we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away. Sorry for the inconvenience I'm unable to find the option to perform the desired action in the Philips Hue Lights.

AFTER RULE 2:
I'm having an issue with the Philips Hue Lights. Sorry for the inconvenience I'm unable to find the option to perform the desired action in the Philips Hue Lights.

--- Ticket row 507 ---

AFTER RULE 1:
I'm having an issue with the LG Washing Machine. I'm having an issue with the . This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the LG Washing Machine. I'm having an issue with the. This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 516 ---

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. I get the exact same problem as the product I bought today, the same Dyson Vacuum Cleaner . I can't find the item in my Dyson Vacuum Cleaner This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. I get the exact same problem as the product I bought today, the same Dyson Vacuum Cleaner. I can't find the item in my Dyson Vacuum Cleaner This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- Ticket row 520 ---

AFTER RULE 1:
I'm having an issue with the LG Smart TV. If you have any further feedback, please drop me an email at xanj@comcast.net. [This post has been updated.] I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

AFTER RULE 2:
I'm having an issue with the LG Smart TV. [This post has been updated.] I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

In [12]:
# ============================================================
# PREPROCESSING RULE 2 — REVISED
# Remove clearly unrelated injected content
# ============================================================
#
# Input:
#     description_rule1
#
# Output:
#     description_rule2
#
# Rule 2 is intentionally conservative.
# It removes known contamination fragments while preserving
# genuine support-ticket information.
# ============================================================

import re


def clean_injected_content(text: str) -> str:
    value = str(text)

    # --------------------------------------------------------
    # 1. Remove explicit source-code / game-log contamination
    # --------------------------------------------------------

    value = re.sub(
        r"\[[0-9]{1,2}:\d{2}:\d{2}(?:\.\d+)?\]"
        r"\s*\[[^\]]+\]"
        r"(?:\s*\[[^\]]+\])?"
        r"\s*"
        r".*?(?="
        r"\b(?:I['’]?m|I['’]?ve|I am|"
        r"I've|I've noticed|I'm experiencing|"
        r"I've checked|I've tried|"
        r"This problem|The issue|"
        r"I suspect|I need|I rely)\b"
        r"|$)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"/\*.*?\*/",
        "",
        value,
        flags=re.DOTALL,
    )

    value = re.sub(
        r"\b(?:errno\s*=\s*0|"
        r"net\.minecraft\.inventory\.ItemStack)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 2. Remove explicit malformed injected fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bProduct Search:\s*What's New in 2-3-4-5\?",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bReport Feedback Customer Service is your best\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bplease send a ['\"]request['\"] to\s+\w+",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bRetain Seller Info\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 3. Remove explicit marketplace contamination
    # --------------------------------------------------------

    value = re.sub(
        r"\bThe seller has sold the item for \$[\d,.]+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller is not responsible for any damages "
        r"arising out of the delivery of the battleground game\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease have the game in good condition and shipped to you\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bFirst, look at the seller['’]?s web site\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 4. Remove explicit supplier / inventory contamination
    # --------------------------------------------------------

    value = re.sub(
        r"\(?Thanks\)? I will contact all my suppliers and confirm\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease try and find out whether their inventory is "
        r"currently stocked, or any other reason\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bWhen we are the only supplier to provide this service\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf we can't keep this up, and the supplier can't figure "
        r"this out, we should have sent something in this particular "
        r"order right away\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 5. Remove explicit feedback / website contamination
    # --------------------------------------------------------

    value = re.sub(
        r"\bWe appreciate that you have requested a website address\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have a problem you're interested in and I'd love "
        r"to see this happen, please check out the Feedback\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have any further feedback, please drop me an "
        r"email at [A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease send feedback here -V\.3\.0\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 6. Remove explicit transaction fragments
    # --------------------------------------------------------

    value = re.sub(
        r"\bYour billing zip code:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bYour billing zip code is:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller says on \d{1,2}/\d{1,2}/\d{2,4}\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 7. Remove obvious metadata/injection labels
    # --------------------------------------------------------

    value = re.sub(
        r"\bCustomer Reviewer:\s*",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bUser Info:\s*"
        r"[A-Za-z0-9_.-]+\s+"
        r"[A-Za-z0-9_.-]+\s+"
        r"\d+\s+years?\s+ago\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\[[A-Z][A-Z0-9_ -]+\]\s*",
        "",
        value,
    )

    # --------------------------------------------------------
    # 8. Remove clearly orphaned contamination prefixes
    # --------------------------------------------------------

    value = re.sub(
        r"\bIf we can,\s*(?=The issue|This problem|"
        r"I['’]?m|I['’]?ve|I am)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI am\s+(?=I['’]?ve|I've|I'm|"
        r"I've performed|I['’]?m experiencing)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bNote:\s*(?=I've|I['’]?ve|I'm|I['’]?m|"
        r"This problem|The issue)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 9. Remove standalone post/comment metadata
    # --------------------------------------------------------

    value = re.sub(
        r"\[This post has been updated\.\]",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 10. Whitespace normalization
    # --------------------------------------------------------

    value = re.sub(r"\s{2,}", " ", value)
    value = re.sub(r"\s+([,.!?])", r"\1", value)

    return value.strip()


# ------------------------------------------------------------
# Apply Rule 2
# ------------------------------------------------------------

df["description_rule2"] = (
    df["description_rule1"]
    .astype(str)
    .apply(clean_injected_content)
)


# ------------------------------------------------------------
# Validation statistics
# ------------------------------------------------------------

df["rule1_char_count"] = df["description_rule1"].str.len()

df["rule2_char_count"] = (
    df["description_rule2"].str.len()
)

df["rule2_removed_chars"] = (
    df["rule1_char_count"]
    - df["rule2_char_count"]
)

df["rule2_empty"] = (
    df["description_rule2"].str.strip() == ""
)


print("=" * 70)
print("RULE 2 — REVISED VALIDATION")
print("=" * 70)

print(
    "\nOriginal tickets:",
    len(df)
)

print(
    "Empty after Rule 2:",
    int(df["rule2_empty"].sum())
)

print(
    "Tickets modified by Rule 2:",
    int((df["rule2_removed_chars"] > 0).sum())
)

print(
    "Total characters removed:",
    int(df["rule2_removed_chars"].sum())
)

print(
    "Average characters removed per ticket:",
    round(
        df["rule2_removed_chars"].mean(),
        4
    )
)


# ------------------------------------------------------------
# Before / after examples
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("RULE 2 BEFORE / AFTER")
print("=" * 70)

modified = df[
    df["rule2_removed_chars"] > 0
].head(20)

for index, row in modified.iterrows():

    print(f"\n--- Ticket row {index} ---")

    print("\nAFTER RULE 1:")
    print(row["description_rule1"])

    print("\nAFTER RULE 2:")
    print(row["description_rule2"])

======================================================================
RULE 2 — REVISED VALIDATION
======================================================================

Original tickets: 8469
Empty after Rule 2: 0
Tickets modified by Rule 2: 1071
Total characters removed: 15837
Average characters removed per ticket: 1.87

======================================================================
RULE 2 BEFORE / AFTER
======================================================================

--- Ticket row 0 ---

AFTER RULE 1:
I'm having an issue with the GoPro Hero. Your billing zip code is: 71701. We appreciate that you have requested a website address. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 2:
I'm having an issue with the GoPro Hero. Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 3 ---

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 2:
I'm having an issue with the Microsoft Office. I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 4 ---

AFTER RULE 1:
I'm having an issue with the Autodesk AutoCAD. Note: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

AFTER RULE 2:
I'm having an issue with the Autodesk AutoCAD. I've noticed a sudden decrease in battery life on my Autodesk AutoCAD. It used to last much longer.

--- Ticket row 7 ---

AFTER RULE 1:
I'm having an issue with the Philips Hue Lights. (Thanks) I will contact all my suppliers and confirm. Please try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

AFTER RULE 2:
I'm having an issue with the Philips Hue Lights. I've performed a factory reset on my Philips Hue Lights, hoping it would resolve the problem, but it didn't help.

--- Ticket row 9 ---

AFTER RULE 1:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

AFTER RULE 2:
My Dyson Vacuum Cleaner is making strange noises and not functioning properly. I suspect there might be a hardware issue. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Ticket row 10 ---

AFTER RULE 1:
I'm having an issue with the Nintendo Switch. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

AFTER RULE 2:
I'm having an issue with the Nintendo Switch. 1-. I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

--- Ticket row 19 ---

AFTER RULE 1:
I'm having an issue with the Canon EOS. I'm having an issue with the product_purchased . Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my Canon EOS, but there are none.

AFTER RULE 2:
I'm having an issue with the Canon EOS. I'm having an issue with the product_purchased. My Husband was able to take an order from Apple I've checked for any available software updates for my Canon EOS, but there are none.

--- Ticket row 31 ---

AFTER RULE 1:
I'm having an issue with the GoPro Action Camera. The seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 2:
I'm having an issue with the GoPro Action Camera. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

--- Ticket row 49 ---

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at [PHONE] . I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

AFTER RULE 2:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

--- Ticket row 51 ---

AFTER RULE 1:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.......................................................1. Visit [URL] I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

AFTER RULE 2:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.......................................................1. Visit I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

--- Ticket row 62 ---

AFTER RULE 1:
I'm having an issue with the Xbox. [CODE_REMOVED]

AFTER RULE 2:
I'm having an issue with the Xbox.

--- Ticket row 64 ---

AFTER RULE 1:
I'm facing a problem with my Microsoft Xbox Controller. The Microsoft Xbox Controller is not turning on. It was working fine until yesterday, but now it doesn't respond. I'm working around this problem by switching off I've noticed a peculiar error message popping up on my Microsoft Xbox Controller screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm facing a problem with my Microsoft Xbox Controller. The Microsoft Xbox Controller is not turning on. It was working fine until yesterday, but now it doesn't respond. I'm working around this problem by switching off I've noticed a peculiar error message popping up on my Microsoft Xbox Controller screen. It says ''.

--- Ticket row 65 ---

AFTER RULE 1:
There seems to be a glitch in the Apple AirPods software. It freezes frequently, making it difficult to use. "I'd love to do this on my own. It's a I've noticed a peculiar error message popping up on my Apple AirPods screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
There seems to be a glitch in the Apple AirPods software. It freezes frequently, making it difficult to use. "I'd love to do this on my own. It's a I've noticed a peculiar error message popping up on my Apple AirPods screen. It says ''.

--- Ticket row 70 ---

AFTER RULE 1:
I've accidentally deleted important data from my Google Pixel. Is there any way to recover the deleted files? What about my [PLACEHOLDER] files? The Google Pixel is the I'm using the original charger that came with my Google Pixel, but it's not charging properly.

AFTER RULE 2:
I've accidentally deleted important data from my Google Pixel. Is there any way to recover the deleted files? What about my files? The Google Pixel is the I'm using the original charger that came with my Google Pixel, but it's not charging properly.

--- Ticket row 73 ---

AFTER RULE 1:
My Fitbit Charge is making strange noises and not functioning properly. I suspect there might be a hardware issue. This is a product that must fit in a box. Please let me I've noticed a peculiar error message popping up on my Fitbit Charge screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
My Fitbit Charge is making strange noises and not functioning properly. I suspect there might be a hardware issue. This is a product that must fit in a box. Please let me I've noticed a peculiar error message popping up on my Fitbit Charge screen. It says ''.

--- Ticket row 86 ---

AFTER RULE 1:
I'm having an issue with the Sony PlayStation. * * * @param [PLACEHOLDER]_item * * @return [PLACEHOLDER] @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

AFTER RULE 2:
I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

--- Ticket row 93 ---

AFTER RULE 1:
I'm having an issue with the PlayStation. In-app purchases don't always match up with your new product. In-app purchases are very costly. Make sure you also check if your product is I've noticed a peculiar error message popping up on my PlayStation screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm having an issue with the PlayStation. In-app purchases don't always match up with your new product. In-app purchases are very costly. Make sure you also check if your product is I've noticed a peculiar error message popping up on my PlayStation screen. It says ''.

--- Ticket row 94 ---

AFTER RULE 1:
I'm having an issue with the Microsoft Xbox Controller. [URL] I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 2:
I'm having an issue with the Microsoft Xbox Controller. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Ticket row 95 ---

AFTER RULE 1:
My Autodesk AutoCAD crashed, and I lost all the data stored on it. Is there any way to recover the lost data? Is there any way to recover the lost data? Can it be done remotely from a remote I've noticed a peculiar error message popping up on my Autodesk AutoCAD screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
My Autodesk AutoCAD crashed, and I lost all the data stored on it. Is there any way to recover the lost data? Is there any way to recover the lost data? Can it be done remotely from a remote I've noticed a peculiar error message popping up on my Autodesk AutoCAD screen. It says ''.

--- Ticket row 99 ---

AFTER RULE 1:
I'm having an issue with the Samsung Soundbar. Thank you for your visit. I've noticed a peculiar error message popping up on my Samsung Soundbar screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm having an issue with the Samsung Soundbar. Thank you for your visit. I've noticed a peculiar error message popping up on my Samsung Soundbar screen. It says ''.

In [13]:
# ============================================================
# PREPROCESSING RULE 2 — FINAL PATCH
# Remove clearly unrelated injected content
# while preserving genuine support information
# ============================================================

import re


def clean_injected_content(text: str) -> str:

    value = str(text)

    # --------------------------------------------------------
    # 1. SOURCE CODE / GAME LOGS
    # --------------------------------------------------------

    value = re.sub(
        r"\[[0-9]{1,2}:\d{2}:\d{2}(?:\.\d+)?\]"
        r"\s*\[[^\]]+\]"
        r"(?:\s*\[[^\]]+\])?"
        r"\s*"
        r".*?(?="
        r"\b(?:I['’]?m|I['’]?ve|I am|"
        r"I['’]?ve noticed|"
        r"I['’]?m experiencing|"
        r"I['’]?ve checked|"
        r"I['’]?ve tried|"
        r"This problem|The issue|"
        r"I suspect|I need|I rely)\b"
        r"|$)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # C-style comments
    value = re.sub(
        r"/\*.*?\*/",
        "",
        value,
        flags=re.DOTALL,
    )

    # Common code fragments
    value = re.sub(
        r"\b(?:errno\s*=\s*0|net\.minecraft\.inventory\.ItemStack)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Java/code remnants
    value = re.sub(
        r"\b(?:@param|@return)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bif\s*\([^)]*_[^)]*\)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 2. MALFORMED / NON-SUPPORT CONTENT
    # --------------------------------------------------------

    value = re.sub(
        r"\bProduct Search:\s*What's New in 2-3-4-5\?",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bReport Feedback Customer Service is your best\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bplease send a ['\"]request['\"] to\s+\w+",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bRetain Seller Info\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 3. MARKETPLACE / SELLER INJECTION
    # --------------------------------------------------------

    value = re.sub(
        r"\bThe seller has sold the item for \$[\d,.]+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller is not responsible for any damages arising out of the delivery of the battleground game\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease have the game in good condition and shipped to you\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bFirst, look at the seller['’]?s web site\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bWhen we receive your replacement, we will exchange the item for a full refund or exchange immediately upon\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 4. SUPPLIER / INVENTORY
    # --------------------------------------------------------

    value = re.sub(
        r"\(?Thanks\)? I will contact all my suppliers and confirm\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease try and find out whether their inventory is currently stocked, or any other reason\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bWhen we are the only supplier to provide this service\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 5. FEEDBACK / WEBSITE INJECTION
    # --------------------------------------------------------

    value = re.sub(
        r"\bWe appreciate that you have requested a website address\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bIf you have any further feedback, please drop me an email at [A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bPlease send feedback here -V\.3\.0\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 6. TRANSACTION / BILLING INJECTION
    # --------------------------------------------------------

    value = re.sub(
        r"\bYour billing zip code:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bYour billing zip code is:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bThe seller says on \d{1,2}/\d{1,2}/\d{2,4}\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 7. METADATA INJECTION
    # --------------------------------------------------------

    # Remove label + obvious reviewer fragment
    value = re.sub(
        r"\bCustomer Reviewer:\s*"
        r"(?:My Husband|My Wife|My Friend|My Brother|My Sister|"
        r"My Father|My Mother|My Son|My Daughter)\b"
        r".*?(?=\bI['’]?ve|\bI['’]?m|\bThis problem|\bThe issue)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # User metadata
    value = re.sub(
        r"\bUser Info:\s*"
        r"[A-Za-z0-9_.-]+\s+"
        r"[A-Za-z0-9_.-]+\s+"
        r"\d+\s+years?\s+ago\b",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Post metadata
    value = re.sub(
        r"\[This post has been updated\.\]",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 8. MALFORMED NUMBERED FRAGMENTS
    # --------------------------------------------------------

    # Example: "1- [PHONE] . Product Search..."
    value = re.sub(
        r"\b\d+\s*-\s*(?:\[[A-Z_]+\])?\s*\.?",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Example: "#4: The product. #5: GoPro Action Camera."
    value = re.sub(
        r"#\d+\s*:\s*[^#.!?]*(?:[.!?]|$)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 9. PLACEHOLDER HANDLING
    # --------------------------------------------------------

    # Remove complete sentence whose only useful content
    # is a placeholder.
    value = re.sub(
        r"\bIt says\s*['\"]?\s*\[PLACEHOLDER\]\s*['\"]?\s*\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Remove placeholder token while preserving sentence.
    value = re.sub(
        r"\[PLACEHOLDER\]",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 10. GENERIC MALFORMED PRODUCT VARIABLE
    # --------------------------------------------------------

    value = re.sub(
        r"\bI'm having an issue with the\s+product_purchased\s*\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI'm having an issue with the\s*\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 11. REMAINING ORPHAN PREFIXES
    # --------------------------------------------------------

    value = re.sub(
        r"\bIf we can,\s*(?=The issue|This problem|I['’]?m|I['’]?ve|I am)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI am\s+(?=I['’]?ve|I['’]?m|I've performed|I['’]?m experiencing)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bNote:\s*(?=I've|I['’]?ve|I'm|I['’]?m|This problem|The issue)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 12. URL / PHONE PLACEHOLDER CLEANUP
    # --------------------------------------------------------

    # Remove explicit URL placeholder.
    value = re.sub(
        r"\[URL\]",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Remove phone placeholder only.
    # Do NOT remove surrounding support sentence.
    value = re.sub(
        r"\[PHONE\]",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # --------------------------------------------------------
    # 13. WHITESPACE / PUNCTUATION
    # --------------------------------------------------------

    value = re.sub(
        r"\s{2,}",
        " ",
        value,
    )

    value = re.sub(
        r"\s+([,.!?])",
        r"\1",
        value,
    )

    value = re.sub(
        r"\.{2,}",
        ".",
        value,
    )

    # Remove empty quote artifacts
    value = re.sub(
        r"['\"]{2,}",
        "",
        value,
    )

    # Remove repeated punctuation
    value = re.sub(
        r"\s+\.",
        ".",
        value,
    )

    return value.strip()

In [14]:
df["description_rule2_final"] = (
    df["description_rule1"]
    .astype(str)
    .apply(clean_injected_content)
)

df["rule2_final_empty"] = (
    df["description_rule2_final"].str.strip() == ""
)

df["rule2_final_char_count"] = (
    df["description_rule2_final"].str.len()
)

df["rule2_final_removed_chars"] = (
    df["description_rule1"].str.len()
    - df["rule2_final_char_count"]
)

print("=" * 70)
print("RULE 2 — FINAL PATCH VALIDATION")
print("=" * 70)

print("\nOriginal tickets:", len(df))

print(
    "Empty after Rule 2:",
    int(df["rule2_final_empty"].sum())
)

print(
    "Tickets modified by Rule 2:",
    int((df["rule2_final_removed_chars"] > 0).sum())
)

print(
    "Total characters removed:",
    int(df["rule2_final_removed_chars"].sum())
)

print(
    "Average characters removed per ticket:",
    round(df["rule2_final_removed_chars"].mean(), 4)
)

======================================================================
RULE 2 — FINAL PATCH VALIDATION
======================================================================

Original tickets: 8469
Empty after Rule 2: 0
Tickets modified by Rule 2: 1368
Total characters removed: 25305
Average characters removed per ticket: 2.988

In [15]:
check_rows = [
    10, 19, 31, 49, 51,
    64, 65, 70, 73,
    86, 93, 95, 99,
    108, 118, 131, 153,
    164, 221, 478, 505,
    507, 516, 520
]

for index in check_rows:

    print("\n" + "=" * 70)
    print(f"TICKET ROW {index}")
    print("=" * 70)

    print("\nAFTER RULE 1:")
    print(df.loc[index, "description_rule1"])

    print("\nAFTER RULE 2:")
    print(df.loc[index, "description_rule2_final"])

======================================================================
TICKET ROW 10
======================================================================

AFTER RULE 1:
I'm having an issue with the Nintendo Switch. 1- [PHONE] . Product Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

AFTER RULE 2:
I'm having an issue with the Nintendo Switch. I'm using the original charger that came with my Nintendo Switch, but it's not charging properly.

======================================================================
TICKET ROW 19
======================================================================

AFTER RULE 1:
I'm having an issue with the Canon EOS. I'm having an issue with the product_purchased . Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my Canon EOS, but there are none.

AFTER RULE 2:
I'm having an issue with the Canon EOS. I've checked for any available software updates for my Canon EOS, but there are none.

======================================================================
TICKET ROW 31
======================================================================

AFTER RULE 1:
I'm having an issue with the GoPro Action Camera. The seller has sold the item for $29.89. When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon I've already contacted customer support multiple times, but the issue remains unresolved.

AFTER RULE 2:
I'm having an issue with the GoPro Action Camera. I've already contacted customer support multiple times, but the issue remains unresolved.

======================================================================
TICKET ROW 49
======================================================================

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at [PHONE] . I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

AFTER RULE 2:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

======================================================================
TICKET ROW 51
======================================================================

AFTER RULE 1:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.......................................................1. Visit [URL] I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

AFTER RULE 2:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.1. Visit I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

======================================================================
TICKET ROW 64
======================================================================

AFTER RULE 1:
I'm facing a problem with my Microsoft Xbox Controller. The Microsoft Xbox Controller is not turning on. It was working fine until yesterday, but now it doesn't respond. I'm working around this problem by switching off I've noticed a peculiar error message popping up on my Microsoft Xbox Controller screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm facing a problem with my Microsoft Xbox Controller. The Microsoft Xbox Controller is not turning on. It was working fine until yesterday, but now it doesn't respond. I'm working around this problem by switching off I've noticed a peculiar error message popping up on my Microsoft Xbox Controller screen.

======================================================================
TICKET ROW 65
======================================================================

AFTER RULE 1:
There seems to be a glitch in the Apple AirPods software. It freezes frequently, making it difficult to use. "I'd love to do this on my own. It's a I've noticed a peculiar error message popping up on my Apple AirPods screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
There seems to be a glitch in the Apple AirPods software. It freezes frequently, making it difficult to use. "I'd love to do this on my own. It's a I've noticed a peculiar error message popping up on my Apple AirPods screen.

======================================================================
TICKET ROW 70
======================================================================

AFTER RULE 1:
I've accidentally deleted important data from my Google Pixel. Is there any way to recover the deleted files? What about my [PLACEHOLDER] files? The Google Pixel is the I'm using the original charger that came with my Google Pixel, but it's not charging properly.

AFTER RULE 2:
I've accidentally deleted important data from my Google Pixel. Is there any way to recover the deleted files? What about my files? The Google Pixel is the I'm using the original charger that came with my Google Pixel, but it's not charging properly.

======================================================================
TICKET ROW 73
======================================================================

AFTER RULE 1:
My Fitbit Charge is making strange noises and not functioning properly. I suspect there might be a hardware issue. This is a product that must fit in a box. Please let me I've noticed a peculiar error message popping up on my Fitbit Charge screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
My Fitbit Charge is making strange noises and not functioning properly. I suspect there might be a hardware issue. This is a product that must fit in a box. Please let me I've noticed a peculiar error message popping up on my Fitbit Charge screen.

======================================================================
TICKET ROW 86
======================================================================

AFTER RULE 1:
I'm having an issue with the Sony PlayStation. * * * @param [PLACEHOLDER]_item * * @return [PLACEHOLDER] @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

AFTER RULE 2:
I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

======================================================================
TICKET ROW 93
======================================================================

AFTER RULE 1:
I'm having an issue with the PlayStation. In-app purchases don't always match up with your new product. In-app purchases are very costly. Make sure you also check if your product is I've noticed a peculiar error message popping up on my PlayStation screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm having an issue with the PlayStation. In-app purchases don't always match up with your new product. In-app purchases are very costly. Make sure you also check if your product is I've noticed a peculiar error message popping up on my PlayStation screen.

======================================================================
TICKET ROW 95
======================================================================

AFTER RULE 1:
My Autodesk AutoCAD crashed, and I lost all the data stored on it. Is there any way to recover the lost data? Is there any way to recover the lost data? Can it be done remotely from a remote I've noticed a peculiar error message popping up on my Autodesk AutoCAD screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
My Autodesk AutoCAD crashed, and I lost all the data stored on it. Is there any way to recover the lost data? Is there any way to recover the lost data? Can it be done remotely from a remote I've noticed a peculiar error message popping up on my Autodesk AutoCAD screen.

======================================================================
TICKET ROW 99
======================================================================

AFTER RULE 1:
I'm having an issue with the Samsung Soundbar. Thank you for your visit. I've noticed a peculiar error message popping up on my Samsung Soundbar screen. It says '[PLACEHOLDER]'.

AFTER RULE 2:
I'm having an issue with the Samsung Soundbar. Thank you for your visit. I've noticed a peculiar error message popping up on my Samsung Soundbar screen.

======================================================================
TICKET ROW 108
======================================================================

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. " , " [URL] " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

======================================================================
TICKET ROW 118
======================================================================

AFTER RULE 1:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion . 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

AFTER RULE 2:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion. 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

======================================================================
TICKET ROW 131
======================================================================

AFTER RULE 1:
I'm having an issue with the LG Smart TV. I'm having an issue with the product_purchased . " User Info: zerogel zerogel 3 years ago I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

AFTER RULE 2:
I'm having an issue with the LG Smart TV. " I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

======================================================================
TICKET ROW 153
======================================================================

AFTER RULE 1:
I'm having an issue with the GoPro Action Camera. #4: The product. #5: GoPro Action Camera . #6: "Vaporizer": GoPro Action Camera . I've tried using different cables, adapters, or peripherals with my GoPro Action Camera, but the issue persists.

AFTER RULE 2:
I'm having an issue with the GoPro Action Camera. I've tried using different cables, adapters, or peripherals with my GoPro Action Camera, but the issue persists.

======================================================================
TICKET ROW 164
======================================================================

AFTER RULE 1:
I'm having an issue with the HP Pavilion. I'm having an issue with the product_purchased . I'm having an issue with the product_purchased . This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the HP Pavilion. This problem started occurring after the recent software update. I haven't made any other changes to the device.

======================================================================
TICKET ROW 221
======================================================================

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm having an issue with the product_purchased . Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

======================================================================
TICKET ROW 478
======================================================================

AFTER RULE 1:
I'm having an issue with the Lenovo ThinkPad. The seller says on 3/1/16 The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

======================================================================
TICKET ROW 505
======================================================================

AFTER RULE 1:
I'm having an issue with the Philips Hue Lights. If we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away. Sorry for the inconvenience I'm unable to find the option to perform the desired action in the Philips Hue Lights.

AFTER RULE 2:
I'm having an issue with the Philips Hue Lights. Sorry for the inconvenience I'm unable to find the option to perform the desired action in the Philips Hue Lights.

======================================================================
TICKET ROW 507
======================================================================

AFTER RULE 1:
I'm having an issue with the LG Washing Machine. I'm having an issue with the . This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the LG Washing Machine. This problem started occurring after the recent software update. I haven't made any other changes to the device.

======================================================================
TICKET ROW 516
======================================================================

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. I get the exact same problem as the product I bought today, the same Dyson Vacuum Cleaner . I can't find the item in my Dyson Vacuum Cleaner This problem started occurring after the recent software update. I haven't made any other changes to the device.

AFTER RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. I get the exact same problem as the product I bought today, the same Dyson Vacuum Cleaner. I can't find the item in my Dyson Vacuum Cleaner This problem started occurring after the recent software update. I haven't made any other changes to the device.

======================================================================
TICKET ROW 520
======================================================================

AFTER RULE 1:
I'm having an issue with the LG Smart TV. If you have any further feedback, please drop me an email at xanj@comcast.net. [This post has been updated.] I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

AFTER RULE 2:
I'm having an issue with the LG Smart TV. I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

In [16]:
# ============================================================
# RULE 2 — FINAL TARGETED ARTIFACT CLEANUP
# ============================================================

# 1. Remove malformed refund/call fragment
value = re.sub(
    r"\bOtherwise,\s*please call us at\.",
    "",
    value,
    flags=re.IGNORECASE,
)

# 2. Remove orphan "I'm having an issue with the"
value = re.sub(
    r"\bI'm having an issue with the\s+(?=I'm concerned|This problem|The issue|$)",
    "",
    value,
    flags=re.IGNORECASE,
)

# 3. Remove orphan URL instruction
value = re.sub(
    r"\b\d+\.\s*Visit\s*(?=I've|I'm|The|This|I\b)",
    "",
    value,
    flags=re.IGNORECASE,
)

# 4. Remove remaining obvious code annotation residue
value = re.sub(
    r"\*+\s*@param\s+_?\w+\s*\*+\s*@return\s*@\*/\)?",
    "",
    value,
    flags=re.IGNORECASE,
)

# 5. Remove obvious blockchain injection
value = re.sub(
    r'["\']\s*,\s*["\']\s*;\s*Here,\s*we\s+can\s+fetch\s+a\s+blockchain\b',
    "",
    value,
    flags=re.IGNORECASE,
)

# 6. Remove boilerplate attached to previous sentence
value = re.sub(
    r"(?i)\bPavilion\.Please assist\.",
    "Pavilion.",
    value,
)

# 7. Remove orphan quotation artifact
value = re.sub(
    r'\.\s*"\s+(?=I\'ve|I\'m|This|The)',
    ". ",
    value,
)

# 8. Remove duplicated generic support instruction
value = re.sub(
    r"\bContact customer support\.\s*Contact customer support\.",
    "",
    value,
    flags=re.IGNORECASE,
)

# 9. Remove orphan generic fragment
value = re.sub(
    r"\bI'm having an issue with some\s+(?=I'm unable|I['’]m unable|The issue|This problem)",
    "",
    value,
    flags=re.IGNORECASE,
)

# 10. Remove broken fragment observed in row 478
value = re.sub(
    r"\bThe base plate and the\s+['\"]C['\"]\s+on\b",
    "",
    value,
    flags=re.IGNORECASE,
)

# 11. Final whitespace / punctuation cleanup
value = re.sub(r"\s{2,}", " ", value)
value = re.sub(r"\s+([,.!?])", r"\1", value)
value = re.sub(r"\.{2,}", ".", value)
value = value.strip()

In [17]:
print("=" * 70)
print("RULE 2 — FINAL ACCEPTANCE CHECK")
print("=" * 70)

print("Original tickets:", len(df))

print(
    "Empty after Rule 2:",
    int((df["description_rule2_final"].str.strip() == "").sum())
)

print(
    "Modified tickets:",
    int((df["description_rule2_final"] != df["description_rule1"]).sum())
)

print(
    "Characters removed:",
    int(
        (
            df["description_rule1"].str.len()
            - df["description_rule2_final"].str.len()
        ).sum()
    )
)

======================================================================
RULE 2 — FINAL ACCEPTANCE CHECK
======================================================================
Original tickets: 8469
Empty after Rule 2: 0
Modified tickets: 1368
Characters removed: 25305

In [18]:
final_check_rows = [
    49, 51, 86, 108, 118,
    131, 221, 478
]

for index in final_check_rows:

    print("\n" + "=" * 70)
    print(f"TICKET ROW {index}")
    print("=" * 70)

    print("\nAFTER RULE 1:")
    print(df.loc[index, "description_rule1"])

    print("\nFINAL RULE 2:")
    print(df.loc[index, "description_rule2_final"])

======================================================================
TICKET ROW 49
======================================================================

AFTER RULE 1:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at [PHONE] . I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

FINAL RULE 2:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

======================================================================
TICKET ROW 51
======================================================================

AFTER RULE 1:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.......................................................1. Visit [URL] I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

FINAL RULE 2:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.1. Visit I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

======================================================================
TICKET ROW 86
======================================================================

AFTER RULE 1:
I'm having an issue with the Sony PlayStation. * * * @param [PLACEHOLDER]_item * * @return [PLACEHOLDER] @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

FINAL RULE 2:
I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

======================================================================
TICKET ROW 108
======================================================================

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. " , " [URL] " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

FINAL RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

======================================================================
TICKET ROW 118
======================================================================

AFTER RULE 1:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion . 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

FINAL RULE 2:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion. 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

======================================================================
TICKET ROW 131
======================================================================

AFTER RULE 1:
I'm having an issue with the LG Smart TV. I'm having an issue with the product_purchased . " User Info: zerogel zerogel 3 years ago I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

FINAL RULE 2:
I'm having an issue with the LG Smart TV. " I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

======================================================================
TICKET ROW 221
======================================================================

AFTER RULE 1:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm having an issue with the product_purchased . Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

FINAL RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

======================================================================
TICKET ROW 478
======================================================================

AFTER RULE 1:
I'm having an issue with the Lenovo ThinkPad. The seller says on 3/1/16 The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

FINAL RULE 2:
I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

In [19]:
# ============================================================
# FINAL TARGETED ARTIFACT CLEANUP
# ============================================================

# Row 49 — remove broken phone/call fragment
value = re.sub(
    r"Otherwise,\s*please call us at\.",
    "",
    value,
    flags=re.IGNORECASE,
)

# Row 49 — remove incomplete generic opening
value = re.sub(
    r"\bI'm having an issue with the\s+(?=I'm concerned\b)",
    "",
    value,
    flags=re.IGNORECASE,
)


# Row 51 — remove the entire leftover "1. Visit" fragment
value = re.sub(
    r"\.{2,}\s*\d+\.\s*Visit\s*",
    ". ",
    value,
    flags=re.IGNORECASE,
)


# Row 86 — remove remaining code annotation residue
value = re.sub(
    r"\*+\s*@param\s*_?\w+\s*\*+\s*@return\s*@\*/\)?",
    "",
    value,
    flags=re.IGNORECASE,
)


# Row 108 — remove obvious blockchain injection
value = re.sub(
    r'["\']\s*,\s*["\']\s*["\']?\s*;\s*Here,\s*we\s+can\s+fetch\s+a\s+blockchain\b',
    "",
    value,
    flags=re.IGNORECASE,
)


# Row 118 — separate attached "Please assist."
value = re.sub(
    r"(?i)(Pavilion)\.Please assist\.",
    r"\1.",
    value,
)


# Row 131 — remove orphan quotation left by metadata removal
value = re.sub(
    r"\.\s*\"\s*(?=I've recently updated\b)",
    ". ",
    value,
    flags=re.IGNORECASE,
)


# Row 221 — remove duplicated generic support phrase
value = re.sub(
    r"\bContact customer support\.\s*Contact customer support\.",
    "",
    value,
    flags=re.IGNORECASE,
)

# Remove malformed generic fragment before genuine issue
value = re.sub(
    r"\bI'm having an issue with some\s+(?=I'm unable to find\b)",
    "",
    value,
    flags=re.IGNORECASE,
)


# Row 478 — remove clearly truncated injected fragment
value = re.sub(
    r"\bThe base plate and the\s+['\"]C['\"]\s+on\b",
    "",
    value,
    flags=re.IGNORECASE,
)


# Final normalization
value = re.sub(r"\s{2,}", " ", value)
value = re.sub(r"\s+([,.!?])", r"\1", value)
value = re.sub(r"\.{2,}", ".", value)
value = value.strip()

In [20]:
df["description_rule2_final"] = (
    df["description_rule1"]
    .astype(str)
    .apply(clean_injected_content)
)

In [21]:
final_check_rows = [
    49, 51, 86, 108,
    118, 131, 221, 478
]

for index in final_check_rows:

    print("\n" + "=" * 70)
    print(f"TICKET ROW {index}")
    print("=" * 70)

    print("\nFINAL RULE 2:")
    print(df.loc[index, "description_rule2_final"])

======================================================================
TICKET ROW 49
======================================================================

FINAL RULE 2:
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

======================================================================
TICKET ROW 51
======================================================================

FINAL RULE 2:
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.1. Visit I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

======================================================================
TICKET ROW 86
======================================================================

FINAL RULE 2:
I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

======================================================================
TICKET ROW 108
======================================================================

FINAL RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

======================================================================
TICKET ROW 118
======================================================================

FINAL RULE 2:
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion. 2) Add the HP Pavilion.Please assist. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

======================================================================
TICKET ROW 131
======================================================================

FINAL RULE 2:
I'm having an issue with the LG Smart TV. " I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

======================================================================
TICKET ROW 221
======================================================================

FINAL RULE 2:
I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

======================================================================
TICKET ROW 478
======================================================================

FINAL RULE 2:
I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

In [23]:
import re


def clean_injected_content(text: str) -> str:

    value = str(text)

    # ========================================================
    # 1. Clearly unrelated marketplace / seller content
    # ========================================================

    patterns = [

        r"The seller has sold the item for \$[\d,.]+\.",
        
        r"The seller is not responsible for any damages arising out of the delivery of the battleground game\.",

        r"Please have the game in good condition and shipped to you",

        r"First, look at the seller['’]?s web site\.",

        r"When we receive your replacement, we will exchange the item for a full refund or exchange immediately upon",

        r"The seller says on \d{1,2}/\d{1,2}/\d{2,4}",

    ]

    for pattern in patterns:
        value = re.sub(
            pattern,
            "",
            value,
            flags=re.IGNORECASE,
        )


    # ========================================================
    # 2. Supplier / inventory contamination
    # ========================================================

    patterns = [

        r"\(?Thanks\)? I will contact all my suppliers and confirm\.",

        r"Please try and find out whether their inventory is currently stocked, or any other reason\.",

        r"When we are the only supplier to provide this service",

        r"If we can't keep this up, and the supplier can't figure this out, we should have sent something in this particular order right away\.",

    ]

    for pattern in patterns:
        value = re.sub(
            pattern,
            "",
            value,
            flags=re.IGNORECASE,
        )


    # ========================================================
    # 3. Feedback / website contamination
    # ========================================================

    patterns = [

        r"We appreciate that you have requested a website address\.",

        r"If you have a problem you're interested in and I'd love to see this happen, please check out the Feedback\.",

        r"If you have any further feedback, please drop me an email at [A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\.",

        r"Please send feedback here -V\.3\.0",

    ]

    for pattern in patterns:
        value = re.sub(
            pattern,
            "",
            value,
            flags=re.IGNORECASE,
        )


    # ========================================================
    # 4. Billing / transaction contamination
    # ========================================================

    value = re.sub(
        r"Your billing zip code(?: is)?:\s*\d+\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 5. Obvious metadata contamination
    # ========================================================

    value = re.sub(
        r"Customer Reviewer:\s*"
        r"(?:My Husband|My Wife|My Friend|My Brother|My Sister|"
        r"My Father|My Mother|My Son|My Daughter)"
        r".*?(?=I've|I'm|This problem|The issue)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"User Info:\s*"
        r"[A-Za-z0-9_.-]+\s+"
        r"[A-Za-z0-9_.-]+\s+"
        r"\d+\s+years?\s+ago",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\[This post has been updated\.\]",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 6. Source-code contamination
    # ========================================================

    # Remove complete C-style comments
    value = re.sub(
        r"/\*.*?\*/",
        "",
        value,
        flags=re.DOTALL,
    )

    # Remove Java annotation remnants
    value = re.sub(
        r"\*+\s*@param\s+[A-Za-z0-9_]+\s*\*+\s*@return\s*",
        "",
        value,
        flags=re.IGNORECASE,
    )

    # Remove function/code tail observed in corpus
    value = re.sub(
        r"@?\*/?\s*if\s*\(_[A-Za-z0-9_]+\([^)]*\)\)\s*",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\b(?:errno\s*=\s*0|net\.minecraft\.inventory\.ItemStack)\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 7. Placeholder-only error messages
    # ========================================================

    value = re.sub(
        r"\bI've noticed a peculiar error message popping up on "
        r"[^.]+\. It says\s*['\"]?\s*\[PLACEHOLDER\]\s*['\"]?\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 8. Remaining placeholders
    # ========================================================

    value = re.sub(
        r"\[PLACEHOLDER\]",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\[URL\]",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\[PHONE\]",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\[CODE_REMOVED\]",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 9. Malformed product variable
    # ========================================================

    value = re.sub(
        r"\bI'm having an issue with the\s+product_purchased\s*\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI'm having an issue with the\s*\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 10. Malformed numbered fragments
    # ========================================================

    value = re.sub(
        r"\b\d+\s*-\s*(?:\[[A-Z_]+\])?\s*\.?",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"#\d+\s*:\s*[^#.!?]*(?:[.!?]|$)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 11. Known blockchain injection
    # ========================================================

    value = re.sub(
        r'["\']\s*,\s*["\']\s*;\s*Here,\s*we\s+can\s+fetch\s+a\s+blockchain\b',
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 12. Known orphan fragments
    # ========================================================

    value = re.sub(
        r"\bIf we can,\s*(?=The issue|This problem|I'm|I've)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI am\s+(?=I've|I'm)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bNote:\s*(?=I've|I'm|This problem|The issue)",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bI'm having an issue with some\s+(?=I'm unable to find)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 13. Attached generic boilerplate
    # ========================================================

    value = re.sub(
        r"(?i)(Pavilion)\.Please assist\.",
        r"\1.",
        value,
    )

    value = re.sub(
        r"\bContact customer support\.\s*Contact customer support\.",
        "",
        value,
        flags=re.IGNORECASE,
    )

    value = re.sub(
        r"\bOtherwise,\s*please call us at\.",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 14. Broken URL instruction
    # ========================================================

    value = re.sub(
        r"\b\d+\.\s*Visit\s*(?=I've|I'm|The|This|I\b)",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 15. Known broken fragment from row 478
    # ========================================================

    value = re.sub(
        r"\bThe base plate and the\s+['\"]C['\"]\s+on\b",
        "",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 16. Orphan quotation artifacts
    # ========================================================

    value = re.sub(
        r"\.\s*\"\s+(?=I've|I'm|This|The)",
        ". ",
        value,
        flags=re.IGNORECASE,
    )


    # ========================================================
    # 17. Whitespace / punctuation normalization
    # ========================================================

    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    value = re.sub(
        r"\s+([,.!?])",
        r"\1",
        value,
    )

    value = re.sub(
        r"\.{2,}",
        ".",
        value,
    )

    value = value.strip()

    return value

In [24]:
df["description_rule2_final"] = (
    df["description_rule1"]
    .astype(str)
    .apply(clean_injected_content)
)

In [25]:
final_check_rows = [
    49, 51, 86, 108,
    118, 131, 221, 478
]

for index in final_check_rows:

    print("\n" + "=" * 70)
    print(f"TICKET ROW {index}")
    print("=" * 70)

    print(df.loc[index, "description_rule2_final"])

======================================================================
TICKET ROW 49
======================================================================
I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

======================================================================
TICKET ROW 51
======================================================================
I've recently set up my LG Smart TV, but it fails to connect to any available networks. What steps should I take to troubleshoot this issue?.I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

======================================================================
TICKET ROW 86
======================================================================
I'm having an issue with the Sony PlayStation. * * * @param _item * * @return I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.

======================================================================
TICKET ROW 108
======================================================================
I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

======================================================================
TICKET ROW 118
======================================================================
I'm having an issue with the HP Pavilion. 1) Remove the HP Pavilion. 2) Add the HP Pavilion. I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

======================================================================
TICKET ROW 131
======================================================================
I'm having an issue with the LG Smart TV. I've recently updated the firmware of my LG Smart TV, and the issue started happening afterward. Could it be related to the update?

======================================================================
TICKET ROW 221
======================================================================
I'm having an issue with the Dyson Vacuum Cleaner. I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

======================================================================
TICKET ROW 478
======================================================================
I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. This problem started occurring after the recent software update. I haven't made any other changes to the device.

Ticket Description
        ↓
Rule 1
generic boilerplate removal
        ↓
Rule 2
confirmed contamination removal
        ↓
description_rule2_final
        ↓
BERTopic-targeted preprocessing
        ↓
BERTopic

In [26]:
# Final targeted artifact check before saving the BERTopic dataset

artifact_patterns = [
    "@param",
    "@return",
    "blockchain",
    "Otherwise, please call us at.",
    "I'm having an issue with some",
    'The base plate and the "C" on',
    'Here, we can fetch',
]

for pattern in artifact_patterns:
    matches = df[
        df["description_rule2"]
        .astype(str)
        .str.contains(pattern, case=False, regex=False, na=False)
    ]

    if len(matches):
        print(f"\n--- {pattern!r}: {len(matches)} matches ---")
        print(
            matches[["Ticket ID", "description_rule2"]]
            .to_string(index=False)
        )

--- '@param': 6 matches ---
 Ticket ID                                                                                                                                                                                                                                                                 description_rule2
        87                                           I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.
      2876                                              I'm having an issue with the Nintendo Switch. * * @hide * * @param id integer id which can be the ID of all products we will have. This includes I'm unable to find the option to perform the desired action in the Nintendo Switch.
      4383                  I'm having an issue with the Nintendo Switch Pro Controller. * ** * @param psql As MySQL database to query. */ function get_products function set_products [ 2] I'm not sure if this issue is specific to my device or if others have reported similar problems.
      4393 I'm having an issue with the Sony Xperia. * @param product_purchased The product-purchased id of the item. Optional. This item is ignored by your bot if your bot I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony Xperia.
      6518                              I'm having an issue with the Sony PlayStation. */ /** * Return the product * * @param i The product ID * @param price The amount of money to The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
      6805                            I'm having an issue with the Fitbit Versa Smartwatch. * * * @param array of purchased items * @return int */ public void purchase ( int product_size, I'm not sure if this issue is specific to my device or if others have reported similar problems.

--- '@return': 2 matches ---
 Ticket ID                                                                                                                                                                                                                                      description_rule2
        87                I'm having an issue with the Sony PlayStation. * * * @param _item * * @return @*/if (_ejection_exceeds(_proposal)) I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.
      6805 I'm having an issue with the Fitbit Versa Smartwatch. * * * @param array of purchased items * @return int */ public void purchase ( int product_size, I'm not sure if this issue is specific to my device or if others have reported similar problems.

--- 'blockchain': 2 matches ---
 Ticket ID                                                                                                                                                                                                                                                                                                                    description_rule2
       109                                                                                                                                  I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.
      4409 I'm having an issue with the Adobe Photoshop. My phone will be returned for a refund in 30 days, or until I receive compensation once the return policy is fully implemented. I blockchain based on my experience and advice The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- 'Otherwise, please call us at.': 1 matches ---
 Ticket ID                                                                                                                                                                                                                                                              description_rule2
        50 I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. Otherwise, please call us at. I'm having an issue with the I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.

--- "I'm having an issue with some": 1 matches ---
 Ticket ID                                                                                                                                                                                                                                                             description_rule2
       222 I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm having an issue with the product_purchased. Contact customer support. I'm having an issue with some I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.

--- 'The base plate and the "C" on': 1 matches ---
 Ticket ID                                                                                                                                                                                                                       description_rule2
       479 I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. The base plate and the "C" on This problem started occurring after the recent software update. I haven't made any other changes to the device.

--- 'Here, we can fetch': 1 matches ---
 Ticket ID                                                                                                                                                                                   description_rule2
       109 I'm having an issue with the Dyson Vacuum Cleaner. ", " " ; Here, we can fetch a blockchain I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.

In [30]:
import re


def final_rule2_cleanup(text: str) -> str:
    if not text:
        return ""

    text = str(text)

    # ---------------------------------------------------------
    # 1. Remove confirmed code / documentation contamination
    # ---------------------------------------------------------
    code_patterns = [
        r"\*+\s*@param\b.*?(?=I've|I'm|The issue|The problem|I’m|$)",
        r"\*+\s*@return\b.*?(?=I've|I'm|The issue|The problem|I’m|$)",
        r"@hide\b.*?(?=I'm unable|I've|I'm|The issue|$)",
        r"@\*/if\s*\([^)]*\).*?(?=I've|I'm|The issue|The problem|$)",
        r"/\*\*.*?(?=I've|I'm|The issue|The problem|$)",
        r"\bfunction\s+\w+\b.*?(?=I'm|I've|The issue|The problem|$)",
        r"\bget_products\b.*?(?=I'm|I've|The issue|The problem|$)",
        r"\bset_products\b.*?(?=I'm|I've|The issue|The problem|$)",
        r"\bpublic\s+void\s+\w+\s*\(.*?(?=I'm|I've|The issue|The problem|$)",
    ]

    for pattern in code_patterns:
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE | re.DOTALL)

    # ---------------------------------------------------------
    # 2. Remove confirmed blockchain / generated-text fragments
    # ---------------------------------------------------------
    text = re.sub(
        r'"\s*,\s*"\s*"\s*;\s*Here,\s*we\s*can\s*fetch\s+a\s+blockchain',
        " ",
        text,
        flags=re.IGNORECASE,
    )

    # Remove the isolated blockchain injection in Ticket 4409
    text = re.sub(
        r"\bI\s+blockchain\s+based\s+on\s+my\s+experience\s+and\s+advice\b",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 3. Remove confirmed broken / orphan fragments
    # ---------------------------------------------------------
    text = re.sub(
        r"\bOtherwise,\s*please\s*call\s*us\s*at\.",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"\bI'm\s+having\s+an\s+issue\s+with\s+the\s+I'm\s+concerned\b",
        "I'm concerned",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"\bI'm\s+having\s+an\s+issue\s+with\s+the\s+product_purchased\.",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"\bI'm\s+having\s+an\s+issue\s+with\s+some\s+I'm\s+unable\b",
        "I'm unable",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"\bThe\s+base\s+plate\s+and\s+the\s+\"C\"\s+on\b",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 4. Remove orphan quotation marks
    # ---------------------------------------------------------
    text = re.sub(
        r"(?<=\.)\s*\"\s*(?=I've|I'm|The|This|Could|I)",
        " ",
        text,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 5. Remove duplicated generic support sentence
    # ---------------------------------------------------------
    text = re.sub(
        r"(Contact\s+customer\s+support\.)"
        r"(\s*\1)+",
        r"\1",
        text,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 6. Clean whitespace / punctuation artifacts
    # ---------------------------------------------------------
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s+([,.!?])", r"\1", text)
    text = re.sub(r"([.!?])(?=[A-Z])", r"\1 ", text)

    return text.strip()

In [31]:
df["bertopic_text"] = (
    df["description_rule2"]
    .astype(str)
    .apply(final_rule2_cleanup)
)

In [32]:
remaining_patterns = [
    "@param",
    "@return",
    "@hide",
    "blockchain",
    "Here, we can fetch",
    "Otherwise, please call us at.",
    "I'm having an issue with some",
    'The base plate and the "C" on',
    "product_purchased.",
]

for pattern in remaining_patterns:
    matches = df[
        df["bertopic_text"]
        .str.contains(pattern, case=False, regex=False, na=False)
    ]

    print(f"{pattern!r}: {len(matches)} matches")

'@param': 0 matches
'@return': 0 matches
'@hide': 0 matches
'blockchain': 0 matches
'Here, we can fetch': 0 matches
'Otherwise, please call us at.': 0 matches
"I'm having an issue with some": 0 matches
'The base plate and the "C" on': 0 matches
'product_purchased.': 9 matches

In [33]:
check_ids = [50, 87, 109, 222, 2876, 4383, 4393, 4409, 479, 6518, 6805]

df.loc[
    df["Ticket ID"].isin(check_ids),
    ["Ticket ID", "Ticket Subject", "bertopic_text"]
].to_string(index=False)

" Ticket ID           Ticket Subject                                                                                                                                                                                                                                                                         bertopic_text\n        50            Display issue                                                                   I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.\n        87   Product recommendation                                                                                                               I'm having an issue with the Sony PlayStation. * * I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.\n       109            Product setup                                                                                                                            I'm having an issue with the Dyson Vacuum Cleaner. I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.\n       222     Installation support                                                                                                                 I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.\n       479             Software bug                                                                             I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. This problem started occurring after the recent software update. I haven't made any other changes to the device.\n      2876    Product compatibility                                                                                                                                                 I'm having an issue with the Nintendo Switch. * * I'm unable to find the option to perform the desired action in the Nintendo Switch.\n      4383            Product setup                                                                                                                    I'm having an issue with the Nintendo Switch Pro Controller. * ** I'm not sure if this issue is specific to my device or if others have reported similar problems.\n      4393             Software bug                                                                                                                             I'm having an issue with the Sony Xperia. I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony Xperia.\n      4409 Peripheral compatibility I'm having an issue with the Adobe Photoshop. My phone will be returned for a refund in 30 days, or until I receive compensation once the return policy is fully implemented. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.\n      6518         Delivery problem                                                                                                                             I'm having an issue with the Sony PlayStation. */ The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.\n      6805 Peripheral compatibility                                                                                                                            I'm having an issue with the Fitbit Versa Smartwatch. * * I'm not sure if this issue is specific to my device or if others have reported similar problems."

In [34]:
df["bertopic_text"] = (
    df["bertopic_text"]
    .str.replace(r"\*/", " ", regex=True)
    .str.replace(r"\* \* \*", " ", regex=True)
    .str.replace(r"\* \*\*", " ", regex=True)
    .str.replace(r"\* \*", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [35]:
check_ids = [50, 87, 109, 222, 479, 2876, 4383, 4393, 4409, 6518, 6805]

df.loc[
    df["Ticket ID"].isin(check_ids),
    ["Ticket ID", "Ticket Subject", "bertopic_text"]
].to_string(index=False)

" Ticket ID           Ticket Subject                                                                                                                                                                                                                                                                         bertopic_text\n        50            Display issue                                                                   I'm having an issue with the Microsoft Office. If you've received a refund, please contact Customer Service. I'm concerned about the security of my Microsoft Office and would like to ensure that my data is safe.\n        87   Product recommendation                                                                                                                   I'm having an issue with the Sony PlayStation. I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony PlayStation.\n       109            Product setup                                                                                                                            I'm having an issue with the Dyson Vacuum Cleaner. I've noticed a sudden decrease in battery life on my Dyson Vacuum Cleaner. It used to last much longer.\n       222     Installation support                                                                                                                 I'm having an issue with the Dyson Vacuum Cleaner. Contact customer support. I'm unable to find the option to perform the desired action in the Dyson Vacuum Cleaner.\n       479             Software bug                                                                             I'm having an issue with the Lenovo ThinkPad. The base plate is missing a metal bracket. This problem started occurring after the recent software update. I haven't made any other changes to the device.\n      2876    Product compatibility                                                                                                                                                     I'm having an issue with the Nintendo Switch. I'm unable to find the option to perform the desired action in the Nintendo Switch.\n      4383            Product setup                                                                                                                         I'm having an issue with the Nintendo Switch Pro Controller. I'm not sure if this issue is specific to my device or if others have reported similar problems.\n      4393             Software bug                                                                                                                             I'm having an issue with the Sony Xperia. I've noticed that the issue occurs consistently when I use a specific feature or application on my Sony Xperia.\n      4409 Peripheral compatibility I'm having an issue with the Adobe Photoshop. My phone will be returned for a refund in 30 days, or until I receive compensation once the return policy is fully implemented. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.\n      6518         Delivery problem                                                                                                                                I'm having an issue with the Sony PlayStation. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.\n      6805 Peripheral compatibility                                                                                                                                I'm having an issue with the Fitbit Versa Smartwatch. I'm not sure if this issue is specific to my device or if others have reported similar problems."

In [36]:
from pathlib import Path

# Project-level processed-data directory
output_dir = Path("../../../../../data/processed")
output_dir.mkdir(parents=True, exist_ok=True)

# Keep only the information needed for BERTopic modelling
bertopic_dataset = df[
    [
        "Ticket ID",
        "Ticket Subject",
        "Ticket Description",
        "bertopic_text",
    ]
].copy()

output_path = output_dir / "supportmind_bertopic_cleaned_dataset.csv"

bertopic_dataset.to_csv(output_path, index=False)

print("BERTopic dataset saved successfully.")
print(f"Path: {output_path.resolve()}")
print(f"Rows: {len(bertopic_dataset):,}")
print(f"Columns: {list(bertopic_dataset.columns)}")

BERTopic dataset saved successfully.
Path: C:\Users\danie\supportmind-ai\data\processed\supportmind_bertopic_cleaned_dataset.csv
Rows: 8,469
Columns: ['Ticket ID', 'Ticket Subject', 'Ticket Description', 'bertopic_text']

In [37]:
import pandas as pd

text = bertopic_dataset["bertopic_text"].astype(str)

print("Documents:", len(text))
print("Empty:", (text.str.strip() == "").sum())
print("Characters:")
print(text.str.len().describe())
print("\nWords:")
print(text.str.split().str.len().describe())

Documents: 8469
Empty: 0
Characters:
count    8469.000000
mean      252.670799
std        44.935360
min        34.000000
25%       233.000000
50%       263.000000
75%       282.000000
max       364.000000
Name: bertopic_text, dtype: float64

Words:
count    8469.000000
mean       44.421892
std         8.529490
min         7.000000
25%        40.000000
50%        46.000000
75%        51.000000
max        65.000000
Name: bertopic_text, dtype: float64

In [38]:
# BERTopic-targeted residual noise check

patterns = {
    "placeholder": r"\[PLACEHOLDER\]",
    "url": r"https?://|www\.",
    "email": r"\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b",
    "code_marker": r"@param|@return|/\*|\*/|function\s+\w+",
}

for name, pattern in patterns.items():
    count = text.str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{name}: {count:,}")

placeholder: 0
url: 7
email: 72
code_marker: 0

In [39]:
# BERTopic-specific check:
# How much of the corpus contains product information?

product_names = (
    bertopic_dataset["Ticket Description"]
    .astype(str)
    .str.lower()
)

products = (
    df["Product Purchased"]
    .dropna()
    .astype(str)
    .str.lower()
    .unique()
)

product_hits = product_names.apply(
    lambda text: sum(product in text for product in products)
)

print("Documents:", len(product_hits))
print("Documents containing at least one product name:",
      (product_hits > 0).sum())
print("Percentage:",
      round((product_hits > 0).mean() * 100, 2), "%")

Documents: 8469
Documents containing at least one product name: 8469
Percentage: 100.0 %

In [40]:
import re

def prepare_bertopic_text(text: str) -> str:
    text = str(text)

    # Remove URLs
    text = re.sub(
        r"https?://\S+|www\.\S+",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # Remove email addresses
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b",
        " ",
        text
    )

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


bertopic_dataset["bertopic_input"] = (
    bertopic_dataset["bertopic_text"]
    .apply(prepare_bertopic_text)
)

print("Documents:", len(bertopic_dataset))
print(
    "Empty documents:",
    (bertopic_dataset["bertopic_input"].str.strip() == "").sum()
)
print(
    "Mean words:",
    round(
        bertopic_dataset["bertopic_input"]
        .str.split()
        .str.len()
        .mean(),
        2
    )
)

Documents: 8469
Empty documents: 0
Mean words: 44.42

In [41]:
url_remaining = bertopic_dataset["bertopic_input"].str.contains(
    r"https?://|www\.",
    case=False,
    regex=True,
    na=False
).sum()

email_remaining = bertopic_dataset["bertopic_input"].str.contains(
    r"\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b",
    regex=True,
    na=False
).sum()

print("URLs remaining:", url_remaining)
print("Emails remaining:", email_remaining)

URLs remaining: 7
Emails remaining: 0

supportmind_bertopic_cleaned_dataset.csv
              │
              ▼
        bertopic_text
              │
              ▼
     BERTopic preprocessing
       ├─ URLs/emails cleanup
       ├─ whitespace normalization
       ├─ product names preserved
       ├─ issue terminology preserved
       ├─ no stemming
       ├─ no aggressive stopword removal
       └─ no information-destroying cleaning
              │
              ▼
        bertopic_input

In [42]:
import bertopic
import umap
import hdbscan

print("BERTopic:", bertopic.__version__)
print("UMAP:", umap.__version__)
print("HDBSCAN:", hdbscan.__version__ if hasattr(hdbscan, "__version__") else "installed")

c:\Users\danie\anaconda3\envs\supportmind\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

BERTopic: 0.17.4
UMAP: 0.5.12
HDBSCAN: installed

In [43]:
from bertopic import BERTopic

# Prepare modelling corpus
documents = (
    bertopic_dataset["bertopic_input"]
    .astype(str)
    .tolist()
)

print(f"Documents for BERTopic: {len(documents):,}")

Documents for BERTopic: 8,469

In [44]:
topic_model = BERTopic(
    verbose=True
)

topics, probabilities = topic_model.fit_transform(documents)

print("\nBERTopic training completed.")
print(f"Documents: {len(topics):,}")
print(f"Unique topic IDs: {len(set(topics))}")

2026-09-13 23:43:56,108 - BERTopic - Embedding - Transforming documents to embeddings.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1613.33it/s]
Batches: 100%|██████████| 265/265 [03:24<00:00,  1.30it/s]
2026-09-13 23:47:31,200 - BERTopic - Embedding - Completed ✓
2026-09-13 23:47:31,201 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-09-13 23:48:18,177 - BERTopic - Dimensionality - Completed ✓
2026-09-13 23:48:18,177 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-09-13 23:48:18,460 - BERTopic - Cluster - Completed ✓
2026-09-13 23:48:18,466 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-09-13 23:48:19,010 - BERTopic - Representation - Completed ✓

BERTopic training completed.
Documents: 8,469
Unique topic IDs: 176

In [45]:
# Inspect discovered topics

topic_info = topic_model.get_topic_info()

print("Number of topics:", len(topic_info) - 1)  # exclude -1 outlier topic

print("\nTopic information:")
display(
    topic_info.head(30)
)

Number of topics: 175

Topic information:

,Topic,Count,Name,Representation,Representative_Docs
0,-1,692,-1_bug_lg_to_in,"[bug, lg, to, in, my, tv, perform, smart, soft...",[My Sony Xperia is making strange noises and n...
1,0,177,0_charge_fitbit_with_having,"[charge, fitbit, with, having, issue, im, an, ...",[I'm having an issue with the Fitbit Charge. I...
2,1,172,1_playstation_sony_having_issue,"[playstation, sony, having, issue, an, product...",[I'm having an issue with the Sony PlayStation...
3,2,169,2_roomba_robot_vacuum_an,"[roomba, robot, vacuum, an, with, issue, havin...",[I'm having an issue with the Roomba Robot Vac...
4,3,167,3_hp_pavilion_issue_having,"[hp, pavilion, issue, having, an, for, the, an...",[I'm having an issue with the HP Pavilion. 1) ...
5,4,163,4_airpods_apple_product_issue,"[airpods, apple, product, issue, having, with,...",[The Apple AirPods is unable to establish a st...
6,5,163,5_versa_smartwatch_fitbit_but,"[versa, smartwatch, fitbit, but, ive, issue, h...",[I'm having an issue with the Fitbit Versa Sma...
7,6,151,6_nikon_having_an_issue,"[nikon, having, an, issue, with, support, you,...",[I'm having an issue with the Nikon D. I'm hav...
8,7,149,7_galaxy_samsung_having_an,"[galaxy, samsung, having, an, null, issue, wit...",[I'm having an issue with the Samsung Galaxy. ...
9,8,144,8_philips_hue_lights_2k,"[philips, hue, lights, 2k, gaming, an, having,...",[I'm having an issue with the Philips Hue Ligh...
10,9,144,9_washing_machine_lg_please,"[washing, machine, lg, please, having, an, the...",[I'm having an issue with the LG Washing Machi...
11,10,144,10_hero_gopro_having_an,"[hero, gopro, having, an, issue, with, this, i...",[I'm having an issue with the GoPro Hero. I've...
12,11,144,11_dslr_camera_canon_having,"[dslr, camera, canon, having, an, issue, with,...",[I'm having an issue with the Canon DSLR Camer...
13,12,142,12_camera_gopro_action_issue,"[camera, gopro, action, issue, with, an, menti...",[I'm having an issue with the GoPro Action Cam...
14,13,139,13_dell_xps_product_an,"[dell, xps, product, an, for, issue, the, be, ...",[I'm having an issue with the Dell XPS. I've c...
15,14,137,14_quietcomfort_bose_issue_having,"[quietcomfort, bose, issue, having, an, with, ...",[I'm having an issue with the Bose QuietComfor...
16,15,136,15_adobe_photoshop_an_issue,"[adobe, photoshop, an, issue, with, having, im...",[I'm having an issue with the Adobe Photoshop....
17,16,134,16_autodesk_autocad_issue_with,"[autodesk, autocad, issue, with, an, having, t...",[I'm having an issue with the Autodesk AutoCAD...
18,17,133,17_surface_microsoft_after_having,"[surface, microsoft, after, having, recent, th...",[I'm having an issue with the Microsoft Surfac...
19,18,133,18_thermostat_nest_product_name,"[thermostat, nest, product, name, having, issu...",[I'm having an issue with the Nest Thermostat....
20,19,132,19_office_microsoft_issue_an,"[office, microsoft, issue, an, having, the, wi...",[I'm having an issue with the Microsoft Office...
21,20,132,20_thinkpad_lenovo_an_the,"[thinkpad, lenovo, an, the, issue, with, havin...",[I'm having an issue with the Lenovo ThinkPad....
22,21,132,21_macbook_pro_an_having,"[macbook, pro, an, having, with, issue, the, p...",[I'm having an issue with the MacBook Pro. I'v...
23,22,131,22_soundbar_samsung_having_issue,"[soundbar, samsung, having, issue, an, with, i...",[I'm having an issue with the Samsung Soundbar...
24,23,130,23_soundlink_speaker_bose_issue,"[soundlink, speaker, bose, issue, with, an, fo...",[I'm having an issue with the Bose SoundLink S...
25,24,129,24_nintendo_switch_pro_controller,"[nintendo, switch, pro, controller, an, having...",[I'm having an issue with the Nintendo Switch ...
26,25,129,25_kindle_amazon_issue_an,"[kindle, amazon, issue, an, with, having, the,...",[I'm having an issue with the Amazon Kindle. P...
27,26,129,26_cleaner_dyson_vacuum_an,"[cleaner, dyson, vacuum, an, having, issue, fo...",[I'm having an issue with the Dyson Vacuum Cle...
28,27,124,27_rog_asus_issue_an,"[rog, asus, issue, an, or, having, with, produ...",[I'm having an issue with the Asus ROG. C: I'v...
29,28,122,28_iphone_having_this_an,"[iphone, having, this, an, issue, with, you, p...",[I'm having an issue with the iPhone. I rely h...

In [46]:
# Inspect top words for the largest discovered topics

for topic_id in topic_info[
    topic_info["Topic"] != -1
].head(10)["Topic"]:

    print(f"\nTopic {topic_id}")
    print(topic_model.get_topic(topic_id))

Topic 0
[('charge', np.float64(0.0769716075843485)), ('fitbit', np.float64(0.05972882746172755)), ('with', np.float64(0.006497160146027033)), ('having', np.float64(0.00583766911444087)), ('issue', np.float64(0.005771757951604101)), ('im', np.float64(0.005755521820265863)), ('an', np.float64(0.005630318353422354)), ('the', np.float64(0.0055453558470575405)), ('tried', np.float64(0.005266643843271305)), ('this', np.float64(0.005224490113397775))]

Topic 1
[('playstation', np.float64(0.05306320202852142)), ('sony', np.float64(0.020753514965509777)), ('having', np.float64(0.007241854855300477)), ('issue', np.float64(0.007015902786404935)), ('an', np.float64(0.006876155161590296)), ('product', np.float64(0.006755877525834386)), ('support', np.float64(0.006700777170452235)), ('already', np.float64(0.006367661893997486)), ('with', np.float64(0.006326479212968138)), ('the', np.float64(0.006243746771102185))]

Topic 2
[('roomba', np.float64(0.0717562984044866)), ('robot', np.float64(0.0717562984044866)), ('vacuum', np.float64(0.05263559556882593)), ('an', np.float64(0.005975385942816276)), ('with', np.float64(0.005836195525078369)), ('issue', np.float64(0.005818346330874868)), ('having', np.float64(0.005713373176259284)), ('im', np.float64(0.005645061530331892)), ('the', np.float64(0.005463392023347873)), ('this', np.float64(0.005456346875017717))]

Topic 3
[('hp', np.float64(0.07407604109062194)), ('pavilion', np.float64(0.07390169990602966)), ('issue', np.float64(0.006491097720912805)), ('having', np.float64(0.006109406362845568)), ('an', np.float64(0.005961229234847988)), ('for', np.float64(0.005820624419710114)), ('the', np.float64(0.0058202984265558625)), ('and', np.float64(0.00580538928295814)), ('with', np.float64(0.005693873196285028)), ('im', np.float64(0.00562005890715972))]

Topic 4
[('airpods', np.float64(0.07367744159750936)), ('apple', np.float64(0.07188978045377964)), ('product', np.float64(0.006204641924278955)), ('issue', np.float64(0.005980469591070366)), ('having', np.float64(0.005908015109191799)), ('with', np.float64(0.0057031992412966285)), ('it', np.float64(0.0055915311083533405)), ('an', np.float64(0.005569113164334431)), ('on', np.float64(0.005557204942408036)), ('this', np.float64(0.005435319752234446))]

Topic 5
[('versa', np.float64(0.07322690818826724)), ('smartwatch', np.float64(0.0730340033243446)), ('fitbit', np.float64(0.054545700785267756)), ('but', np.float64(0.005652196958267698)), ('ive', np.float64(0.0056149216149285605)), ('issue', np.float64(0.005395388796640727)), ('having', np.float64(0.005259184001741007)), ('the', np.float64(0.005246174303352115)), ('an', np.float64(0.005168974826985062)), ('to', np.float64(0.005078147317167869))]

Topic 6
[('nikon', np.float64(0.08391247950901752)), ('having', np.float64(0.006933021305406713)), ('an', np.float64(0.006870518023711181)), ('issue', np.float64(0.006710313115642273)), ('with', np.float64(0.006533494036014983)), ('support', np.float64(0.006080180281267111)), ('you', np.float64(0.005925199330535193)), ('the', np.float64(0.005830217078872967)), ('on', np.float64(0.005667623901821244)), ('purchased', np.float64(0.0056358854718270655))]

Topic 7
[('galaxy', np.float64(0.0806705033369976)), ('samsung', np.float64(0.059156596146323674)), ('having', np.float64(0.006508055286010735)), ('an', np.float64(0.006478847815919646)), ('null', np.float64(0.006345300929229108)), ('issue', np.float64(0.006212731658614285)), ('with', np.float64(0.006175502443022021)), ('this', np.float64(0.005851998860807604)), ('the', np.float64(0.0058079558034294125)), ('customer', np.float64(0.0057397535571898405))]

Topic 8
[('philips', np.float64(0.06623332697632563)), ('hue', np.float64(0.06623332697632563)), ('lights', np.float64(0.06615152689181016)), ('2k', np.float64(0.006938112313310546)), ('gaming', np.float64(0.006938112313310546)), ('an', np.float64(0.00622310211415854)), ('having', np.float64(0.0060084255674043244)), ('with', np.float64(0.00595869339428437)), ('issue', np.float64(0.005898371741584561)), ('the', np.float64(0.005712374417288801))]

Topic 9
[('washing', np.float64(0.0686948352700388)), ('machine', np.float64(0.06783024906011811)), ('lg', np.float64(0.03794286147323085)), ('please', np.float64(0.006435633908973415)), ('having', np.float64(0.005994991085472684)), ('an', np.float64(0.005949520314749023)), ('the', np.float64(0.005873771879765488)), ('issue', np.float64(0.0058244830794851234)), ('product', np.float64(0.005635571826724965)), ('with', np.float64(0.0056118430762167795))]

In [47]:
import re

products = (
    bertopic_dataset["Ticket Description"]
    .dropna()
    .astype(str)
    .unique()
)

# Sort longest first so multi-word product names are matched correctly
products = sorted(products, key=len, reverse=True)

def mask_product_names(text):
    text = str(text)

    for product in products:
        pattern = r"\b" + re.escape(product) + r"\b"
        text = re.sub(
            pattern,
            "PRODUCT",
            text,
            flags=re.IGNORECASE
        )

    return text


bertopic_dataset["bertopic_issue_text"] = (
    bertopic_dataset["bertopic_input"]
    .apply(mask_product_names)
)

print("Documents:", len(bertopic_dataset))
print(
    "Empty documents:",
    (bertopic_dataset["bertopic_issue_text"].str.strip() == "").sum()
)

print("\nExamples:")
display(
    bertopic_dataset[
        ["Ticket Description", "bertopic_issue_text"]
    ].head(10)
)

KeyboardInterrupt:

In [48]:
import re

# Get the actual product names from the dataset
products = (
    bertopic_dataset
    .merge(
        df[["Ticket ID", "Product Purchased"]],
        on="Ticket ID",
        how="left"
    )["Product Purchased"]
    .dropna()
    .astype(str)
    .unique()
)

# Longest first so multi-word products are matched first
products = sorted(products, key=len, reverse=True)

print("Unique products:", len(products))
print(products)

Unique products: 42
['Nintendo Switch Pro Controller', 'Microsoft Xbox Controller', 'Fitbit Versa Smartwatch', 'Bose SoundLink Speaker', 'Dyson Vacuum Cleaner', 'GoPro Action Camera', 'Roomba Robot Vacuum', 'Philips Hue Lights', 'LG Washing Machine', 'Microsoft Surface', 'Canon DSLR Camera', 'Bose QuietComfort', 'Garmin Forerunner', 'Microsoft Office', 'Autodesk AutoCAD', 'Sony PlayStation', 'Samsung Soundbar', 'Nintendo Switch', 'Nest Thermostat', 'Lenovo ThinkPad', 'Adobe Photoshop', 'Samsung Galaxy', 'Sony 4K HDR TV', 'Amazon Kindle', 'Fitbit Charge', 'Apple AirPods', 'Google Pixel', 'LG Smart TV', 'HP Pavilion', 'Amazon Echo', 'PlayStation', 'Sony Xperia', 'Google Nest', 'MacBook Pro', 'GoPro Hero', 'Canon EOS', 'Dell XPS', 'Asus ROG', 'LG OLED', 'Nikon D', 'iPhone', 'Xbox']

In [49]:
product_pattern = re.compile(
    r"\b(?:"
    + "|".join(re.escape(product) for product in products)
    + r")\b",
    flags=re.IGNORECASE
)

def mask_product_names(text):
    return product_pattern.sub("PRODUCT", str(text))


bertopic_dataset["bertopic_issue_text"] = (
    bertopic_dataset["bertopic_input"]
    .apply(mask_product_names)
)

print("Documents:", len(bertopic_dataset))
print(
    "Empty documents:",
    (bertopic_dataset["bertopic_issue_text"].str.strip() == "").sum()
)

Documents: 8469
Empty documents: 0

In [50]:
display(
    bertopic_dataset[
        ["Ticket ID", "Ticket Description", "bertopic_issue_text"]
    ].head(10)
)

,Ticket ID,Ticket Description,bertopic_issue_text
0,1,I'm having an issue with the GoPro Hero. Pleas...,I'm having an issue with the PRODUCT. Please d...
1,2,I'm having an issue with the LG Smart TV. Plea...,I'm having an issue with the PRODUCT. If you n...
2,3,I'm facing a problem with my Dell XPS. The Del...,I'm facing a problem with my PRODUCT. The PROD...
3,4,I'm having an issue with the Microsoft Office....,I'm having an issue with the PRODUCT. I've alr...
4,5,I'm having an issue with the Autodesk AutoCAD....,I'm having an issue with the PRODUCT. I've not...
5,6,I'm facing a problem with my Microsoft Office....,I'm facing a problem with my PRODUCT. The PROD...
6,7,I'm unable to access my Microsoft Surface acco...,I'm unable to access my PRODUCT account. It ke...
7,8,I'm having an issue with the Philips Hue Light...,I'm having an issue with the PRODUCT. I've per...
8,9,I'm having an issue with the Fitbit Versa Smar...,I'm having an issue with the PRODUCT. PRODUCT ...
9,10,My Dyson Vacuum Cleaner is making strange nois...,My PRODUCT is making strange noises and not fu...

In [51]:
GENERIC_OPENINGS = [
    "i'm having an issue with the product.",
    "i am having an issue with the product.",
    "i'm facing a problem with my product.",
    "i am facing a problem with my product.",
]

for phrase in GENERIC_OPENINGS:
    count = bertopic_dataset["bertopic_issue_text"].str.lower().str.startswith(phrase).sum()
    print(f"{phrase!r}: {count}")

print("\nTop exact opening phrases:")

opening_phrases = (
    bertopic_dataset["bertopic_issue_text"]
    .str.lower()
    .str.extract(r"^(.{0,80}?)(?:\.|!|\?)")[0]
    .value_counts()
    .head(15)
)

display(opening_phrases)

"i'm having an issue with the product.": 5868
'i am having an issue with the product.': 0
"i'm facing a problem with my product.": 179
'i am facing a problem with my product.': 0

Top exact opening phrases:

0
i'm having an issue with the product                                 5868
i'm unable to access my product account                               189
the product is unable to establish a stable internet connection       184
i'm encountering a software bug in the product                        183
my product is making strange noises and not functioning properly      182
i'm facing a problem with my product                                  179
i've noticed a software bug in the product app                        179
i'm having trouble connecting my product to my home wi-fi network     178
there seems to be a hardware problem with my product                  169
i've accidentally deleted important data from my product              165
there seems to be a glitch in the product software                    164
i've encountered a data loss issue with my product                    164
i'm facing issues logging into my product account                     154
my product crashed, and i lost all the data stored on it              145
Name: count, dtype: int64

In [52]:
GENERIC_PRODUCT_OPENINGS = {
    "i'm having an issue with the product.",
    "i'm facing a problem with my product.",
}

def remove_generic_product_opening(text):
    text = str(text).strip()

    sentences = re.split(r"(?<=[.!?])\s+", text)

    cleaned = [
        sentence.strip()
        for sentence in sentences
        if sentence.strip().lower() not in GENERIC_PRODUCT_OPENINGS
    ]

    return " ".join(cleaned).strip()


bertopic_dataset["bertopic_issue_text_v2"] = (
    bertopic_dataset["bertopic_issue_text"]
    .apply(remove_generic_product_opening)
)

print("Documents:", len(bertopic_dataset))

print(
    "Empty after Rule 3:",
    (bertopic_dataset["bertopic_issue_text_v2"].str.strip() == "").sum()
)

print(
    "Modified:",
    (
        bertopic_dataset["bertopic_issue_text_v2"]
        != bertopic_dataset["bertopic_issue_text"]
    ).sum()
)

print(
    "Average words:",
    bertopic_dataset["bertopic_issue_text_v2"]
    .str.split()
    .str.len()
    .mean()
)

display(
    bertopic_dataset[
        [
            "Ticket ID",
            "bertopic_issue_text",
            "bertopic_issue_text_v2"
        ]
    ].head(10)
)

Documents: 8469
Empty after Rule 3: 1
Modified: 6044
Average words: 37.18030464045342

,Ticket ID,bertopic_issue_text,bertopic_issue_text_v2
0,1,I'm having an issue with the PRODUCT. Please d...,Please double check your email address. I've t...
1,2,I'm having an issue with the PRODUCT. If you n...,If you need to change an existing product. If ...
2,3,I'm facing a problem with my PRODUCT. The PROD...,The PRODUCT is not turning on. It was working ...
3,4,I'm having an issue with the PRODUCT. I've alr...,I've already contacted customer support multip...
4,5,I'm having an issue with the PRODUCT. I've not...,I've noticed a sudden decrease in battery life...
5,6,I'm facing a problem with my PRODUCT. The PROD...,The PRODUCT is not turning on. It was working ...
6,7,I'm unable to access my PRODUCT account. It ke...,I'm unable to access my PRODUCT account. It ke...
7,8,I'm having an issue with the PRODUCT. I've per...,"I've performed a factory reset on my PRODUCT, ..."
8,9,I'm having an issue with the PRODUCT. PRODUCT ...,PRODUCT is not the exact type you might prefer...
9,10,My PRODUCT is making strange noises and not fu...,My PRODUCT is making strange noises and not fu...

In [53]:
empty_rule3 = bertopic_dataset[
    bertopic_dataset["bertopic_issue_text_v2"].str.strip() == ""
]

display(
    empty_rule3[
        [
            "Ticket ID",
            "Ticket Description",
            "bertopic_issue_text",
            "bertopic_issue_text_v2"
        ]
    ]
)

,Ticket ID,Ticket Description,bertopic_issue_text,bertopic_issue_text_v2
62,63,I'm having an issue with the Xbox. Please assi...,I'm having an issue with the PRODUCT.,

In [54]:
bertopic_training_data = bertopic_dataset[
    bertopic_dataset["bertopic_issue_text_v2"].str.strip() != ""
].copy()

print("Original documents:", len(bertopic_dataset))
print("BERTopic training documents:", len(bertopic_training_data))
print(
    "Excluded documents:",
    len(bertopic_dataset) - len(bertopic_training_data)
)

display(
    bertopic_dataset[
        bertopic_dataset["bertopic_issue_text_v2"].str.strip() == ""
    ][
        ["Ticket ID", "Ticket Description", "bertopic_issue_text_v2"]
    ]
)

Original documents: 8469
BERTopic training documents: 8468
Excluded documents: 1

,Ticket ID,Ticket Description,bertopic_issue_text_v2
62,63,I'm having an issue with the Xbox. Please assi...,

------------------------------modeltrainnig--------------------------

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    min_df=5
)

print("Vectorizer configured")
print("ngram_range:", vectorizer_model.ngram_range)
print("min_df:", vectorizer_model.min_df)
print("stop_words: english")

Vectorizer configured
ngram_range: (1, 2)
min_df: 5
stop_words: english

In [56]:
from bertopic import BERTopic

documents_v2 = (
    bertopic_training_data["bertopic_issue_text_v2"]
    .astype(str)
    .tolist()
)

topic_model_v2 = BERTopic(
    vectorizer_model=vectorizer_model,
    verbose=True
)

topics_v2, probabilities_v2 = topic_model_v2.fit_transform(
    documents_v2
)

print("Documents:", len(documents_v2))
print("Unique topic IDs:", len(set(topics_v2)))
print("Outliers (-1):", sum(topic == -1 for topic in topics_v2))

2026-09-14 00:18:31,228 - BERTopic - Embedding - Transforming documents to embeddings.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1815.37it/s]
Batches: 100%|██████████| 265/265 [01:26<00:00,  3.07it/s]
2026-09-14 00:20:04,913 - BERTopic - Embedding - Completed ✓
2026-09-14 00:20:04,915 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-09-14 00:20:09,627 - BERTopic - Dimensionality - Completed ✓
2026-09-14 00:20:09,627 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-09-14 00:20:09,954 - BERTopic - Cluster - Completed ✓
2026-09-14 00:20:09,961 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-09-14 00:20:10,694 - BERTopic - Representation - Completed ✓

Documents: 8468
Unique topic IDs: 124
Outliers (-1): 1646

In [57]:
topic_info_v2 = topic_model_v2.get_topic_info()

display(
    topic_info_v2[
        ["Topic", "Count", "Name", "Representation"]
    ].head(25)
)

,Topic,Count,Name,Representation
0,-1,1646,-1_ive_checked_ive checked_issue,"[ive, checked, ive checked, issue, product, up..."
1,0,346,0_error message_popping_peculiar error_peculiar,"[error message, popping, peculiar error, pecul..."
2,1,318,1_im concerned_concerned security_security pro...,"[im concerned, concerned security, security pr..."
3,2,312,2_updated firmware_afterward related_afterward...,"[updated firmware, afterward related, afterwar..."
4,3,282,3_update havent_occurring recent_started occur...,"[update havent, occurring recent, started occu..."
5,4,195,4_charger_original charger_product charging_ch...,"[charger, original charger, product charging, ..."
6,5,191,5_password_working_reset_product account,"[password, working, reset, product account, op..."
7,6,189,6_desired action_perform desired_unable option...,"[desired action, perform desired, unable optio..."
8,7,183,7_battery life_sudden decrease_used longer_sudden,"[battery life, sudden decrease, used longer, s..."
9,8,176,8_connection_internet_stable_keeps,"[connection, internet, stable, keeps, unable, ..."
10,9,175,9_problem product_hardware_screen_product screen,"[problem product, hardware, screen, product sc..."
11,10,149,10_logging_account_issues_product account,"[logging, account, issues, product account, sa..."
12,11,147,11_noticed software_loss unexpected_unexpected...,"[noticed software, loss unexpected, unexpected..."
13,12,146,12_productpurchased_id_productid_product product,"[productpurchased, id, productid, product prod..."
14,13,145,13_strange_product making_functioning_hardware...,"[strange, product making, functioning, hardwar..."
15,14,139,14_card_payment_credit_gift,"[card, payment, credit, gift, credit card, dev..."
16,15,139,15_price_prices_product price_issue persists,"[price, prices, product price, issue persists,..."
17,16,128,16_issue product_files_data loss_loss,"[issue product, files, data loss, loss, data, ..."
18,17,115,17_unexpectedly_acts unexpectedly_acts_times acts,"[unexpectedly, acts unexpectedly, acts, times ..."
19,18,111,18_use specific_application product_feature ap...,"[use specific, application product, feature ap..."
20,19,102,19_im encountering_perform specific_encounteri...,"[im encountering, perform specific, encounteri..."
21,20,97,20_require repair_repair replacement_hardwarer...,"[require repair, repair replacement, hardwarer..."
22,21,96,21_deleted_important data_ive accidentally_del...,"[deleted, important data, ive accidentally, de..."
23,22,91,22_peripherals_cables adapters_different cable...,"[peripherals, cables adapters, different cable..."
24,23,91,23_acts_unexpectedly_fine times_facing intermi...,"[acts, unexpectedly, fine times, facing interm..."

In [58]:
display(
    topic_info_v2[
        topic_info_v2["Topic"] != -1
    ][
        ["Topic", "Count", "Name", "Representation"]
    ]
    .sort_values("Count", ascending=False)
    .head(15)
)

,Topic,Count,Name,Representation
1,0,346,0_error message_popping_peculiar error_peculiar,"[error message, popping, peculiar error, pecul..."
2,1,318,1_im concerned_concerned security_security pro...,"[im concerned, concerned security, security pr..."
3,2,312,2_updated firmware_afterward related_afterward...,"[updated firmware, afterward related, afterwar..."
4,3,282,3_update havent_occurring recent_started occur...,"[update havent, occurring recent, started occu..."
5,4,195,4_charger_original charger_product charging_ch...,"[charger, original charger, product charging, ..."
6,5,191,5_password_working_reset_product account,"[password, working, reset, product account, op..."
7,6,189,6_desired action_perform desired_unable option...,"[desired action, perform desired, unable optio..."
8,7,183,7_battery life_sudden decrease_used longer_sudden,"[battery life, sudden decrease, used longer, s..."
9,8,176,8_connection_internet_stable_keeps,"[connection, internet, stable, keeps, unable, ..."
10,9,175,9_problem product_hardware_screen_product screen,"[problem product, hardware, screen, product sc..."
11,10,149,10_logging_account_issues_product account,"[logging, account, issues, product account, sa..."
12,11,147,11_noticed software_loss unexpected_unexpected...,"[noticed software, loss unexpected, unexpected..."
13,12,146,12_productpurchased_id_productid_product product,"[productpurchased, id, productid, product prod..."
14,13,145,13_strange_product making_functioning_hardware...,"[strange, product making, functioning, hardwar..."
15,14,139,14_card_payment_credit_gift,"[card, payment, credit, gift, credit card, dev..."

In [59]:
topic_12_docs = topic_model_v2.get_representative_docs(12)

print("Topic 12 representative documents:")
for i, doc in enumerate(topic_12_docs, 1):
    print(f"\n--- Document {i} ---")
    print(doc)

Topic 12 representative documents:

--- Document 1 ---
#PRODUCT.product " a[0].name = "panther" b[0].name = "peppermint The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Document 2 ---
PRODUCT PRODUCT if (product_name == "Raffle" ) The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Document 3 ---
Product ID # I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

In [60]:
contamination_patterns = [
    r"#PRODUCT",
    r"productid",
    r"product\.product",
    r"product id",
    r"\bif\s*\(\s*product_name",
    r"\ba\[\d+\]\.name\s*=",
    r"\bb\[\d+\]\.name\s*=",
]

for pattern in contamination_patterns:
    matches = bertopic_dataset["bertopic_issue_text_v2"].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    )

    print(f"{pattern:35} → {matches.sum()} documents")

#PRODUCT                            → 13 documents
productid                           → 13 documents
product\.product                    → 4 documents
product id                          → 62 documents
\bif\s*\(\s*product_name            → 2 documents
\ba\[\d+\]\.name\s*=                → 1 documents
\bb\[\d+\]\.name\s*=                → 1 documents

In [61]:
product_id_docs = bertopic_dataset[
    bertopic_dataset["bertopic_issue_text_v2"]
    .str.contains(r"\bproduct id\b", case=False, regex=True, na=False)
]

print("Documents containing 'product id':", len(product_id_docs))

display(
    product_id_docs[
        [
            "Ticket ID",
            "bertopic_issue_text_v2"
        ]
    ].head(20)
)

Documents containing 'product id': 58

      Ticket ID                             bertopic_issue_text_v2
77           78  Product #8 4-8-0-1 The product code on your pr...
194         195  (I'm using 'PRODUCT ' as a product id in my co...
494         495  Product ID: 294823 Model: D3-M3 Year: 2015 Gra...
778         779  Product ID: 0 Date of Use: 04/18/2018 format: ...
802         803  Product ID: 0 3 Sold Unavailable I'm not sure ...
878         879  Product ID: 1413882 Product ID: 1413882 Date: ...
1098       1099  If we missed any of the product details, pleas...
1126       1127  Product ID # I've followed the troubleshooting...
1154       1155  This is the product ID and it should not be in...
1342       1343  Product ID: 1680 Process: eos Total price: $12...
1437       1438  I was unable to download the Product ID for al...
1497       1498  $purchase = 0; # If the product ID is not the ...
1714       1715  Product ID: 2304 Product ID: 2304 Last update:...
1916       1917  When searching your items or checking out the ...
1946       1947  I'm facing issues logging into my PRODUCT acco...
2152       2153  3 1 0 Reviews Add to Cart Product ID: 0 I've n...
2168       2169  If I'm having an issue with my subscription th...
2261       2262  Product ID: 505 Size: 12-Pack Style: High-Dens...
2295       2296  Thank you! * When using product ID on a new Pr...
2308       2309  Add to cart The Product's ID number: The produ...

In [62]:
for _, row in product_id_docs.head(20).iterrows():
    print(f"\n{'=' * 80}")
    print("Ticket ID:", row["Ticket ID"])
    print(row["bertopic_issue_text_v2"])

================================================================================
Ticket ID: 78
Product #8 4-8-0-1 The product code on your product. #Product ID : PRODUCT I've checked the device settings and made sure that everything is configured correctly.

================================================================================
Ticket ID: 195
(I'm using 'PRODUCT ' as a product id in my code to indicate the 'id' I want to share). Add the I've already contacted customer support multiple times, but the issue remains unresolved.

================================================================================
Ticket ID: 495
Product ID: 294823 Model: D3-M3 Year: 2015 Grade: B2 Grade point: I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.

================================================================================
Ticket ID: 779
Product ID: 0 Date of Use: 04/18/2018 format: wb league: uk playback I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

================================================================================
Ticket ID: 803
Product ID: 0 3 Sold Unavailable I'm not sure if this issue is specific to my device or if others have reported similar problems.

================================================================================
Ticket ID: 879
Product ID: 1413882 Product ID: 1413882 Date: 11 Mar 2013 Update Date: 11-Mar 2013 0:06:36 This problem started occurring after the recent software update. I haven't made any other changes to the device.

================================================================================
Ticket ID: 1099
If we missed any of the product details, please email this post to the issue list. In the event that your Product ID is missing please send an email I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

================================================================================
Ticket ID: 1127
Product ID # I've followed the troubleshooting steps mentioned in the user manual, but the issue persists.

================================================================================
Ticket ID: 1155
This is the product ID and it should not be in the same category and not for different products. It must not be in a specific category and the reason I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

================================================================================
Ticket ID: 1343
Product ID: 1680 Process: eos Total price: $1245.95 A new way for users to pay via I'm using the original charger that came with my PRODUCT, but it's not charging properly.

================================================================================
Ticket ID: 1438
I was unable to download the Product ID for all the new ones that were added on September 20. You can visit this website for any product you find that you need The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

================================================================================
Ticket ID: 1498
$purchase = 0; # If the product ID is not the type of an existing order, an example: echo "There is I'm worried that the issue might be hardware-related and might require repair or replacement.

================================================================================
Ticket ID: 1715
Product ID: 2304 Product ID: 2304 Last update: 8/21/2017 Available: 5th of every month I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

================================================================================
Ticket ID: 1917
When searching your items or checking out the listing on Amazon, please use the Product ID of your credit card from Amazon.com. Once you have your Credit Card, I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

================================================================================
Ticket ID: 1947
I'm facing issues logging into my PRODUCT account. It says my account is locked. What should I do to unlock it? Step 2: Add your Product ID. I don't know if it's the product I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

================================================================================
Ticket ID: 2153
3 1 0 Reviews Add to Cart Product ID: 0 I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

================================================================================
Ticket ID: 2169
If I'm having an issue with my subscription the product code I'm sending to the email address given to me is incorrectly included in the product ID. Please I've tried using different cables, adapters, or peripherals with my PRODUCT, but the issue persists.

================================================================================
Ticket ID: 2262
Product ID: 505 Size: 12-Pack Style: High-Density Gloss Black Shipping Policy: $6.99 I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

================================================================================
Ticket ID: 2296
Thank you! * When using product ID on a new Product you are required to activate your account in iTunes Store. NOTE: This service gives YOU I've tried using different cables, adapters, or peripherals with my PRODUCT, but the issue persists.

================================================================================
Ticket ID: 2309
Add to cart The Product's ID number: The product ID displayed should read a product ID field that indicates your order is online. Your I've checked for software updates, and my PRODUCT is already running the latest version.

In [63]:
import re


def remove_confirmed_metadata_fragments(text):
    text = str(text)

    # Code-like fragments
    text = re.sub(
        r"\bif\s*\(\s*product_name\s*==.*?\)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\b[a-z]\[\d+\]\.name\s*=\s*['\"].*?['\"]",
        " ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\b(?:\$purchase|productid)\s*=\s*[^;]+;?",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # Explicit malformed Product-ID markers
    text = re.sub(
        r"#product\s*id\s*:\s*product\b",
        " ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\bproduct\s*id\s*#\b",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # Standalone marketplace/cart fragments
    text = re.sub(
        r"\b\d+\s+\d+\s+\d+\s+reviews\s+add\s+to\s+cart\b",
        " ",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"\badd\s+to\s+cart\b",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # Clean spacing
    text = re.sub(r"\s+", " ", text).strip()

    return text


bertopic_dataset["bertopic_issue_text_v3"] = (
    bertopic_dataset["bertopic_issue_text_v2"]
    .apply(remove_confirmed_metadata_fragments)
)

print("Documents:", len(bertopic_dataset))

print(
    "Empty after metadata cleanup:",
    (bertopic_dataset["bertopic_issue_text_v3"].str.strip() == "").sum()
)

print(
    "Modified:",
    (
        bertopic_dataset["bertopic_issue_text_v3"]
        != bertopic_dataset["bertopic_issue_text_v2"]
    ).sum()
)

Documents: 8469
Empty after metadata cleanup: 1
Modified: 25

In [64]:
empty_v3 = bertopic_dataset[
    bertopic_dataset["bertopic_issue_text_v3"].str.strip() == ""
]

display(
    empty_v3[
        [
            "Ticket ID",
            "Ticket Description",
            "bertopic_issue_text_v3"
        ]
    ]
)

,Ticket ID,Ticket Description,bertopic_issue_text_v3
62,63,I'm having an issue with the Xbox. Please assi...,

In [65]:
check_patterns = [
    r"#PRODUCT",
    r"product\.product",
    r"\bif\s*\(\s*product_name",
    r"\ba\[\d+\]\.name\s*=",
    r"\bb\[\d+\]\.name\s*=",
    r"\bproductid\b",
]

for pattern in check_patterns:
    count = bertopic_dataset["bertopic_issue_text_v3"].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{pattern:35} → {count}")

#PRODUCT                            → 12
product\.product                    → 4
\bif\s*\(\s*product_name            → 1
\ba\[\d+\]\.name\s*=                → 0
\bb\[\d+\]\.name\s*=                → 0
\bproductid\b                       → 10

In [66]:
remaining_patterns = {
    "#PRODUCT": r"#PRODUCT",
    "product.product": r"product\.product",
    "if product_name": r"\bif\s*\(\s*product_name",
    "productid": r"\bproductid\b",
}

for name, pattern in remaining_patterns.items():

    matches = bertopic_dataset[
        bertopic_dataset["bertopic_issue_text_v3"].str.contains(
            pattern,
            case=False,
            regex=True,
            na=False
        )
    ]

    print(f"\n{'=' * 90}")
    print(f"{name} → {len(matches)} documents")

    for _, row in matches.iterrows():
        print(f"\nTicket ID: {row['Ticket ID']}")
        print(row["bertopic_issue_text_v3"])

==========================================================================================
#PRODUCT → 12 documents

Ticket ID: 2419
#PRODUCT is the last name that the item has been sold so far.. $this can't be a product I ordered from and I'm missing The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

Ticket ID: 3195
Thanks. #PRODUCT We've received a message claiming to be from an individual here, but we are unable to confirm who I've already contacted customer support multiple times, but the issue remains unresolved.

Ticket ID: 4162
#purchase #id=1422 #product_sell #id=1421 #value@product_purchased #id=1420 #product_ I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

Ticket ID: 5207
#PRODUCT.product " m facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

Ticket ID: 5901
I'm having an issue with the code. $ ( '#product_purchasement' ). _ -> product_purchasement ([ 1 I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

Ticket ID: 6114
#PRODUCT will be accepted the next week if the name of the product you're looking at is currently in the PRODUCT I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

Ticket ID: 6185
I do not understand if this is a problem to some of our users. Thank you for your support. #ProductShop #Vacation_Rides #N I'm not sure if this issue is specific to my device or if others have reported similar problems.

Ticket ID: 6674
I'm unable to access my PRODUCT account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. #product_ I'm using the original charger that came with my PRODUCT, but it's not charging properly.

Ticket ID: 7839
#PRODUCT[name]. #PRODUCT[name] can't be shipped. If you will ship another product I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

Ticket ID: 7861
$( '#product-id' ).then( function( product ) product = $.promotions[product]; $.promotional_title I'm using the original charger that came with my PRODUCT, but it's not charging properly.

Ticket ID: 8193
#PRODUCT #can't be added in the config file! # The config file will have # I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

Ticket ID: 8399
#PRODUCT _ #. # I'm unable to find the option to perform the desired action in the PRODUCT.

==========================================================================================
product.product → 4 documents

Ticket ID: 3446
It is not a problem with the PRODUCT.product so please bring the order back on the same day and send some back, and in I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

Ticket ID: 4399
This section describes the functionality of the PRODUCT.product_method () method used by the Product Request Object. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

Ticket ID: 5207
#PRODUCT.product " m facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

Ticket ID: 8047
PRODUCT is not a valid key type by default PRODUCT of product.product You can set PRODUCT of I've noticed a sudden decrease in battery life on my PRODUCT. It used to last much longer.

==========================================================================================
if product_name → 1 documents

Ticket ID: 285
" > > Note: There may be a few of these errors on this page. if ( product_name =='\r ' I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

==========================================================================================
productid → 10 documents

Ticket ID: 485
if (!productID.length) I've checked for any available software updates for my PRODUCT, but there are none.

Ticket ID: 1146
ProductID 003FC58D F2F1033 F2F5F6FD I'm unable to find the option to perform the desired action in the PRODUCT.

Ticket ID: 1170
PRODUCT.add to ProductID, (

Ticket ID: 2691
ProductID.asc or PRODUCT.htm Please contact me and explain what your problem is. No matter if my I've tried different settings and configurations on my PRODUCT, but the issue persists.

Ticket ID: 2784
if ( ProductId. ProductID_OK ) else I'm using the original charger that came with my PRODUCT, but it's not charging properly.

Ticket ID: 3857
The ProductID number is a unique identifier that has no meaningful value with regards to what the supplier sold it for The product cannot be made available by I'm unable to find the option to perform the desired action in the PRODUCT.

Ticket ID: 4108
( defun myProductWanted ( item :Product, itemId :ProductId ) ( interactive )) ( println! ( "[Product added]" I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.

Ticket ID: 4548
# This code should remain in an active state. # The 'Product # is already active in a specified field. The 'Product ProductID' field shouldn't be This problem started occurring after the recent software update. I haven't made any other changes to the device.

Ticket ID: 7686
PRODUCT The Product Name. PRODUCT The Product Name (ProductID). PRODUCT The I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

Ticket ID: 8199
I need to add my PRODUCT to an item in the [ProductID] PRODUCT. I'm using the original charger that came with my PRODUCT, but it's not charging properly.

In [67]:
import re


def remove_final_confirmed_contamination(text):
    text = str(text)

    # Code-like product-name condition
    text = re.sub(
        r'if\s*\(\s*product_name\s*==.*?\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # JavaScript / code-style product references
    text = re.sub(
        r"\$\s*\(\s*['\"]#?product[^)]*['\"]\s*\).*?(?=I'm|I’m|The|My|I've|I’ve|This|There|It|I'm|If)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # Array/object code fragments
    text = re.sub(
        r'\b[a-z]\[\d+\]\.name\s*=\s*["\'].*?["\']',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Explicit malformed product markers
    text = re.sub(
        r'#product(?:\.product|[_a-z]*)?',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r'\bproduct\.product(?:_method)?\s*\([^)]*\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Code-style ProductID references
    text = re.sub(
        r'\b(?:productid|productId|ProductID)\b',
        ' ',
        text
    )

    # Clean leftover obvious code punctuation
    text = re.sub(
        r'(?<!\w)[\$#]\s*(?=[\(\[])',
        ' ',
        text
    )

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text


bertopic_dataset["bertopic_issue_text_final"] = (
    bertopic_dataset["bertopic_issue_text_v3"]
    .apply(remove_final_confirmed_contamination)
)

print("Documents:", len(bertopic_dataset))

print(
    "Empty documents:",
    (
        bertopic_dataset["bertopic_issue_text_final"]
        .str.strip() == ""
    ).sum()
)

print(
    "Modified:",
    (
        bertopic_dataset["bertopic_issue_text_final"]
        != bertopic_dataset["bertopic_issue_text_v3"]
    ).sum()
)

Documents: 8469
Empty documents: 1
Modified: 28

In [68]:
patterns = {
    "#PRODUCT": r"#PRODUCT",
    "product.product": r"product\.product",
    "if product_name": r"\bif\s*\(\s*product_name",
    "productID": r"\bproductid\b",
}

for name, pattern in patterns.items():

    count = bertopic_dataset[
        "bertopic_issue_text_final"
    ].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{name:25} → {count}")

#PRODUCT                  → 0
product.product           → 2
if product_name           → 1
productID                 → 3

In [69]:
display(
    bertopic_dataset[
        bertopic_dataset["bertopic_issue_text_final"].str.strip() == ""
    ][
        ["Ticket ID", "Ticket Description", "bertopic_issue_text_final"]
    ]
)

,Ticket ID,Ticket Description,bertopic_issue_text_final
62,63,I'm having an issue with the Xbox. Please assi...,

In [70]:
patterns = {
    "product.product": r"product\.product",
    "if product_name": r"\bif\s*\(\s*product_name",
    "productID": r"\bproductid\b",
}

for name, pattern in patterns.items():
    mask = bertopic_dataset["bertopic_issue_text_final"].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    )

    print(f"\n{'=' * 70}")
    print(f"{name} → {mask.sum()} matches")
    print("=" * 70)

    display(
        bertopic_dataset.loc[
            mask,
            [
                "Ticket ID",
                "Ticket Description",
                "bertopic_issue_text_v3",
                "bertopic_issue_text_final",
            ]
        ]
    )

======================================================================
product.product → 2 matches
======================================================================

,Ticket ID,Ticket Description,bertopic_issue_text_v3,bertopic_issue_text_final
3445,3446,I'm having an issue with the Apple AirPods. Pl...,It is not a problem with the PRODUCT.product s...,It is not a problem with the PRODUCT.product s...
8046,8047,I'm having an issue with the Autodesk AutoCAD....,PRODUCT is not a valid key type by default PRO...,PRODUCT is not a valid key type by default PRO...

======================================================================
if product_name → 1 matches
======================================================================

,Ticket ID,Ticket Description,bertopic_issue_text_v3,bertopic_issue_text_final
284,285,I'm having an issue with the Microsoft Xbox Co...,""" > > Note: There may be a few of these errors...",""" > > Note: There may be a few of these errors..."

======================================================================
productID → 3 matches
======================================================================

,Ticket ID,Ticket Description,bertopic_issue_text_v3,bertopic_issue_text_final
484,485,I'm having an issue with the Canon DSLR Camera...,if (!productID.length) I've checked for any av...,if (!productID.length) I've checked for any av...
2783,2784,I'm having an issue with the Adobe Photoshop. ...,if ( ProductId. ProductID_OK ) else I'm using ...,if ( ProductId. ProductID_OK ) else I'm using ...
4107,4108,I'm having an issue with the iPhone. Please as...,"( defun myProductWanted ( item :Product, itemI...","( defun myProductWanted ( item :Product, itemI..."

In [71]:
def remove_last_confirmed_contamination(text):
    text = str(text)

    # JavaScript / code-style ProductID checks
    text = re.sub(
        r'if\s*\(\s*!?\s*productid\s*\.?\s*[a-z_]*\s*\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # ProductId/ProductID conditional code
    text = re.sub(
        r'if\s*\(\s*productid\s*\.\s*productid_ok\s*\)\s*else',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Lisp/Common-Lisp style product function fragment
    text = re.sub(
        r'\(\s*defun\s+myproductwanted\b.*?\)',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Remaining PRODUCT.product contamination
    text = re.sub(
        r'\bproduct\.product\b',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Remaining code-style ProductID tokens
    text = re.sub(
        r'\bproductid\b',
        ' ',
        text,
        flags=re.IGNORECASE
    )

    # Clean obvious leftover code punctuation
    text = re.sub(r'\s+', ' ', text).strip()

    return text


bertopic_dataset["bertopic_issue_text_final_v2"] = (
    bertopic_dataset["bertopic_issue_text_final"]
    .apply(remove_last_confirmed_contamination)
)

In [72]:
print("Documents:", len(bertopic_dataset))

print(
    "Empty documents:",
    (
        bertopic_dataset["bertopic_issue_text_final_v2"]
        .str.strip() == ""
    ).sum()
)

print(
    "Modified:",
    (
        bertopic_dataset["bertopic_issue_text_final_v2"]
        != bertopic_dataset["bertopic_issue_text_final"]
    ).sum()
)

Documents: 8469
Empty documents: 1
Modified: 5

In [73]:
patterns = {
    "product.product": r"product\.product",
    "if product_name": r"\bif\s*\(\s*product_name",
    "productID": r"\bproductid\b",
    "defun myProductWanted": r"\bdefun\s+myProductWanted\b",
}

for name, pattern in patterns.items():
    count = bertopic_dataset[
        "bertopic_issue_text_final_v2"
    ].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    ).sum()

    print(f"{name:25} → {count}")

product.product           → 0
if product_name           → 1
productID                 → 0
defun myProductWanted     → 0

In [74]:
bertopic_training_data = bertopic_dataset[
    bertopic_dataset["bertopic_issue_text_final_v2"].str.strip() != ""
].copy()

documents = (
    bertopic_training_data["bertopic_issue_text_final_v2"]
    .astype(str)
    .tolist()
)

print("Training documents:", len(documents))

Training documents: 8468

In [75]:
import numpy as np
import pandas as pd

from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer

print("BERTopic:", __import__("bertopic").__version__)
print("UMAP:", __import__("umap").__version__)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

BERTopic: 0.17.4
UMAP: 0.5.12
NumPy: 2.4.6
Pandas: 3.0.3

In [76]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42,
)

print(umap_model)

UMAP(metric='cosine', min_dist=0.0, n_components=5, random_state=42)

In [77]:
hdbscan_model = HDBSCAN(
    min_cluster_size=30,
    min_samples=10,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True,
)

print(hdbscan_model)

HDBSCAN(min_cluster_size=30, min_samples=10, prediction_data=True)

In [78]:
vectorizer_model = CountVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    min_df=5,
)

print(vectorizer_model)

CountVectorizer(min_df=5, ngram_range=(1, 2), stop_words='english')

In [79]:
from fastembed import TextEmbedding

embedding_model = TextEmbedding(
    model_name="BAAI/bge-base-en-v1.5"
)

print("Embedding model loaded:")
print(embedding_model.model_name)

Embedding model loaded:
BAAI/bge-base-en-v1.5

In [80]:
topic_model = BERTopic(
    embedding_model=None,          # We will provide our own BGE embeddings
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    verbose=True,
)

print(topic_model)

BERTopic(calculate_probabilities=False, ctfidf_model=ClassTfidfTransformer(...), embedding_model=None, hdbscan_model=HDBSCAN(...), language=english, low_memory=False, min_topic_size=10, n_gram_range=(1, 1), nr_topics=None, representation_model=None, seed_topic_list=None, top_n_words=10, umap_model=UMAP(...), vectorizer_model=CountVectorizer(...), verbose=True, zeroshot_min_similarity=0.7, zeroshot_topic_list=None)

In [81]:
print("Documents:", len(documents))
print("Column:", "bertopic_issue_text_final_v2")

print("\nFirst 3 modelling documents:\n")

for i, text in enumerate(documents[:3], start=1):
    print(f"--- Document {i} ---")
    print(text)
    print()

Documents: 8468
Column: bertopic_issue_text_final_v2

First 3 modelling documents:

--- Document 1 ---
Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

--- Document 2 ---
If you need to change an existing product. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

--- Document 3 ---
The PRODUCT is not turning on. It was working fine until yesterday, but now it doesn't respond. 1.8.3 I really I'm using the original charger that came with my PRODUCT, but it's not charging properly.

In [82]:
# Inspect the shortest modelling documents.
lengths = (
    bertopic_training_data["bertopic_issue_text_final_v2"]
    .astype(str)
    .str.split()
    .str.len()
)

shortest = bertopic_training_data.loc[
    lengths.nsmallest(30).index,
    [
        "Ticket ID",
        "Ticket Description",
        "bertopic_issue_text_final_v2",
    ],
].copy()

display(shortest)

,Ticket ID,Ticket Description,bertopic_issue_text_final_v2
728,729,I'm having an issue with the LG Washing Machin...,<Exclude
7200,7201,I'm having an issue with the iPhone. Please as...,;
8331,8332,I'm having an issue with the Microsoft Xbox Co...,""""
790,791,I'm having an issue with the LG OLED. Please a...,""" )"
4601,4602,I'm having an issue with the Apple AirPods. Pl...,Note: This
6440,6441,I'm having an issue with the Roomba Robot Vacu...,## var
1169,1170,I'm having an issue with the Canon EOS. Please...,"PRODUCT.add to , ("
7034,7035,I'm having an issue with the Asus ROG. Please ...,I appreciate your time. return export
3,4,I'm having an issue with the Microsoft Office....,I've already contacted customer support multip...
1242,1243,I'm having an issue with the HP Pavilion. Plea...,I've already contacted customer support multip...
1656,1657,I'm having an issue with the Google Nest. Plea...,I've already contacted customer support multip...
1761,1762,I'm having an issue with the Asus ROG. Please ...,I've already contacted customer support multip...
2037,2038,I'm having an issue with the Apple AirPods. Pl...,I've already contacted customer support multip...
2196,2197,I'm having an issue with the Dyson Vacuum Clea...,I've already contacted customer support multip...
2249,2250,I'm having an issue with the Xbox. Please assi...,I've already contacted customer support multip...
2487,2488,I'm having an issue with the LG Smart TV. Plea...,I've already contacted customer support multip...
2857,2858,I'm having an issue with the Nikon D. Please a...,I've already contacted customer support multip...
3084,3085,I'm having an issue with the Nintendo Switch P...,I've already contacted customer support multip...
3640,3641,I'm having an issue with the Roomba Robot Vacu...,I've already contacted customer support multip...
3708,3709,I'm having an issue with the Bose QuietComfort...,I've already contacted customer support multip...
3883,3884,I'm having an issue with the MacBook Pro. Plea...,I've already contacted customer support multip...
4464,4465,I'm having an issue with the LG Smart TV. Plea...,I've already contacted customer support multip...
4491,4492,I'm having an issue with the Microsoft Office....,I've already contacted customer support multip...
4579,4580,I'm having an issue with the Xbox. Please assi...,I've already contacted customer support multip...
4823,4824,I'm having an issue with the Autodesk AutoCAD....,I've already contacted customer support multip...
4876,4877,I'm having an issue with the Fitbit Charge. Pl...,I've already contacted customer support multip...
5679,5680,I'm having an issue with the Amazon Echo. Plea...,I've already contacted customer support multip...
5726,5727,I'm having an issue with the PlayStation. Plea...,I've already contacted customer support multip...
5913,5914,I'm having an issue with the GoPro Hero. Pleas...,I've already contacted customer support multip...
6642,6643,I'm having an issue with the Microsoft Office....,I've already contacted customer support multip...

In [83]:
print("Word-count statistics:")
print(lengths.describe())

print("\nDocuments with <= 10 words:", (lengths <= 10).sum())
print("Documents with <= 15 words:", (lengths <= 15).sum())
print("Documents with <= 20 words:", (lengths <= 20).sum())

Word-count statistics:
count    8468.000000
mean       37.163321
std         9.530127
min         1.000000
25%        33.000000
50%        40.000000
75%        44.000000
max        61.000000
Name: bertopic_issue_text_final_v2, dtype: float64

Documents with <= 10 words: 8
Documents with <= 15 words: 290
Documents with <= 20 words: 754

In [84]:
short_mask = (
    bertopic_training_data["bertopic_issue_text_final_v2"]
    .astype(str)
    .str.split()
    .str.len()
    <= 10
)

display(
    bertopic_training_data.loc[
        short_mask,
        [
            "Ticket ID",
            "Ticket Subject",
            "Ticket Description",
            "bertopic_issue_text_final_v2",
        ],
    ]
)

,Ticket ID,Ticket Subject,Ticket Description,bertopic_issue_text_final_v2
728,729,Delivery problem,I'm having an issue with the LG Washing Machin...,<Exclude
790,791,Product recommendation,I'm having an issue with the LG OLED. Please a...,""" )"
1169,1170,Battery life,I'm having an issue with the Canon EOS. Please...,"PRODUCT.add to , ("
4601,4602,Peripheral compatibility,I'm having an issue with the Apple AirPods. Pl...,Note: This
6440,6441,Cancellation request,I'm having an issue with the Roomba Robot Vacu...,## var
7034,7035,Product setup,I'm having an issue with the Asus ROG. Please ...,I appreciate your time. return export
7200,7201,Product compatibility,I'm having an issue with the iPhone. Please as...,;
8331,8332,Cancellation request,I'm having an issue with the Microsoft Xbox Co...,""""

In [85]:
INVALID_BERTOPIC_TICKETS = {
    63,
    728,
    790,
    1169,
    4601,
    6440,
    7034,
    7200,
    8331,
}

bertopic_training_data_final = bertopic_dataset[
    ~bertopic_dataset["Ticket ID"].isin(INVALID_BERTOPIC_TICKETS)
].copy()

documents_final = (
    bertopic_training_data_final[
        "bertopic_issue_text_final_v2"
    ]
    .astype(str)
    .tolist()
)

print("Original documents:", len(bertopic_dataset))
print("Excluded documents:", len(INVALID_BERTOPIC_TICKETS))
print("Final BERTopic documents:", len(documents_final))
print(
    "Empty documents:",
    (
        bertopic_training_data_final[
            "bertopic_issue_text_final_v2"
        ].str.strip() == ""
    ).sum()
)

Original documents: 8469
Excluded documents: 9
Final BERTopic documents: 8460
Empty documents: 0

In [86]:
embeddings = np.array(
    list(
        embedding_model.embed(
            documents_final
        )
    )
)

print("Embedding shape:", embeddings.shape)
print("Embedding dtype:", embeddings.dtype)
print("Expected documents:", len(documents_final))

Embedding shape: (8460, 768)
Embedding dtype: float32
Expected documents: 8460

In [87]:
from pathlib import Path

embedding_path = Path(
    r"C:\Users\danie\supportmind-ai\data\processed\supportmind_bertopic_embeddings.npy"
)

np.save(embedding_path, embeddings)

print("Saved:", embedding_path)
print("File exists:", embedding_path.exists())
print("Shape:", np.load(embedding_path, mmap_mode="r").shape)

Saved: C:\Users\danie\supportmind-ai\data\processed\supportmind_bertopic_embeddings.npy
File exists: True
Shape: (8460, 768)

In [88]:
topics, probabilities = topic_model.fit_transform(
    documents_final,
    embeddings=embeddings,
)

print("Training complete.")
print("Documents:", len(topics))
print("Unique topic IDs:", len(set(topics)))
print("Outliers (-1):", sum(t == -1 for t in topics))

2026-09-14 01:21:15,922 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-09-14 01:21:28,724 - BERTopic - Dimensionality - Completed ✓
2026-09-14 01:21:28,724 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-09-14 01:21:28,876 - BERTopic - Cluster - Completed ✓
2026-09-14 01:21:28,879 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-09-14 01:21:29,168 - BERTopic - Representation - Completed ✓

Training complete.
Documents: 8460
Unique topic IDs: 60
Outliers (-1): 1379

In [89]:
topic_info = topic_model.get_topic_info()

display(
    topic_info[
        ["Topic", "Count", "Name"]
    ].head(20)
)

    Topic  Count                                               Name
0      -1   1379                        -1_issue_problem_device_ive
1       0    393  0_productivity_need assistance_assistance soon...
2       1    349  1_error message_screen says_popping_popping pr...
3       2    335  2_updated firmware_happening afterward_afterwa...
4       3    318  3_software updates_updates product_updates_ive...
5       4    306  4_acts unexpectedly_acts_intermittent works_fi...
6       5    294  5_action product_option perform_perform desire...
7       6    273  6_im concerned_security product_like ensure_en...
8       7    229                      7_errors_app_product app_loss
9       8    228  8_used longer_sudden_sudden decrease_noticed s...
10      9    211                      9_connect_fails_set_available
11     10    193          10_account_logging_issues_product account
12     11    182  11_problem product_hardware_screen_product screen
13     12    179  12_original charger_using original_charger cam...
14     13    175                13_connection_internet_stable_keeps
15     14    171   14_yesterday_working fine_doesnt respond_respond
16     15    169  15_peripherals_adapters peripherals_cables_per...
17     16    166             16_deleted_important_product way_files
18     17    148          17_connecting_having trouble_home_trouble
19     18    145                        18_lost_stored_data_recover

In [90]:
print("Total topics excluding outlier:", (topic_info["Topic"] != -1).sum())
print("Outlier count:", topic_info.loc[topic_info["Topic"] == -1, "Count"].iloc[0])

print("\nTopic size statistics:")
print(
    topic_info.loc[
        topic_info["Topic"] != -1,
        "Count"
    ].describe()
)

Total topics excluding outlier: 59
Outlier count: 1379

Topic size statistics:
count     59.000000
mean     120.016949
std       94.198706
min       31.000000
25%       46.000000
50%       77.000000
75%      170.000000
max      393.000000
Name: Count, dtype: float64

In [91]:
for topic_id in topic_info.loc[
    topic_info["Topic"] != -1,
    "Topic"
].head(30):

    print(f"\n{'=' * 70}")
    print(f"TOPIC {topic_id}")
    print("=" * 70)

    words = topic_model.get_topic(topic_id)

    print(
        ", ".join(
            f"{word} ({score:.3f})"
            for word, score in words[:10]
        )
    )

======================================================================
TOPIC 0
======================================================================
productivity (0.085), need assistance (0.063), assistance soon (0.062), affecting work (0.062), possible affecting (0.062), work productivity (0.062), affecting (0.062), soon possible (0.062), assistance (0.061), soon (0.060)

======================================================================
TOPIC 1
======================================================================
error message (0.077), screen says (0.077), popping (0.077), popping product (0.077), noticed peculiar (0.077), message popping (0.077), peculiar (0.077), peculiar error (0.077), message (0.071), product screen (0.067)

======================================================================
TOPIC 2
======================================================================
updated firmware (0.072), happening afterward (0.072), afterward (0.072), afterward related (0.072), started happening (0.072), related update (0.072), firmware product (0.072), issue started (0.072), recently updated (0.072), firmware (0.072)

======================================================================
TOPIC 3
======================================================================
software updates (0.098), updates product (0.097), updates (0.094), ive checked (0.082), checked (0.082), checked software (0.066), running latest (0.066), product running (0.066), latest version (0.065), latest (0.063)

======================================================================
TOPIC 4
======================================================================
acts unexpectedly (0.080), acts (0.080), intermittent works (0.080), fine times (0.080), times acts (0.080), facing intermittent (0.080), unexpectedly (0.080), intermittent (0.080), works fine (0.079), issue im (0.078)

======================================================================
TOPIC 5
======================================================================
action product (0.102), option perform (0.102), perform desired (0.102), desired action (0.102), unable option (0.102), desired (0.101), perform (0.089), action (0.088), option (0.087), im unable (0.080)

======================================================================
TOPIC 6
======================================================================
im concerned (0.092), security product (0.092), like ensure (0.092), ensure data (0.092), concerned security (0.092), concerned (0.092), safe (0.092), data safe (0.092), product like (0.091), security (0.091)

======================================================================
TOPIC 7
======================================================================
errors (0.068), app (0.063), product app (0.057), loss (0.056), software bug (0.054), bug product (0.054), bug (0.054), ive noticed (0.037), noticed (0.037), software (0.034)

======================================================================
TOPIC 8
======================================================================
used longer (0.099), sudden (0.099), sudden decrease (0.099), noticed sudden (0.099), life product (0.099), decrease battery (0.099), battery life (0.098), decrease (0.098), product used (0.098), battery (0.098)

======================================================================
TOPIC 9
======================================================================
connect (0.089), fails (0.088), set (0.088), available (0.058), ive recently (0.057), recently (0.056), ive (0.025), network (0.022), connecting (0.019), product (0.017)

======================================================================
TOPIC 10
======================================================================
account (0.096), logging (0.075), issues (0.061), product account (0.060), says (0.046), im facing (0.046), facing (0.046), im (0.027), log (0.020), login (0.018)

======================================================================
TOPIC 11
======================================================================
problem product (0.084), hardware (0.078), screen (0.073), product screen (0.062), im unable (0.055), use (0.052), unable (0.050), problem (0.042), im (0.029), product (0.016)

======================================================================
TOPIC 12
======================================================================
original charger (0.116), using original (0.116), charger came (0.116), product charging (0.116), came product (0.116), charging properly (0.116), charger (0.116), charging (0.116), came (0.114), original (0.110)

======================================================================
TOPIC 13
======================================================================
connection (0.118), internet (0.118), stable (0.112), keeps (0.087), unable (0.060), network (0.024), product (0.018), persists product (0.018), router (0.015), product product (0.013)

======================================================================
TOPIC 14
======================================================================
yesterday (0.110), working fine (0.109), doesnt respond (0.109), respond (0.106), working (0.081), doesnt (0.080), fine (0.063), product (0.018), persists product (0.014), productivity product (0.013)

======================================================================
TOPIC 15
======================================================================
peripherals (0.100), adapters peripherals (0.099), cables (0.099), peripherals product (0.099), cables adapters (0.099), different cables (0.099), adapters (0.099), using different (0.098), tried using (0.098), different (0.073)

======================================================================
TOPIC 16
======================================================================
deleted (0.154), important (0.093), product way (0.092), files (0.078), recover (0.074), data product (0.073), way (0.068), data (0.047), ive (0.024), product (0.016)

======================================================================
TOPIC 17
======================================================================
connecting (0.151), having trouble (0.096), home (0.094), trouble (0.094), network (0.086), im having (0.078), having (0.072), devices (0.071), doesnt (0.070), fine (0.052)

======================================================================
TOPIC 18
======================================================================
lost (0.173), stored (0.109), data (0.091), recover (0.090), way (0.077), product (0.018), data ive (0.015), thanks (0.014), update product (0.014), persists product (0.013)

======================================================================
TOPIC 19
======================================================================
didnt help (0.076), product hoping (0.076), performed factory (0.076), performed (0.076), ive performed (0.076), hoping resolve (0.076), hoping (0.076), problem didnt (0.076), reset product (0.076), factory reset (0.076)

======================================================================
TOPIC 20
======================================================================
price (0.050), multiple (0.024), customer (0.020), issue persists (0.020), persists (0.020), customer support (0.019), issue (0.018), multiple times (0.018), unresolved (0.018), remains (0.018)

======================================================================
TOPIC 21
======================================================================
tried clearing (0.102), cache data (0.102), clearing cache (0.101), app issue (0.101), clearing (0.101), cache (0.101), data product (0.083), product app (0.082), app (0.073), ive tried (0.060)

======================================================================
TOPIC 22
======================================================================
crashes (0.086), product try (0.082), bug (0.070), software bug (0.069), bug product (0.068), application (0.066), try (0.061), perform (0.057), action (0.056), specific (0.053)

======================================================================
TOPIC 23
======================================================================
password (0.162), working (0.070), reset (0.067), option (0.066), product account (0.064), account (0.064), ive (0.024), product (0.016), product ive (0.016), unexpectedly ive (0.012)

======================================================================
TOPIC 24
======================================================================
device (0.033), paypal (0.028), update havent (0.027), started occurring (0.027), changes device (0.027), recent software (0.027), occurring recent (0.027), havent changes (0.027), occurring (0.027), software update (0.027)

======================================================================
TOPIC 25
======================================================================
update havent (0.083), changes device (0.083), started occurring (0.083), occurring recent (0.083), havent changes (0.083), recent software (0.083), occurring (0.083), software update (0.083), problem started (0.083), recent (0.082)

======================================================================
TOPIC 26
======================================================================
issue product (0.093), loss (0.093), files (0.092), data (0.050), issue (0.033), ive (0.029), persists ive (0.026), product ive (0.023), thanks (0.021), productivity ive (0.019)

======================================================================
TOPIC 27
======================================================================
consistently (0.086), occurs consistently (0.086), consistently use (0.086), feature application (0.086), issue occurs (0.086), application product (0.086), use specific (0.086), noticed issue (0.086), specific feature (0.086), occurs (0.085)

======================================================================
TOPIC 28
======================================================================
unresolved (0.092), remains unresolved (0.092), support multiple (0.092), remains (0.092), multiple times (0.092), issue remains (0.092), contacted customer (0.092), times issue (0.092), ive contacted (0.092), contacted (0.092)

======================================================================
TOPIC 29
======================================================================
glitch (0.093), glitch product (0.092), frequently making (0.090), freezes frequently (0.090), difficult use (0.090), product software (0.090), making difficult (0.090), software freezes (0.090), freezes (0.090), frequently (0.089)

In [92]:
for topic_id in range(30):

    if topic_id not in topic_model.get_topics():
        continue

    print(f"\n{'=' * 80}")
    print(f"TOPIC {topic_id}")
    print("=" * 80)

    docs = topic_model.get_representative_docs(topic_id)

    for i, doc in enumerate(docs[:5], start=1):
        print(f"\n{i}. {doc}")

================================================================================
TOPIC 0
================================================================================

1. 1.4.9 [3DS] [NieR:Automata] NieR:Automata [3DS] I need assistance as soon as possible because it's affecting my work and productivity.

2. minutes_to_update?app_id=152634 I need assistance as soon as possible because it's affecting my work and productivity.

3. PRODUCT <div I need assistance as soon as possible because it's affecting my work and productivity.

================================================================================
TOPIC 1
================================================================================

1. _______________________________________________ I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

2. I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

3. I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

================================================================================
TOPIC 2
================================================================================

1. I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

2. 0x0000000000000 0x00000000000000 0x00000000000000 0x00000000000000 0x00000000000000 0 I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

3. 0.00015735595957 0.00015735595957 0.00015735595957 0 I've recently updated the firmware of my PRODUCT, and the issue started happening afterward. Could it be related to the update?

================================================================================
TOPIC 3
================================================================================

1. I've checked for software updates, and my PRODUCT is already running the latest version.

2. The P. J. I've checked for software updates, and my PRODUCT is already running the latest version.

3. I've checked for software updates, and my PRODUCT is already running the latest version.

================================================================================
TOPIC 4
================================================================================

1. Thanks. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

2. PRODUCT The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

3. -@sj @rp_i @l2o_b @v5c @w4f6t The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

================================================================================
TOPIC 5
================================================================================

1. d-> ; / This I'm unable to find the option to perform the desired action in the PRODUCT.

2. I'm unable to find the option to perform the desired action in the PRODUCT.

3. I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 6
================================================================================

1. Thanks. I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

2. 0b9e5c49-48c7-43a9-ab85-9e39ad8d2f9c1 I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

3. <!-- // // // // </ I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

================================================================================
TOPIC 7
================================================================================

1. I've noticed a software bug in the PRODUCT app. It's causing data loss and unexpected errors. Go to any PRODUCT app or PRODUCT I'm worried that the issue might be hardware-related and might require repair or replacement.

2. I've noticed a software bug in the PRODUCT app. It's causing data loss and unexpected errors. I need assistance as soon as possible because it's affecting my work and productivity.

3. I've noticed a software bug in the PRODUCT app. It's causing data loss and unexpected errors. Open the PRODUCT app with the This problem started occurring after the recent software update. I haven't made any other changes to the device.

================================================================================
TOPIC 8
================================================================================

1. I've noticed a sudden decrease in battery life on my PRODUCT. It used to last much longer.

2. I've noticed a sudden decrease in battery life on my PRODUCT. It used to last much longer.

3. Product Name : B-30B-SLS 1 3T 5.6Ghz (CAS #5C-4539-3-1 I've noticed a sudden decrease in battery life on my PRODUCT. It used to last much longer.

================================================================================
TOPIC 9
================================================================================

1. I've recently set up my PRODUCT, but it fails to connect to any available networks. Step 1: Check my network. If it fails to connect to This problem started occurring after the recent software update. I haven't made any other changes to the device.

2. I've recently set up my PRODUCT, but it fails to connect to any available networks. To get to the network I'm looking for, connect to a I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

3. I've recently set up my PRODUCT, but it fails to connect to any available networks. What if I can't get the app to connect to all available This problem started occurring after the recent software update. I haven't made any other changes to the device.

================================================================================
TOPIC 10
================================================================================

1. I'm facing issues logging into my PRODUCT account. It says my account is locked. What should I do to unlock it? I'm facing issues logging into my PRODUCT account. It I'm concerned about the security of my PRODUCT and would like to ensure that my data is safe.

2. I'm facing issues logging into my PRODUCT account. It says my account is locked. What should I do to unlock it?. To log into your PRODUCT account, I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

3. I'm facing issues logging into my PRODUCT account. It says my account is locked. What should I do to unlock it? "I'm facing issues logging into my PRODUCT account. I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 11
================================================================================

1. There seems to be a hardware problem with my PRODUCT. The screen is flickering, and I'm unable to use it. There seems to be a hardware problem with my PRODUCT I've checked for any available software updates for my PRODUCT, but there are none.

2. There seems to be a hardware problem with my PRODUCT. The screen is flickering, and I'm unable to use it. It seems to be a hardware problem with my device. The screen is flickering, I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

3. There seems to be a hardware problem with my PRODUCT. The screen is flickering, and I'm unable to use it. There seems to be a hardware problem with my PRODUCT I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 12
================================================================================

1. I'm using the original charger that came with my PRODUCT, but it's not charging properly.

2. I'm using the original charger that came with my PRODUCT, but it's not charging properly.

3. I'm using the original charger that came with my PRODUCT, but it's not charging properly.

================================================================================
TOPIC 13
================================================================================

1. The PRODUCT is unable to establish a stable internet connection. It keeps disconnecting intermittently. If there is a stable Internet connection, you could attempt that network connection I'm worried that the issue might be hardware-related and might require repair or replacement.

2. The PRODUCT is unable to establish a stable internet connection. It keeps disconnecting intermittently. PRODUCT is unable to establish a stable internet connection. I need assistance as soon as possible because it's affecting my work and productivity.

3. The PRODUCT is unable to establish a stable internet connection. It keeps disconnecting intermittently. PRODUCT is also unable to establish a stable internet connection I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

================================================================================
TOPIC 14
================================================================================

1. The PRODUCT is not turning on. It was working fine until yesterday, but now it doesn't respond. So now, I must give my I'm unable to find the option to perform the desired action in the PRODUCT.

2. The PRODUCT is not turning on. It was working fine until yesterday, but now it doesn't respond. I'm unable to find the option to perform the desired action in the PRODUCT.

3. The PRODUCT is not turning on. It was working fine until yesterday, but now it doesn't respond. It's not working fine again. I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

================================================================================
TOPIC 15
================================================================================

1. I've tried using different cables, adapters, or peripherals with my PRODUCT, but the issue persists.

2. p I've tried using different cables, adapters, or peripherals with my PRODUCT, but the issue persists.

3. I've tried using different cables, adapters, or peripherals with my PRODUCT, but the issue persists.

================================================================================
TOPIC 16
================================================================================

1. I've accidentally deleted important data from my PRODUCT. Is there any way to recover the deleted files? I've accidentally deleted important data from my PRODUCT. Is there any I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

2. I've accidentally deleted important data from my PRODUCT. Is there any way to recover the deleted files? I've accidentally deleted important data from my PRODUCT. Is there any I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

3. I've accidentally deleted important data from my PRODUCT. Is there any way to recover the deleted files? I've accidentally deleted important data from my PRODUCT. Is there any I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 17
================================================================================

1. I'm having trouble connecting my PRODUCT to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. If you've been I'm unable to find the option to perform the desired action in the PRODUCT.

2. I'm having trouble connecting my PRODUCT to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. I'm unable to find the option to perform the desired action in the PRODUCT.

3. I'm having trouble connecting my PRODUCT to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. I'm having trouble I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 18
================================================================================

1. My PRODUCT crashed, and I lost all the data stored on it. Is there any way to recover the lost data? I have no information, is there any way to recover data with the lost information? I've tried different settings and configurations on my PRODUCT, but the issue persists.

2. My PRODUCT crashed, and I lost all the data stored on it. Is there any way to recover the lost data? And is the "data is not readable" really a way to recover lost data? I I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

3. My PRODUCT crashed, and I lost all the data stored on it. Is there any way to recover the lost data? A: I lost all the data stored on this system at once. Even before my name I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 19
================================================================================

1. If it's not working I can't help you. I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

2. The PRODUCT. I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

3. "0":[1, "1"][e:6a4,6a58,6 I've performed a factory reset on my PRODUCT, hoping it would resolve the problem, but it didn't help.

================================================================================
TOPIC 20
================================================================================

1. < < Your name Company Product Name Address poorest price Description </ I've already contacted customer support multiple times, but the issue remains unresolved.

2. The price has changed for the [brand_id] and for the [product_name] from [product_name] to [product_brand_id]. I've already contacted customer support multiple times, but the issue remains unresolved.

3. Somewhere. Sneak a peopie at me and I'll help set the price so I can find enough to throw my kids I've already contacted customer support multiple times, but the issue remains unresolved.

================================================================================
TOPIC 21
================================================================================

1. I've tried clearing the cache and data for the PRODUCT app, but the issue persists.

2. I've tried clearing the cache and data for the PRODUCT app, but the issue persists.

3. I've tried clearing the cache and data for the PRODUCT app, but the issue persists.

================================================================================
TOPIC 22
================================================================================

1. I'm encountering a software bug in the PRODUCT. Whenever I try to perform a specific action, the application crashes. A software bug in the PRODUCT backups I've noticed a peculiar error message popping up on my PRODUCT screen. It says ''.

2. I'm encountering a software bug in the PRODUCT. Whenever I try to perform a specific action, the application crashes. If there are updates, please update them. If it's I'm unable to find the option to perform the desired action in the PRODUCT.

3. I'm encountering a software bug in the PRODUCT. Whenever I try to perform a specific action, the application crashes. I'm experiencing a software bug in the PRODUCT I've checked for any available software updates for my PRODUCT, but there are none.

================================================================================
TOPIC 23
================================================================================

1. I've forgotten my password for my PRODUCT account, and the password reset option is not working. PRODUCT PRODUCT, password You can recover the I've checked for any available software updates for my PRODUCT, but there are none.

2. I've forgotten my password for my PRODUCT account, and the password reset option is not working. By submitting code to reset your password, please do NOT post to /u/Verm I'm unable to find the option to perform the desired action in the PRODUCT.

3. I've forgotten my password for my PRODUCT account, and the password reset option is not working. The only way to recover or reset the password is via another service: I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 24
================================================================================

1. Otherwise, we may make the payment via credit or debit. We have no involvement in our products or services. This problem started occurring after the recent software update. I haven't made any other changes to the device.

2. If I have an issue please have a note in the "Paypal/Email address listed as "contact". Thank you again Ange. - - - - - - This problem started occurring after the recent software update. I haven't made any other changes to the device.

3. Purchased from: In the U. S. P. G. with a credit or debit card. Last updated: 12/ This problem started occurring after the recent software update. I haven't made any other changes to the device.

================================================================================
TOPIC 25
================================================================================

1. The base plate is missing a metal bracket. This problem started occurring after the recent software update. I haven't made any other changes to the device.

2. I'd love to see you. -- V. S. R. S. A V. S. R. S. A. This problem started occurring after the recent software update. I haven't made any other changes to the device.

3. Thanks. This problem started occurring after the recent software update. I haven't made any other changes to the device.

================================================================================
TOPIC 26
================================================================================

1. I've encountered a data loss issue with my PRODUCT. All the files and documents seem to have disappeared. Thanks I've encountered a data loss issue with my I've already contacted customer support multiple times, but the issue remains unresolved.

2. I've encountered a data loss issue with my PRODUCT. All the files and documents seem to have disappeared. I've encountered a data loss issue with my PRODUCT I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

3. I've encountered a data loss issue with my PRODUCT. All the files and documents seem to have disappeared. I've encountered a data loss issue with my last product. I'm unable to find the option to perform the desired action in the PRODUCT.

================================================================================
TOPIC 27
================================================================================

1. Thanks. I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

2. Thank you in everything. :) I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

3. " ", JSON.stringify(' 'key_image': ); var I've noticed that the issue occurs consistently when I use a specific feature or application on my PRODUCT.

================================================================================
TOPIC 28

In [93]:
topic_info = topic_model.get_topic_info()

topic_sizes = (
    topic_info[
        topic_info["Topic"] != -1
    ]["Count"]
)

print("Number of topics:", len(topic_sizes))
print("Minimum topic size:", topic_sizes.min())
print("Median topic size:", topic_sizes.median())
print("Mean topic size:", topic_sizes.mean())
print("Maximum topic size:", topic_sizes.max())

print("\nSmall topics:")
print((topic_sizes < 30).sum())

print("\nTopics with 30+ documents:")
print((topic_sizes >= 30).sum())

Number of topics: 59
Minimum topic size: 31
Median topic size: 77.0
Mean topic size: 120.01694915254237
Maximum topic size: 393

Small topics:
0

Topics with 30+ documents:
59

In [95]:
topic_assignments = topic_model.topics_

outlier_count = sum(topic == -1 for topic in topic_assignments)
total_documents = len(topic_assignments)

outlier_rate = outlier_count / total_documents * 100
assigned_count = total_documents - outlier_count

print("Total documents:", total_documents)
print("Outlier documents:", outlier_count)
print(f"Outlier rate: {outlier_rate:.2f}%")
print("Assigned to topics:", assigned_count)
print(f"Assigned rate: {assigned_count / total_documents * 100:.2f}%")

Total documents: 8460
Outlier documents: 1379
Outlier rate: 16.30%
Assigned to topics: 7081
Assigned rate: 83.70%

In [96]:
id="r4k8pn"
topic_info = topic_model.get_topic_info()

topic_words = []

for topic_id in topic_info["Topic"]:
    if topic_id == -1:
        continue

    words = [
        word
        for word, score in topic_model.get_topic(topic_id)[:10]
    ]

    topic_words.extend(words)

unique_words = set(topic_words)

topic_diversity = len(unique_words) / len(topic_words)

print("Topics evaluated:", len(topic_words) // 10)
print("Top words per topic: 10")
print("Total topic words:", len(topic_words))
print("Unique topic words:", len(unique_words))
print(f"Topic diversity: {topic_diversity:.4f}")

Topics evaluated: 59
Top words per topic: 10
Total topic words: 590
Unique topic words: 353
Topic diversity: 0.5983

In [98]:
from gensim.corpora import Dictionary
from gensim.models.coherencemodel import CoherenceModel

# Tokenize the same corpus used for BERTopic
tokenized_documents = [
    doc.lower().split()
    for doc in documents_final
]

# Build dictionary
dictionary = Dictionary(tokenized_documents)

# Get top words for each discovered topic
topic_words_for_coherence = []

for topic_id in topic_model.get_topics():
    if topic_id == -1:
        continue

    words = [
        word
        for word, score in topic_model.get_topic(topic_id)[:10]
    ]

    topic_words_for_coherence.append(words)

# Calculate C_V coherence
coherence_model = CoherenceModel(
    topics=topic_words_for_coherence,
    texts=tokenized_documents,
    dictionary=dictionary,
    coherence="c_v",
)

coherence_score = coherence_model.get_coherence()

print(f"Number of topics evaluated: {len(topic_words_for_coherence)}")
print(f"Coherence (C_V): {coherence_score:.4f}")

Number of topics evaluated: 59
Coherence (C_V): 0.7972

In [100]:
# Step 1 — Create topic assignments

topic_results = bertopic_training_data_final[
    [
        "Ticket ID",
        "Ticket Subject",
        "bertopic_issue_text_final_v2",
    ]
].copy()

# Add product metadata from the original dataset
topic_results = topic_results.merge(
    df[
        [
            "Ticket ID",
            "Product Purchased",
        ]
    ],
    on="Ticket ID",
    how="left",
    validate="one_to_one",
)

# Attach BERTopic assignments
topic_results["Topic ID"] = topics

print("Rows:", len(topic_results))
print("Columns:", topic_results.columns.tolist())

print("\nMissing product values:")
print(topic_results["Product Purchased"].isna().sum())

print("\nTopic assignment counts:")
print(topic_results["Topic ID"].value_counts().head(15))

Rows: 8460
Columns: ['Ticket ID', 'Ticket Subject', 'bertopic_issue_text_final_v2', 'Product Purchased', 'Topic ID']

Missing product values:
0

Topic assignment counts:
Topic ID
-1     1379
 0      393
 1      349
 2      335
 3      318
 4      306
 5      294
 6      273
 7      229
 8      228
 9      211
 10     193
 11     182
 12     179
 13     175
Name: count, dtype: int64

In [101]:
# Step 2 — Add topic metadata

topic_info = topic_model.get_topic_info()

topic_metadata = topic_info[
    [
        "Topic",
        "Count",
        "Name",
    ]
].copy()

topic_metadata = topic_metadata.rename(
    columns={
        "Topic": "Topic ID",
        "Count": "Topic Size",
        "Name": "Topic Name",
    }
)

topic_results = topic_results.merge(
    topic_metadata,
    on="Topic ID",
    how="left",
    validate="many_to_one",
)

print("Rows:", len(topic_results))
print("Columns:", topic_results.columns.tolist())

print("\nMissing topic metadata:")
print(topic_results[["Topic Size", "Topic Name"]].isna().sum())

print("\nSample:")
print(
    topic_results[
        [
            "Ticket ID",
            "Product Purchased",
            "Topic ID",
            "Topic Size",
            "Topic Name",
        ]
    ].head(10)
)

Rows: 8460
Columns: ['Ticket ID', 'Ticket Subject', 'bertopic_issue_text_final_v2', 'Product Purchased', 'Topic ID', 'Topic Size', 'Topic Name']

Missing topic metadata:
Topic Size    0
Topic Name    0
dtype: int64

Sample:
   Ticket ID        Product Purchased  Topic ID  Topic Size  \
0          1               GoPro Hero        31          71
1          2              LG Smart TV         4         306
2          3                 Dell XPS        14         171
3          4         Microsoft Office        40          48
4          5         Autodesk AutoCAD         8         228
5          6         Microsoft Office        14         171
6          7        Microsoft Surface        33          70
7          8       Philips Hue Lights        47          44
8          9  Fitbit Versa Smartwatch         2         335
9         10     Dyson Vacuum Cleaner        -1        1379

                                          Topic Name
0  31_steps mentioned_mentioned user_manual issue...
1  4_acts unexpectedly_acts_intermittent works_fi...
2   14_yesterday_working fine_doesnt respond_respond
3  40_unresolved ive_multiple times_remains unres...
4  8_used longer_sudden_sudden decrease_noticed s...
5   14_yesterday_working fine_doesnt respond_respond
6  33_login information_account keeps_displaying_...
7  47_didnt help_performed factory_ive performed_...
8  2_updated firmware_happening afterward_afterwa...
9                        -1_issue_problem_device_ive

In [102]:
# Step 3 — Extract topic keywords

topic_keywords = []

for topic_id in topic_model.get_topics():

    if topic_id == -1:
        continue

    words_with_scores = topic_model.get_topic(topic_id)

    for rank, (word, score) in enumerate(
        words_with_scores[:10],
        start=1,
    ):
        topic_keywords.append(
            {
                "Topic ID": topic_id,
                "Rank": rank,
                "Word": word,
                "Score": score,
            }
        )

topic_keywords_df = pd.DataFrame(topic_keywords)

print("Rows:", len(topic_keywords_df))
print("Topics:", topic_keywords_df["Topic ID"].nunique())
print("Keywords per topic:",
      topic_keywords_df.groupby("Topic ID").size().unique())

print("\nSample:")
print(topic_keywords_df.head(20))

Rows: 590
Topics: 59
Keywords per topic: [10]

Sample:
    Topic ID  Rank                Word     Score
0          0     1        productivity  0.084889
1          0     2     need assistance  0.062560
2          0     3     assistance soon  0.062461
3          0     4      affecting work  0.062461
4          0     5  possible affecting  0.062461
5          0     6   work productivity  0.062461
6          0     7           affecting  0.062409
7          0     8       soon possible  0.061639
8          0     9          assistance  0.061389
9          0    10                soon  0.059863
10         1     1       error message  0.076980
11         1     2         screen says  0.076740
12         1     3             popping  0.076740
13         1     4     popping product  0.076740
14         1     5    noticed peculiar  0.076740
15         1     6     message popping  0.076740
16         1     7            peculiar  0.076740
17         1     8      peculiar error  0.076740
18         1     9             message  0.071253
19         1    10      product screen  0.067446

In [103]:
# Step 4 — Create compact topic summary

topic_summary = (
    topic_keywords_df
    .sort_values(["Topic ID", "Rank"])
    .groupby("Topic ID")
    .agg(
        Top_Keywords=("Word", lambda x: ", ".join(x))
    )
    .reset_index()
)

topic_summary = topic_summary.merge(
    topic_metadata[
        ["Topic ID", "Topic Size", "Topic Name"]
    ],
    on="Topic ID",
    how="left",
    validate="one_to_one",
)

topic_summary = topic_summary[
    [
        "Topic ID",
        "Topic Size",
        "Topic Name",
        "Top_Keywords",
    ]
].sort_values("Topic ID")

print("Topics:", len(topic_summary))
print("Columns:", topic_summary.columns.tolist())

print("\nSample:")
print(topic_summary.head(10).to_string(index=False))

Topics: 59
Columns: ['Topic ID', 'Topic Size', 'Topic Name', 'Top_Keywords']

Sample:
 Topic ID  Topic Size                                                         Topic Name                                                                                                                                                        Top_Keywords
        0         393      0_productivity_need assistance_assistance soon_affecting work                   productivity, need assistance, assistance soon, affecting work, possible affecting, work productivity, affecting, soon possible, assistance, soon
        1         349                1_error message_screen says_popping_popping product                          error message, screen says, popping, popping product, noticed peculiar, message popping, peculiar, peculiar error, message, product screen
        2         335 2_updated firmware_happening afterward_afterward_afterward related updated firmware, happening afterward, afterward, afterward related, started happening, related update, firmware product, issue started, recently updated, firmware
        3         318             3_software updates_updates product_updates_ive checked                         software updates, updates product, updates, ive checked, checked, checked software, running latest, product running, latest version, latest
        4         306             4_acts unexpectedly_acts_intermittent works_fine times                          acts unexpectedly, acts, intermittent works, fine times, times acts, facing intermittent, unexpectedly, intermittent, works fine, issue im
        5         294     5_action product_option perform_perform desired_desired action                                         action product, option perform, perform desired, desired action, unable option, desired, perform, action, option, im unable
        6         273            6_im concerned_security product_like ensure_ensure data                                    im concerned, security product, like ensure, ensure data, concerned security, concerned, safe, data safe, product like, security
        7         229                                      7_errors_app_product app_loss                                                                      errors, app, product app, loss, software bug, bug product, bug, ive noticed, noticed, software
        8         228                8_used longer_sudden_sudden decrease_noticed sudden                                 used longer, sudden, sudden decrease, noticed sudden, life product, decrease battery, battery life, decrease, product used, battery
        9         211                                      9_connect_fails_set_available                                                                           connect, fails, set, available, ive recently, recently, ive, network, connecting, product

In [104]:
from pathlib import Path

# Step 5 — Save BERTopic outputs

output_dir = Path(
    r"C:\Users\danie\supportmind-ai\data\processed\bertopic"
)

output_dir.mkdir(
    parents=True,
    exist_ok=True,
)

topic_results_path = output_dir / "bertopic_ticket_topic_assignments.csv"
topic_summary_path = output_dir / "bertopic_topic_summary.csv"
topic_keywords_path = output_dir / "bertopic_topic_keywords.csv"

topic_results.to_csv(
    topic_results_path,
    index=False,
)

topic_summary.to_csv(
    topic_summary_path,
    index=False,
)

topic_keywords_df.to_csv(
    topic_keywords_path,
    index=False,
)

print("Saved:")
print(topic_results_path)
print(topic_summary_path)
print(topic_keywords_path)

print("\nFile existence:")
print("Ticket assignments:", topic_results_path.exists())
print("Topic summary:", topic_summary_path.exists())
print("Topic keywords:", topic_keywords_path.exists())

Saved:
C:\Users\danie\supportmind-ai\data\processed\bertopic\bertopic_ticket_topic_assignments.csv
C:\Users\danie\supportmind-ai\data\processed\bertopic\bertopic_topic_summary.csv
C:\Users\danie\supportmind-ai\data\processed\bertopic\bertopic_topic_keywords.csv

File existence:
Ticket assignments: True
Topic summary: True
Topic keywords: True

In [105]:
from pathlib import Path

# Step 6 — Prepare production model directory

model_dir = Path(
    r"C:\Users\danie\supportmind-ai\backend\app\nlp\topic_modeling\models\supportmind_bertopic"
)

model_dir.mkdir(
    parents=True,
    exist_ok=True,
)

print("Model directory:")
print(model_dir)

print("\nDirectory exists:", model_dir.exists())
print("Is directory:", model_dir.is_dir())

Model directory:
C:\Users\danie\supportmind-ai\backend\app\nlp\topic_modeling\models\supportmind_bertopic

Directory exists: True
Is directory: True

In [106]:
# Step 6b — Save the trained BERTopic model

topic_model.save(
    str(model_dir),
    serialization="safetensors",
    save_ctfidf=True,
)

print("BERTopic model saved successfully.")
print("Model path:")
print(model_dir)

BERTopic model saved successfully.
Model path:
C:\Users\danie\supportmind-ai\backend\app\nlp\topic_modeling\models\supportmind_bertopic

In [107]:
from bertopic import BERTopic

# Step 7 — Reload the persisted BERTopic model

loaded_topic_model = BERTopic.load(
    str(model_dir)
)

print("Model reloaded successfully.")

print("\nNumber of topics:")
print(len(loaded_topic_model.get_topic_info()) - 1)

print("\nTopic 1:")
print(loaded_topic_model.get_topic(1)[:10])

2026-09-14 02:01:31,730 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

Model reloaded successfully.

Number of topics:
59

Topic 1:
[['error message', 0.07697975308529437], ['screen says', 0.07673994564065258], ['popping', 0.07673994564065258], ['popping product', 0.07673994564065258], ['noticed peculiar', 0.07673994564065258], ['message popping', 0.07673994564065258], ['peculiar', 0.07673994564065258], ['peculiar error', 0.07673994564065258], ['message', 0.07125273849138684], ['product screen', 0.06744600748972363]]

In [108]:
# Step 8 — Validate inference using the reloaded model

test_documents = documents_final[:5]

inferred_topics, inferred_probabilities = (
    loaded_topic_model.transform(
        test_documents,
        embeddings=embeddings[:5],
    )
)

for i, (document, topic_id) in enumerate(
    zip(test_documents, inferred_topics),
    start=1,
):
    print(f"\n{'=' * 70}")
    print(f"TEST DOCUMENT {i}")
    print(f"{'=' * 70}")
    print("Topic ID:", topic_id)
    print("Text:", document[:300])

2026-09-14 02:02:36,841 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

======================================================================
TEST DOCUMENT 1
======================================================================
Topic ID: 31
Text: Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

======================================================================
TEST DOCUMENT 2
======================================================================
Topic ID: 4
Text: If you need to change an existing product. If The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.

======================================================================
TEST DOCUMENT 3
======================================================================
Topic ID: 14
Text: The PRODUCT is not turning on. It was working fine until yesterday, but now it doesn't respond. 1.8.3 I really I'm using the original charger that came with my PRODUCT, but it's not charging properly.

======================================================================
TEST DOCUMENT 4
======================================================================
Topic ID: 40
Text: I've already contacted customer support multiple times, but the issue remains unresolved.

======================================================================
TEST DOCUMENT 5
======================================================================
Topic ID: 8
Text: I've noticed a sudden decrease in battery life on my PRODUCT. It used to last much longer.

🎯 BERTopic is now DONE

We have completed the entire target-driven workflow:

Final Clean Dataset
        ↓
Targeted EDA
        ↓
Targeted preprocessing
        ↓
Product masking
        ↓
BERTopic training corpus
        ↓
BERTopic model
        ↓
Evaluation
        ↓
59 useful topics
        ↓
Production artifacts
        ↓
Save
        ↓
Reload
        ↓
Inference validation ✅
Locked model

BERTopic 0.17.4

Embeddings: BGE-base-en-v1.5 / 768D
UMAP: 15 neighbors, 5 components, cosine
HDBSCAN: min cluster size 30, min samples 10
Vectorizer: English stop words, 1–2 grams, min_df=5
Training documents: 8,460
Topics: 59
Topic coverage: 83.70%
Outliers: 16.30%
Topic diversity: 0.5983
C_V coherence: 0.7972
Saved artifacts
data/processed/
├── supportmind_bertopic_cleaned_dataset.csv
├── supportmind_bertopic_embeddings.npy
└── bertopic/
    ├── bertopic_ticket_topic_assignments.csv
    ├── bertopic_topic_summary.csv
    └── bertopic_topic_keywords.csv

Model:

backend/app/nlp/topic_modeling/models/
└── supportmind_bertopic/

No further tuning is required. We have a model that fits its actual SupportMind role.

The next NLP/ML work should therefore start with the next dataset/task, while keeping the same rule: choose the model because the dataset provides a valid training signal and the model has a real role in SupportMind—not because we want more models.